### DISCUSSION TITLE
Multi-provider authentication

### DISCUSSION THREAD

**Discussion by geo-house** [lexik/LexikJWTAuthenticationBundle#1103] [Q&A]
Hello! 
It is necessary to implement the entry of Employees(User) and Customers in one api.
How to authenticate with multiple providers?
It is my security.yaml. It does not work. How to do API authentication (api, api2 section)?

```
security:
    encoders:
        App\Entity\Employees:
            algorithm: bcrypt
        App\Entity\Customers:
            algorithm: bcrypt
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Employees
                property: username
        app_customer_provider:
            entity:
                class: App\Entity\Customers
                property: username
    firewalls:
        login:
            security: true
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            lazy: true
            json_login:
                provider: app_user_provider
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        lklogin:
            security: true
            pattern:  ^/api/customers/login
            stateless: true
            anonymous: true
            lazy: true
            json_login:
                provider: app_customer_provider
                check_path: /api/customers/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        api:
            security: true
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

         api2:
            security: true
            pattern: ^/api
            stateless: true
            provider: app_customer_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator


        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

    access_control:
        - { path: ^/api/customers/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```
