### DISCUSSION TITLE
Symfony 6.4 JWT authentication not working lexik_jwt_authentication.jwt_manager

### DISCUSSION THREAD

**Discussion by BrunoKingbee** [lexik/LexikJWTAuthenticationBundle#1190] [Q&A]
Situation: recently upgraded project from symfony 5.4 to 6.4 and getting error: 
`
Authenticator &quot;Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager&quot; must implement &quot;Symfony\Component\Security\Http\Authenticator\AuthenticatorInterface&quot;. (500 Internal Server Error)
`

**security.yaml**

```
security:
    firewalls:
        health:
            pattern:  "/api/health"
            stateless: true
            #anonymous: true
            custom_authenticators:
                - lexik_jwt_authentication.jwt_manager
            provider: folderz_db_provider
```

**Version: 2.20.3**

How do i configure symfony 6.4 project to use lexik authenticator?
