### ISSUE TITLE
Login does not return the User, only the token

### ISSUE THREAD

**Issue by martinszeltins** [lexik/LexikJWTAuthenticationBundle#1002]
Hi, I would like to get back the token AND the user after a successful login but I get this back in response:

````
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NDk4NjkxNzQsImV4cCI6MTY0OTg3Mjc3NCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lI....."
}
````

But I would like it to also automatically return the User as well like this:

````
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NDk4NjkxNzQsImV4cCI6MTY0OTg3Mjc3NCwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lI....."
  "user": { id: 1, username: 'password' }
}
````

Is there a way I can enable this?

This is my security.yaml

````
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login,       roles: PUBLIC_ACCESS }
        - { path: ^/api,             roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
````

I am using Symfony 6
