### ISSUE TITLE
Symfony 6 Guard\AuthenticatorInterface not found

### ISSUE THREAD

**Issue by stipic** [lexik/LexikJWTAuthenticationBundle#1009]
Hello,

im working on project upgrade, from symfony 5.0 to symfony 6.0 and im using:

` "lexik/jwt-authentication-bundle": "^2.15.1"`

when composer install finished i get:

```
PHP Fatal error:  Uncaught Error: Interface "Symfony\Component\Security\Guard\AuthenticatorInterface" not found in xyz/vendor/lexik/jwt-authentication-bundle/Security/Guard/JWTTokenAuthenticator.php:44
Stack trace:
#0 xyz/vendor/composer/ClassLoader.php(571): include()
#1 xyz/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 xyz/vendor/symfony/security-bundle/DependencyInjection/Compiler/RegisterEntryPointPass.php(53): is_a()
#4 xyz/vendor/symfony/dependency-injection/Compiler/Compiler.php(73): Symfony\Bundle\SecurityBundle\DependencyInjection\Compiler\RegisterEntryPointPass->process()
#5 xyz/vendor/symfony/dependency-injection/ContainerBuilder.php(716): Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
#6 xyz/vendor/symfony/http-kernel/Kernel.php(540): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#7 xyz/vendor/symfony/http-kernel/Kernel.php(769): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#8 xyz/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#9 xyz/vendor/symfony/framework-bundle/Console/Application.php(166): Symfony\Component\HttpKernel\Kernel->boot()
#10 xyz/vendor/symfony/framework-bundle/Console/Application.php(72): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#11 xyz/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#12 xyz/bin/console(39): Symfony\Component\Console\Application->run()
#13 {main}
  thrown in xyz/vendor/lexik/jwt-authentication-bundle/Security/Guard/JWTTokenAuthenticator.php on line 44
```

JWTTokenAuthenticator.php extends AuthenticatorInterface that dosen't exist.

**Comment by chalasr** [comment]
Hi,

The guard component has been removed from Symfony 6.0. You need to adjust your security configuration to stop relying on the guard-based jwt authenticator. See https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/UPGRADE-2.12.md#upgrade-from-211-to-212

**Comment by stipic** [comment]
Thank you for fast reply.
This is my security.yaml

I still get same error. Not sure why still want to go on gard-based jwt authenticator.

```
security:

    enable_authenticator_manager: true
    
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        ROLE_SUPPORT_AGENT:         [ROLE_SUPPORT_AGENT]
        ROLE_REVIEWER:              [ROLE_SUPPORT_AGENT, ROLE_REVIEWER]
        ROLE_PROOF_READER:          [ROLE_PROOF_READER, ROLE_REVIEWER]
        ROLE_AUTHOR:                [ROLE_AUTHOR, ROLE_PROOF_READER]
        ROLE_EDITOR:                [ROLE_AUTHOR, ROLE_EDITOR]
        ROLE_WORKSPACE_ADMIN:       [ROLE_EDITOR, ROLE_WORKSPACE_ADMIN]
        ROLE_ORGANIZATION_ADMIN:    [ROLE_WORKSPACE_ADMIN, ROLE_ORGANIZATION_ADMIN]
        ROLE_SUPERADMIN:            [ROLE_ORGANIZATION_ADMIN, ROLE_SUPERADMIN]

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # zastita admina s lokalnim userima
        admin:
            pattern: ^/admin
            # anonymous: false
            provider: entity_provider   
            http_basic: ~
            logout: ~

        # zastita logova s lokalnim userima
        audit_logs:
            pattern: ^/audit
            # anonymous: false
            provider: entity_provider   
            http_basic: ~
            logout: ~

        # zastita api docsa s lokalnim userima
        api_docs:
            pattern: ^/api/?$
            # anonymous: false
            provider: entity_provider            
            http_basic: ~
            logout: ~

        login:
            pattern:  ^/login
            stateless: true
            # anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_path: _username
                password_path: _password
        zendesk_sso:
            pattern:  ^/zendesk/sso_login
            stateless: true
            # anonymous: true
            custom_authenticators:
                - App\Security\ZendeskAuthenticator
        zendesk:
            pattern:  ^/zendesk
            stateless: true
            # anonymous: false
            jwt: ~

        register:
            pattern:  ^/register
            stateless: true
            # anonymous: true

        api:
            pattern:   ^/api/
            stateless: true
            jwt: ~

        multimedia_metadata:
            pattern:   ^/multimedia/
            stateless: true
            jwt: ~
        
        uploader:
            pattern: ^/_uploader/
            stateless: true
            jwt: ~

        refresh:
            pattern:  ^/token/refresh
            stateless: true
            # anonymous: true

        component: 
            pattern: ^/component/
            # anonymous: false
            stateless: true
            jwt: ~
    
        component_delete:
            pattern:   ^/delete/component/files
            # anonymous: false
            stateless: true
            jwt: ~

        component_files:
            pattern:   ^/list/component/files
            # anonymous: false
            stateless: true
            jwt: ~

        page_order:
            pattern:   ^/page/reorder
            # anonymous: false
            stateless: true
            jwt: ~   

        page_preview:
             pattern:   ^/preview/page
            #  anonymous: true #ovo mora biti "anoonymous: true" zbog preview tokena
             stateless: true
             custom_authenticators:
                - App\Security\PagePreviewJWTAuthenticator

        exporter:
            pattern: ^/export/
            # anonymous: false
            stateless: true
            jwt: ~
                    
        # must go last !!!
        main:
            # anonymous: true
            stateless: true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/zendesk/sso_login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/zendesk, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/.*,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/*, roles: ROLE_SUPERADMIN }
```
