### ISSUE TITLE
[RESOLVED] CURL works - AngularJS get a 401 Bad Credentials

### ISSUE THREAD

**Issue by Morgiver** [lexik/LexikJWTAuthenticationBundle#102]
Hi,

I'm trying to use the bundle, but i'm blocked when i want to post credentials with AngularJS.

The server side working fine, when i'm using the curl command, it's return the token.
But when i'm using the $http.post() function in AngularJS, it's returning 401 Bad Credentials response.

Here's my code on Client side : 
```javascript
function loginCheck(data) {
        var defer = $q.defer();
            
        $http.post('api/login_check', data, { ignoreAuthModule: true }).then(function(success) {
            defer.resolve(success);
        }, function(error) {
            defer.reject(error);
        });
            
        return defer.promise;
}
```

Here's my security.yml

```yaml
# app/config/security.yml
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: user
                        roles: 'ROLE_USER'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter:       _username
                password_parameter:       _password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        
        api: 
            pattern: ^/api
            stateless: true
            lexik_jwt: ~
    
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
```
Did i miss something ?

Thx in advance for help :)

Morgiver
