### ISSUE TITLE
Addition of the token in the headers

### ISSUE THREAD

**Issue by itokia** [lexik/LexikJWTAuthenticationBundle#1034]
Hello,

I have set up an api under api_platform with JWT and I would like to add the token in the headers when connecting.
I'm on symfony 5.4 and php 8.
But I don't see how to do it. I followed the api_platform tutorial for the conf

my setup:
Security.yml:
```
security:
    password_hashers:
        #Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur: auto
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            stateless: true
            provider: app_user_provider
            jwt: ~
        main:
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: api_authentication
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            #jwt: ~
            # Permet d'ajouter des regles de sécurité d'authentification
            user_checker: App\Security\UserChecker
            # use a custom rate limiter via its service ID
            login_throttling:
                limiter: app.login_rate_limiter

    access_control:
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allows accessing the Swagger UI
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users, roles: IS_AUTHENTICATED_FULLY }
```

lexik_jwt_authentification.yml:
```
lexik_jwt_authentication:
  token_ttl: 3600
  user_identity_field: username
  token_extractors:
    authorization_header:
      enabled: true
      prefix: Bearer
      name: Authorization
    cookie:
      enabled: true
      name: my-token
    query_parameter:
      enabled: true
      name: bearer
  secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'  # required for token verification
  pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
```

I tested to create to intercept the authentication without succeeding. My var_dump is not showing.
in my authController:
```
#[Route('/auth/login', name: 'api_authentication', methods: 'POST')]
    public function login(UserInterface $user)
    {
        var_dump('test');
    }
```
