### ISSUE TITLE
Different token for each firewall

### ISSUE THREAD

**Issue by mathvicot15** [lexik/LexikJWTAuthenticationBundle#1039]
Hello,

Is it possible to use different token on multiple firewall with specific configuration ? 

Exemple :

  ```
  api1:
	    pattern: ^/api1
	    stateless: true
	    secret_key:  "%env(resolve:API1_SECRET)%"
	    public_key:  "%env(resolve:API1_PUBLIC)%"
	    pass_phrase:  "%env(API1_PASS)%"
	    token_ttl:  1440  
	    token_extractors:
	    	authorization_header:
	    		enabled:  true
	    		prefix:  Bearer
	    		name:  Authorization

    api2:
	    pattern: ^/api2
	    stateless: true
	    secret_key:  "%env(resolve:API2_SECRET)%"
	    public_key:  "%env(resolve:API2_PUBLIC)%"
	    pass_phrase:  "%env(API2_PASS)%"
	    token_ttl:  3600
	    token_extractors:
	    	query_parameter:
			enabled:  true
		        name:  token
```

Thanks for your answer !
