### ISSUE TITLE
upgrade 1.0.10 to 1.3.1

### ISSUE THREAD

**Issue by GreGosPhaTos** [lexik/LexikJWTAuthenticationBundle#104]
OK Have an error when I updating my version form 1.0.10 to 1.3.1 : 

Catchable Fatal Error: Argument 3 passed to Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Provider\JWTProvider::__construct() must implement interface Symfony\Component\EventDispatcher\EventDispatcherInterface, none given, called in /Users/adrienpetitjean/sites/www/evapro-symfony/app/cache/dev/appDevDebugProjectContainer.php on line 4056

Don't why the event_dispatcher is not passed to the constructor of the JWTProvider ....
Symfony issue regarding the cache warmup ?

I had my own JWTProvider, but commented the line, and same issue :

```yaml
    firewalls:
        gettoken:
            pattern:  ^/api/getToken
            stateless: true
            anonymous: ~
            gfreeau_get_jwt:
                # this is the default config
                username_parameter: email
                password_parameter: password
                post_only: true
                success_handler: evapro_api.authenticationSuccessHandler
                failure_handler: evapro_api.authenticationFailureHandler

            lexik_jwt:
#                authentication_provider: evapro_api.evapro_jwt_authentication
                throw_exceptions: true

```  

And same that @marrek13 I've updated Symfony base (2.7.3 -> 2.7.5), and other bundles too ...

Just mention that going back to v1.0.10 fix the pb... 

Do you have a idea of what went wrong ?

**Comment by GreGosPhaTos** [comment]
OK same pb with version 1.1.0

**Comment by slashfan** [comment]
Well @marrek13 problem is the upgrade from 1.1.0 to 1.2.0. But I see you are both using the GfreeauGetJWTBundle, wich I haven't used personally. Could you try to disable it ?

**Comment by GreGosPhaTos** [comment]
OK I just found the problem ... My bad I had an other bundle with a custom JWTProvider, added the event_dispatcher param on the both config file like : 
```yaml
services:
     evapro_jwt_authentication:
        class: Evapro\JWTBundle\Services\JWTProvider
        arguments: ['@security.user.provider.concrete.userdb', '@lexik_jwt_authentication.jwt_manager', '@event_dispatcher']

```
