### ISSUE TITLE
Acces not granted even when authed

### ISSUE THREAD

**Issue by Morgiver** [lexik/LexikJWTAuthenticationBundle#105]
Hi, 

I made a little road just to verify if the user is Authenticated Fully and make some test.

The login phase work fully. Getting my token normaly.

```php
/**
     * @Route("/api/checkTokenValidity", name="check_token_validity")
     */
    public function checkTokenValidity() 
    {
        if (!$this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_FULLY')) {
            return new Response('Authenticated');
        } else {
            return new Response('Not Authenticated');
        }
    }
```

First i was getting "Not Authenticated", so i do some research and add two more line in my security.yml : 
```yaml
lexik_jwt:
    #...#
    authentication_provider: lexik_jwt_authentication.security.authentication.provider
    authentication_listener: lexik_jwt_authentication.security.authentication.listener
```

Fixed the bug 'authentication_listener' parameters with this post : 
https://github.com/yelmontaser/LexikJWTAuthenticationBundle/commit/d98d0a200e6cb4962ab4d6cadeed6d2a401fa35a

But, now, i'm getting a 401 response. What can i do more to fix that ?

Thx in advance for help ;)

UPDATE : 
1. If i delete the two line i added before in my security.yml, the response is "Not Authenticated".
2. If i just delete the 'authentication_provider' i got "Not Authenticated" response.
