### ISSUE TITLE
Deprecation : user_identity_field - improve defaults or deprecation message

### ISSUE THREAD

**Issue by EvilSpartans** [lexik/LexikJWTAuthenticationBundle#1051]
Hello, I have updated my project to symfony 6, and now with this config I have a warning error in the console : 

```
lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 604800
  user_identity_field: email
```

**deprecation.INFO: User Deprecated: Since lexik/jwt-authentication-bundle 2.5: The "lexik_jwt_authentication.user_identity_field" configuration key is deprecated since version 2.15, implement "Symfony\Component\Security\Core\User\UserInterface::getUserIdentifier()" instead.**

If I remove this user_identity_field from the config file, when I login to the api and copy paste the token to secure url, I have a 401 error : jwt not found. So I don't know what to do ?

Here is my security file : 

```
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    registration:
      pattern: ^/api/users
      stateless: true
      methods: [POST]

    login:
      pattern: ^/api/login
      # user_checker: App\Security\UserChecker
      stateless: true
      json_login:
        username_path: email
        password_path: password
        check_path: /api/login_check
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      jwt: ~
```

Thanks for your help ! The warning in the console is annoying ...

**Comment by fd6130** [comment]
Just curious about the ` 401 error : jwt not found`.  Double check your request header if it really contains the Bearer Token header?

And are you using Apache web server? Try take a look at this docs: https://symfony.com/bundles/LexikJWTAuthenticationBundle/current/index.html#important-note-for-apache-users

**Comment by EvilSpartans** [comment]
@fd6130 Hello, yes I just take a look : 
![image](https://user-images.githubusercontent.com/50326257/181754843-e144e35c-c3e3-4028-8a42-7f24249621ab.png)
and yes I'm using apache

**Comment by chalasr** [comment]
Does your `User::getUserIdentifier()` method return the `email` property?

**Comment by EvilSpartans** [comment]
@chalasr  yes : 

```    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
```

**Comment by EvilSpartans** [comment]
So I finally found a solution (with help), I share it to help people who have the same problem.

First you must check you have the getUserIdentifier() method in User.php entity : 
```
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
```
then, don't forget to **remove the old getUserName() method** ! It was the problem with me. I use instead getFullName() (just rename getUsername to getFullName). And if you are using this username for front end app, you can add a ```#[SerializedName('username')]``` to don't have to make changes.

And finally, you can remove the user_identifier_field from the lexik config file : 
```
lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 604800
```
