### ISSUE TITLE
Unable to create a signed JWT from the given configuration (lcobucci/jwt 4.2.1 + HS256)

### ISSUE THREAD

**Issue by mpiot** [lexik/LexikJWTAuthenticationBundle#1063]
Just update dependencies and passing from `lcobucci/jwt` version 4.1.5 to 4.2.1 trigger this error:
> Unable to create a signed JWT from the given configuration.

I've find a related issue #532, but this one ask us to add the `pass_phrase: '%env(JWT_PASSPHRASE)%'` in the config file, in my case there is no passphrase at all:

```yaml
lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'
    encoder:
        signature_algorithm: HS256
```
In my case the JWT_SECRET_KEY is something like just a 32 characters long text.

The error is trigger from `Encoder/LcobucciJWTEncoder.php` in this part:

```php
if (!$jws->isSigned()) {
    throw new JWTEncodeFailureException(JWTEncodeFailureException::UNSIGNED_TOKEN, 'Unable to create a signed JWT from the given configuration.', null, $payload);
}
```
