### ISSUE TITLE
Creating JWT tokens programmatically

### ISSUE THREAD

**Issue by bencagri** [lexik/LexikJWTAuthenticationBundle#1082]
Hello all, 
I just updated symfony from 5.3 to 5.4.x and now having some isssue with Decoding Token.

Im creating JWT manually as [described here](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/v2.16.0/Resources/doc/7-manual-token-creation.rst) based on our flow, it generates but cant now it throws `JWTDecodeFailureException` 

```
{
    "code": 401,
    "message": "Invalid JWT Token"
}
```

```bash
bin/console lexik:jwt:check-config
The configuration seems correct.
```

security.yaml;
```
 api:
            pattern: ^/(v1)(?!/sms)
            stateless: true
            jwt:
                provider: app_user_provider  #(you can put provider here or just ignore this config)
                authenticator: lexik_jwt_authentication.security.jwt_authenticator #(default jwt authenticator)
```

I tried to regenerate private.pem and public.pem, but didnt work. 

Server; Nginx.
PHP 8.1

update:
```bash
bin/console lexik:jwt:generate-token "username"
```

generated token... 

```
eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NjczMjE4OTEsInJvbGVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfTUVSQ0hBTlQiXSwiZnVsbFBob25lTnVtYmVyIjoiOTA1NDEzODA2MDA2In0.fRr4u2zffLm-pU1RExuBIMLz8pNe-DW09Uujm1I2AhDyklmaNd7I7458FJi4a-Yqi3wDEqHEljuV3AgiFKqMvtp8TW7HKXC9zmy5X--4-cht8QjnGCQnuuC52dDfzXjKFCU2OxshDcLm....
```

And its verified on jwt.io

<img width="1053" alt="Screenshot 2022-11-01 at 19 00 52" src="https://user-images.githubusercontent.com/823521/199292428-3ecf38b5-72b8-4c51-9380-a863f3b3eae6.png">
