### ISSUE TITLE
Symfony 6 tutorial doesn't work

### ISSUE THREAD

**Issue by agatumm420** [lexik/LexikJWTAuthenticationBundle#1090]
I've followed the instructions of the configuration page and I get this error:
`Unable to find the controller for path "/api/login_check". The route is wrongly configured. in /home/aga/zadanie-rek-symf2/vendor/symfony/http-kernel/HttpKernel.php:147`
security.yaml
```
security:
    enable_authenticator_manager: true    
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'    
    providers:

        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:

        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: email
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~



        main:
            lazy: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }



```
routes.yaml
```
controllers:
    resource: ../src/Controller/
    type: attribute
api_login_check:
    path: /api/login_check
```
I will be grateful for any help :)
