### ISSUE TITLE
oAuth2 (JWT) Secured request too slow

### ISSUE THREAD

**Issue by smehdux** [lexik/LexikJWTAuthenticationBundle#1162]
Hi,

I'm using LexikJWTAuthenticationBundle  in order to secure an API, maybe I'm not using it well but my problem is, when I call unsecured URL it takes almost less than 150ms in DEV environment, but if the URL is secured, it takes about 20sec to respond.

I'm using an identity provider (IDP) which is responsible for issuing JWT tokens, the JWKeySet is requested from this IDP remotely.

The caller include the JWT Token in the header (Bearer), but this works fine, the problem is the latency.
I've tried to create a custom Authenticator inheriting from the JWTAuthenticator class but it hasn't changed anything in term of latency.

Postgresql performances are OK because I could see that int Doctrine's logs.
 
If I try with basic-auths strategy , everything work and the protected endpoint take almost 1 sec only !

Anyone has an idea or facing the same issue ?

To reproduce: 

**//Controller:**
```
#[Route('/api/v1', name:'lucky_')]
class LuckyController extends AbstractController {
    
    #[Route('/lucky/number', name:'number')]
    public function number(UserInterface $user): Response
    {
        try {
            $number = random_int(0, 100);
    
            return new Response(
                '<html><body><h1>Hey ' . $user->getFirstName() . ' '. $user->getLastName() . ', your Lucky number is: '.$number.'</h1></body></html>'
            );

        }
        catch(BadCredentialsException){
            return $this->json(['error' => $e->getMessage()], 401);
        }
        catch(Exception){
            return $this->json(['error' => $e->getMessage()], 500);
        }
    }
}
```

**//User Entity**
```
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;
    
    #[ORM\Column]
    private array $roles = [];
    
    #[ORM\Column(length: 255)]
    private ?string $firstName = null;
    
    #[ORM\Column(length: 255)]
    private ?string $lastName = null;
    
    #[ORM\Column(length: 180, unique: true)]
    private ?string $upn = null;
	
	//getter/setters/
}
```

**//UserRepository.php:**
```
class UserRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
    }

//CRUD operations	
}
```

**//spomky_labs_lexik_jose_bridge_bundle.yaml:**
```
lexik_jose:
    ttl: 3600
    key_index: 0
    server_name: '%env(OAUTH2_SERVER_NAME)%' #value of the 'iss' attribute of your JWT token
    audience: '%env(OAUTH2_AUDIENCE)%'
    key_set_remote:
        type: 'jku'
        url: '%env(OAUTH2_KEY_SET_URL)%'
    signature_algorithm: "RS256"
    mandatory_claims: ["upn","aud","iss","iat","exp"]
    # claim_checked: 
    #     - my_claims_checker #must be implemented as service with alias 'my_claims_checker', See https://web-token.spomky-labs.com/the-components/claim-checker for more information

jose:
    jku_factory:
        enabled: true
        client: 'httplug.client.acme' # The Httplug client
        request_factory: 'Psr\Http\Message\RequestFactoryInterface'
        # request_factory: 'httplug.message_factory' # In general, you will use the same message factory as the one used by Httplug
    
    jws:
        verifiers:
            jws_verifier:
                signature_algorithms: ['RS256', 'ES256']
                is_public: true
```

**//security.yaml**
```
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_VIEWER, ROLE_APPROVER]
        ROLE_APPROVER: [ROLE_USER, ROLE_VIEWER]
        ROLE_VIEWER: [ROLE_USER]
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: 'email'


        jwt_provider:
            lexik_jwt: ~


    enable_authenticator_manager: true

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern:   ^/api/(v|V)[0-9]+
            stateless: true
            jwt:
                provider: app_user_provider
            #jwt ~
        main:
            lazy: true
            stateless: true
    access_control:
        - { path: ^/api/(v|V)[0-9]+, roles: [ROLE_USER] }
```

**//lexik_jwt_authentication.yaml:**
```
lexik_jwt_authentication:
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    # secret_key: '%env(resolve:JWT_SECRET_KEY)%' //not used as IDP issues tokens
    # pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: 'email'
```
	
	
**//httplug.yaml:**
```
httplug: # Example of client configuration
    plugins:
        cache: # We use the cache plugin
            cache_pool: 'cache.app' # We use the PSR-6 Cache service of the application
            config:
                default_ttl: 1800 # TTL set to 30 min
        logger: ~
    clients:
        acme:
            factory: 'httplug.factory.guzzle6'
            plugins: ['httplug.plugin.cache', 'httplug.plugin.logger'] # We enable the cache and logger plugin for that client.
			
```
**some details about Bundles:**
```
"php": ">=8.1",
"symfony/XXXXX": "6.3.*",
"ext-ctype": "*",
"ext-iconv": "*",
"doctrine/doctrine-bundle": "^2.10",
"doctrine/doctrine-fixtures-bundle": "^3.4",
"doctrine/doctrine-migrations-bundle": "^3.2",
"doctrine/orm": "^2.15",
"nyholm/psr7": "*",
"php-http/cache-plugin": "*",
"php-http/curl-client": "*",
"php-http/guzzle6-adapter": "^2.0",
"php-http/httplug-bundle": "*",
"spomky-labs/lexik-jose-bridge": ">=3.0.2",
"web-token/jwt-bundle": "^3.2",
"web-token/jwt-checker": "^3.2",
"web-token/jwt-key-mgmt": "^3.2",
"web-token/jwt-signature": "^3.2",
"web-token/jwt-signature-algorithm-ecdsa": "^3.2",
"web-token/jwt-signature-algorithm-rsa": "*"
```

//some logs: as we see, there is a latency between the reponse that retrieve the JWKeySet from de IDF (https://idp-url/adfs/discovery/keys) and the request to postgresql, about 20 seconds (2023-10-09T15:05:27 -> 2023-10-09T15:05:47)
```

[2023-10-09T15:05:27.417026+02:00] request.INFO: Matched route "lucky_number". {"route":"lucky_number","route_parameters":{"_route":"lucky_number","_controller":"App\\Controller\\LuckyController::number"},"request_uri":"http://localhost/api/v1/lucky/number","method":"GET"} []

[2023-10-09T15:05:27.432128+02:00] httplug.INFO: Sending request: GET https://idp-url/adfs/discovery/keys 1.1 {"request":{"Nyholm\\Psr7\\Request":[]},"uid":"6523fa97697ef2.65955958"} []

[2023-10-09T15:05:27.721686+02:00] httplug.INFO: Received response: 200 OK 1.1 {"milliseconds":290,"uid":"6523fa97697ef2.65955958"} []

[2023-10-09T15:05:47.873218+02:00] doctrine.INFO: Connecting with parameters array{"dbname":"postgres","host":"db","port":5432,"password":"<redacted>","driver":"pdo_pgsql","user":"root","driverOptions":[],"defaultTableOptions":[],"serverVersion":"15","charset":"utf8"} {"params":{"dbname":"postgres","host":"db","port":5432,"password":"<redacted>","driver":"pdo_pgsql","user":"root","driverOptions":[],"defaultTableOptions":[],"serverVersion":"15","charset":"utf8"}} []

[2023-10-09T15:05:47.889962+02:00] security.INFO: Authenticator successful! {"token":{"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Authenticator\\Token\\JWTPostAuthenticationToken":"JWTPostAuthenticationToken(user=\"mehdi.souilah@regis-dgac.net\", roles=\"ROLE_USER, ROLE_ADMIN, ROLE_APPROVER\")"},"authenticator":"Lexik\\Bundle\\JWTAuthenticationBundle\\Security\\Authenticator\\JWTAuthenticator"} []

[2023-10-09T15:05:47.994012+02:00] doctrine.INFO: Disconnecting [] []
```
Thanks in advance.

Mehdi
