### ISSUE TITLE
Split cookie renewal not working as expected when calling api endpoints

### ISSUE THREAD

**Issue by leonwisdom** [lexik/LexikJWTAuthenticationBundle#1163]
I have another Vue 3 project using both this bundle and JWTRefreshTokenBundle and all work as expected.

This time I'm trying to implement the split cookie option in the bundle with another Vue 3 project. It all works as expected until the jwt_hp cookie expires, leaving just the jwt_s an refresh_token cookies. 

When the jwt_hp cookie expires, the next request to the api results in: "401 Unauthorized - JWT Token not found". I then fire off a api request to the refresh token endpoint. This again results in the following response: "401 Unauthorized - JWT Token not found". Both refresh_token and the jwt_s cookies are being sent in the headers.

I would have thought the flow to work like this:
> Jwt_hp cookie expires
> Next request to the serves 401 unauthorized
> Send api request to the refresh token endpoint with the refresh_token and the jwt_s cookies
> Validates both cookies
> Gives back a new set of jwt_hp and jwt_s cookies, as well as the refresh_token cookie

Am i correct that the "JWT Token not found" response is because the jwt_hp no longer exists which makes the whole jwt cookie no longer valid.

If so, does anyone have any suggestions on this and how they went about implementing it?

I set the jwt_hp cookie lifetime really short for testing purposes. Here is the config i am using:
```
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: uuid
    token_extractors:
        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s

    set_cookies:
        jwt_hp:
            lifetime: 30
            samesite: strict
            path: /
            domain: null
            httpOnly: false
            split:
                - header
                - payload

        jwt_s:
            lifetime: 0
            samesite: strict
            path: /
            domain: null
            httpOnly: true
            split:
                - signature
```

```
gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: '%env(int:JWT_REFRESH_TTL)%'
    single_use: true
    ttl_update: true
    firewall: api
    logout_firewall: api
  
    cookie:
      enabled: true
      same_site: lax
      path: /   
      domain: null
      http_only: true
      secure: true
      remove_token_from_body: true
```
