### ISSUE TITLE
Support for partitioned authentication cookies

### ISSUE THREAD

**Issue by EmilePerron** [lexik/LexikJWTAuthenticationBundle#1166]
Hey folks!

With the upcoming [phasing-out of third-party cookies by Chromium](https://developer.chrome.com/docs/privacy-sandbox/third-party-cookie-phase-out/) (and, I expect, other browser vendors in the near future), I think it would be useful to add support for Partitioned authentication cookies in this library.

Some applications embed widgets (or even their entire application!) on other sites in a legitimate way. In these cases, their authentication cookies are usually set with `SameSite=None`, and considered as third-party cookies by browsers. The upcoming phase-out will therefore break any such application... unless they switch to partitioned cookies (see Google's docs on [CHIPS](https://developer.chrome.com/docs/privacy-sandbox/chips/) - _Cookies Having Independent Partitioned State_).

[Symfony has added support for Partitioned Cookies in version 6.4](https://symfony.com/blog/new-in-symfony-6-4-chips-cookies) (which will be released by the end of the month). This means that this library could fairly easily be updated to also allow this option, by simply adding an additional configuration option, which defaults to the current behavior (not partitioned).

Here is what an example configuration for an application in this context could look like, once this is implemented:

```yaml
    set_cookies:
        jwt_hp:
            lifetime: null
            samesite: none
            path: /
            domain: null
            httpOnly: false
            partitioned: true       # <--- new option
            split:
                - header
                - payload

        jwt_s:
            lifetime: 0
            samesite: none
            path: /
            domain: null
            httpOnly: true
            partitioned: true       # <--- new option
            split:
                - signature
```

If the maintainers do not have any objections, I could get to work on a PR for this, as we do have a need for this in a project that I am currently working on (in order to give us a bit of peace of mind regarding the upcoming phase out 😅). 

Let me know if you have any questions, objections or feedback! Cheers!
