### ISSUE TITLE
token no longer being created

### ISSUE THREAD

**Issue by ctf0** [lexik/LexikJWTAuthenticationBundle#1215]
- security
```yaml
security:
    providers:
        users:
            entity:
                class: App\Modules\User\Persistence\Entity\User
                property: userName

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: api_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            jwt: ~
            refresh_jwt:
                check_path: api_refresh_token # or, you may use the `api_refresh_token` route name
                provider: users
            logout:
                path: api_logout

        api_token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt: ~

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/(login|token/refresh|doc), roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

```

- lexik_jwt_authentication
```yaml
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(JWT_TOKEN_TTL)%' # in seconds, default is 3600
```

- entity
```php
class User implements UserInterface, \Stringable
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\Column(name: 'user_name', length: 255, unique: true)]
    private ?string $userName = null;

    // ...
```

- `api/login`
```php
$user = $this->userRepository->findOneBy([
    'email' => 'some_email',
]);

return $this->authenticationSuccessHandler->handleAuthenticationSuccess($user);
```

- response
```json
{
    "token": "",
    "refresh_token": "c2cab67247510e8430028cf22043c274a34b84035cd2701954784d1fec3b6cf3d36f7f614e1c9ae4e327f27cc30eec47950a9910aa7eafddfcf7c4b0fe95864d"
}
```

- routes
```yaml
api_login:
    path: /api/login

api_logout:
    path: /api/logout

api_refresh_token:
    path: /api/token/refresh
```

am not sure if i missed something out, but for some reason the token no longer being created, any help is appreciated, thanks.
