### ISSUE TITLE
Cannot customise cookies with `set_cookies` option

### ISSUE THREAD

**Issue by silverbackdan** [lexik/LexikJWTAuthenticationBundle#1217]
Using this config:
```
lexik_jwt_authentication:
  token_ttl: 7776000 # 90 days
  secret_key: '%env(resolve:JWT_SECRET_KEY)%'
  public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
  pass_phrase: '%env(JWT_PASSPHRASE)%'
  token_extractors:
    cookie:
      enabled: true
      name:    BEARER
  set_cookies:
    BEARER: ~
```

Which is the documented way to implement `set_cookies` as shown here: https://symfony.com/bundles/LexikJWTAuthenticationBundle/current/1-configuration-reference.html#automatically-generating-cookies

Results in the error:
```
Service "lexik_jwt_authentication.cookie_provider.BEARER": The index "2" is not in the range [0, 1] of the arguments of class "Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookie  
  Provider".  
```

The issue seems to originate here: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/3.x/DependencyInjection/LexikJWTAuthenticationExtension.php#L100-L110

The code appears to try and replace arguments that for some reason is cannot - perhaps the arguments haven't already been set by this point to replace?

The class itself has a constructor with enough arguments in my vendor dir
```
public function __construct(?string $defaultName = null, ?int $defaultLifetime = 0, ?string $defaultSameSite = Cookie::SAMESITE_LAX, ?string $defaultPath = '/', ?string $defaultDomain = null, bool $defaultSecure = true, bool $defaultHttpOnly = true, array $defaultSplit = [], bool $defaultPartitioned = false)
    {
...
```

By using `addArgument` in my case, the issue disappears so the fix would be this.
```
$container
                    ->setDefinition($id = "lexik_jwt_authentication.cookie_provider.$name", new ChildDefinition('lexik_jwt_authentication.cookie_provider'))
                    ->replaceArgument(0, $name)
                    ->replaceArgument(1, $attributes['lifetime'] ?? ($config['token_ttl'] ?: 0))
                    ->addArgument(2, $attributes['samesite'])
                    ->addArgument(3, $attributes['path'])
                    ->addArgument(4, $attributes['domain'])
                    ->addArgument(5, $attributes['secure'])
                    ->addArgument(6, $attributes['httpOnly'])
                    ->addArgument(7, $attributes['split'])
                    ->addArgument(8, $attributes['partitioned']);
```

However without looking into this further and without sufficient background of why it had been working before, I'm not confident in presenting this as a PR.

Could anyone shed light on this issue and is there another config option that I'm missing? I'm thinking to perhaps override the defaults of the primary cookie provider instead.

My main issue was actually that my ttl config for my jwt token was not being used to set the lifetime of the cookie so I was looking to manually set this, and stumbled across this issue.

**Comment by silverbackdan** [comment]
Apologies - I found that I have a services config like this:
```
lexik_jwt_authentication.cookie_provider:
    class: 'Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Cookie\JWTCookieProvider'
    arguments:
        - 'BEARER'
        - 3600
```

Removing this resolved the issue.
