### ISSUE TITLE
bug: `Extending Authenticator` does not work when using a dedicated services file and FQCN instead of id

### ISSUE THREAD

**Issue by Crovitche-1623** [lexik/LexikJWTAuthenticationBundle#1274]
If I have the following service definition:

```yml
# config/services.yml
services:
    App\Security\CustomJwtAuthenticator:
        parent: lexik_jwt_authentication.security.jwt_authenticator
        arguments:
            # aditional arguments here...
```

And I want to move it in a dedicated service file (e.g. `lexik_jwt_authentication.yml`):

```yml
# config/services.yml
imports:
    - { resource: services/ }
```

```yml
# config/lexik_jwt_authentication.yml
services:
    App\Security\CustomJwtAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator
```

it does not work anymore and it requires a dedicated id to make it work :

e.g. 
```yml
# config/lexik_jwt_authentication.yml
services:
      app_jwt_authentication.security.custom_jwt_authenticator:
        class: App\Security\CustomJwtAuthenticator
        parent: lexik_jwt_authentication.security.jwt_authenticator
```
```yml
# config/packages/security
security:
    firewalls:
        main:
            jwt:
                authenticator: app_jwt_authentication.security.custom_jwt_authenticator # instead of App\Security\CustomJwtAuthenticator
```

Otherwise we end up with error like:

```
In Definition.php line 255:
                                                                                                                                                         
  [Symfony\Component\DependencyInjection\Exception\OutOfBoundsException]                                                                                 
  Service "security.authenticator.jwt.main": Cannot replace arguments for class "App\Security\CustomJwtAuthenticator" if none have been configured yet.  
           
```

It seems that the security configuration does not wait the services to be fully loaded when we use multiple services definition files. I know the documentation use an example like the solution I found but I think it's worth to say somewhere that using the FQCN instead of a dedicated id will not work in some cases.
