### ISSUE TITLE
JWTCreatedEvent Request is null

### ISSUE THREAD

**Issue by blt909** [lexik/LexikJWTAuthenticationBundle#128]
Hi,

Since we've upgraded to 1.4.2, our listener onJWTCreated isn't working anymore.
It seems that $event->getRequest() is always null.
Our app is running on Symfony 2.8.2.

Here's our service definition : 
```yaml
# JWT Creation Listener
    pm.event.jwt_created_listener:
        class: AppBundle\EventListener\JWTCreatedListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
```

And the method handling the event : 
```php
public function onJWTCreated(JWTCreatedEvent $event)
    {
        $request = $event->getRequest();
        if (!$request) {
            return;
        }

        $user = $this->token_storage->getToken()->getUser();

        $payload       = $event->getData();
        $payload['pseudo']= $user->getPseudo();        

        $event->setData($payload);
    }
```

Am I missing somethig?

Thanks
