### ISSUE TITLE
401 when bearer is set but not valid on anonymous route

### ISSUE THREAD

**Issue by kevin-sennoun-needone** [lexik/LexikJWTAuthenticationBundle#139]
Hi,

I'm using this bundle with FosUserBundle.

I have this in security.yml :

```
firewalls:
    app:
            pattern: ^/api
            stateless: true
            anonymous: true
            lexik_jwt: ~
```

with the following access_control : 

```
- { path: ^/api/user/action1, roles: IS_AUTHENTICATED_FULLY }
- { path: ^/api/user/action2, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

The behaviour I was expecting for /api/user/action2 is having access no matter what is inside the request header. However I'm getting a 401 in the case where the Authorization Bearer is set but not valid (it is ok with valid token or no Authorization Bearer at all).

My use case is I need to check in my controller if the user is logged in but if not, I still want to let that anonymous user access the route.

Is this behaviour normal ?
