### ISSUE TITLE
ALGORYTHM HS256 generated token not valid

### ISSUE THREAD

**Issue by rbaraut** [lexik/LexikJWTAuthenticationBundle#144]
As you explain in https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/5-encoder-service.md I'm, trying to override JWTEncoder Class because I need to replace the algorythm to HS256 ( I think that is the only way to change the algorithm)

When I put the token generated into https://jwt.io/ webpage, it says that signature is invalid , and if i try to decode the a request with this token i alse get and invalid signature validation

I override the JWTEncoder and change the algoryth to hs256 as exaplin this code

```

<?php

namespace Custom\ApiBundle\Helper;

use InvalidArgumentException;
use Lexik\Bundle\JWTAuthenticationBundle\Encoder\JWTEncoderInterface;
use Namshi\JOSE\SimpleJWS;

/**
 * JWTEncoder
 *
 * @author Dev Lexik <dev@lexik.fr>
 */
class CustomJWTEncoder implements JWTEncoderInterface
{
    const ALGORYTHM = 'HS256';

    /**
     * @var string
     */
    protected $privateKey;

    /**
     * @var string
     */
    protected $publicKey;

    /**
     * @var string
     */
    protected $passPhrase;

    /**
     * @param string $privateKey
     * @param string $publicKey
     * @param string $passPhrase
     */
    public function __construct($privateKey, $publicKey, $passPhrase)
    {
        $this->privateKey = $privateKey;
        $this->publicKey  = $publicKey;
        $this->passPhrase = $passPhrase;
    }

    /**
     * {@inheritdoc}
     */
    public function encode(array $data)
    {
        $jws = new SimpleJWS(['alg' => self::ALGORYTHM]);
        $jws->setPayload($data);
        $jws->sign($this->getPrivateKey());

        return $jws->getTokenString();
    }

    /**
     * {@inheritdoc}
     */
    public function decode($token)
    {
        try {
            /** @var SimpleJWS $jws */
            $jws = SimpleJWS::load($token);
        } catch (InvalidArgumentException $e) {
            return false;
        }

        if (!$jws->isValid($this->getPublicKey(), self::ALGORYTHM)) {
            return false;
        }

        return $jws->getPayload();
    }

    /**
     * @return bool|resource
     */
    protected function getPrivateKey()
    {
        return openssl_pkey_get_private('file://' . $this->privateKey, $this->passPhrase);
    }

    /**
     * @return resource
     */
    protected function getPublicKey()
    {
        return openssl_pkey_get_public('file://' . $this->publicKey);
    }
}

```

And in services.yml
```

parameters:
    customlexik_jwt_authentication.jwt_encoder.class: Diba\ApiBundle\Helper\CustomJWTEncoder

services:
    customlexik_jwt_authentication.jwt_encoder:
        class: %customlexik_jwt_authentication.jwt_encoder.class%
        arguments: ["%lexik_jwt_authentication.private_key_path%","%lexik_jwt_authentication.public_key_path%","%lexik_jwt_authentication.pass_phrase%"]
```
