### ISSUE TITLE
Problem with authentication_manager

### ISSUE THREAD

**Issue by pemumor** [lexik/LexikJWTAuthenticationBundle#165]
Hi,

I've a problem with authentication_manager in services.yml.

I change the arguments of authentication_manager
```
authentication_manager:
        class: %authentication_manager.class%
        arguments: 
            - '%lexik_jwt_authentication.pass_phrase%'
            - '%lexik_jwt_authentication.private_key_path%'
            - '%lexik_jwt_authentication.public_key_path%'
            - @doctrine.orm.entity_manager
            - @translator
```
for these
```
    authentication_manager:
        class: %authentication_manager.class%
        arguments: 
            - '%lexik_jwt_authentication.openssl_key_loader%'
            - @doctrine.orm.entity_manager
            - @translator
```

and when I run the server I recive this problem:

```
 [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
 The service "authentication_manager" has a dependency on a non-existent parameter "lexik_jwt_authentication.openssl_key_loader". Did you mean one of these: "lexik_jwt_authentication.openssl_key_l
 oader.class", "lexik_jwt_authentication.private_key_path", "lexik_jwt_authentication.public_key_path", "lexik_jwt_authentication.pass_phrase", "lexik_jwt_authentication.token_ttl"?
```

Any of you can help me with this issue?

Thanks!
