### ISSUE TITLE
Bad credentials always api/v1/login_check

### ISSUE THREAD

**Issue by iarenasbeyond** [lexik/LexikJWTAuthenticationBundle#183]
Good afternoon. I have an application with symfony 3 and what is the mobile application with AngularJS + Ionic. I installed the bundle authentication token for JWT loguerarme with users of the database but api/v1/login_check always gives me the 401- error> Bad credentials, being correct because the backend access those credentials.

My routing.yml

```
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api_login_check:
    path: /api/v1/login_check
```
My security.yml

```
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: AppBundle:User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/v1/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/v1/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix: Bearer

        default:
            pattern: ^/
            anonymous: true
            form_login:
                check_path: security_login_check
                login_path: security_login_form
            logout:
                path: security_logout
                target: homepage

    access_control:
        - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }

```
