### ISSUE TITLE
401 Bad credentials

### ISSUE THREAD

**Issue by MarioPatch** [lexik/LexikJWTAuthenticationBundle#209]
Hello, I'm just trying to retrieve the token but I still have the same result.

curl request :
```
curl -X POST https://mylocalhost.com/api/login_check -d _username=johndoe -d _password=test --insecure
```

response :
```
{"code":401,"message":"Bad credentials"}
```
my symfony version : 2.5.10 - ezpublish/dev/debug
lexik/jwt-authentication-bundle version : 1.6.0

security.yml :

```
firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
          pattern:   ^/api
          stateless: true
          lexik_jwt: ~
```

routing.yml : 

```
api_login_check:
    path: /api/login_check
```

exactly the same config for parameters.yml and I add the jwt_key_pass_phrase used when i generate my private/public keys and i have added the apache config + restart apache
any idea ?

**Comment by yoannfleurydev** [comment]
Do you have a user provider configured in your `security.yml` ? 
With your actual configuration, just try to add these lines to your `security.yml` :

```yml
encoders:
  Symfony\Component\Security\Core\User\User: plaintext

providers:
  in_memory:
    memory:
      users:
        johndoe:
          password: test
```

Hope it solves your issue.

**Comment by MarioPatch** [comment]
thx, okay so i add this 
```
encoders:
  Symfony\Component\Security\Core\User\User: plaintext
providers:
    in_memory:
        memory:
            users:
                johndoe:
                    password: test
                    roles: 'IS_AUTHENTICATED_FULLY'
[...]
            form_login:
                [...]
                provider: in_memory
```
but no success. I still have 401 bad credentials
