### ISSUE TITLE
Use Lexik JWT for OTP

### ISSUE THREAD

**Issue by RonRademaker** [lexik/LexikJWTAuthenticationBundle#242]
Hi,

I want to allow both token based and username / password based authentication on the same firewall. So I tried just adding the lexik_jwt config to my existing firewall like:

``` yml
 main:
            pattern: ^/
            form_login:
                provider: chain_provider
                check_path: fos_user_security_check
                success_handler: authentication_success_handler
                failure_handler: authentication_failure_handler

            lexik_jwt:
                query_parameter:      # check token in query string parameter
                    enabled: true
                    name:    bearer

            logout:       true
            anonymous:    true
```

I use the token as an OTP, which works with this setup but any following requests fail (probably due to the missing token in the query). 

How can I fix this?
