### ISSUE TITLE
Bad credentials with LexikJWTAuthenticationBundle and fosuserbundle  

### ISSUE THREAD

**Issue by iometrine** [lexik/LexikJWTAuthenticationBundle#255]
Hi,

I use symfony 3 with fosuserbundle, hwioauthbundle. All works fine for the web site.
Now i need to expose some services from mobile app.
So i begin by the login request  I want to use LexikJWTAuthenticationBundle to get a JWT with this request http:
http://127.0.0.1:8000/api/login_check?_username=john_user&_password=kitten

My problem is i received always a {"code":401,"message":"Bad credentials"}

Please find my config files below :

```yaml
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: api #secured_area
    user_class: AppBundle\Entity\User
    registration:
        form:
            type: AppBundle\Form\RegistrationType

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%


Routing file:
api_login_check:
    path: /api/login_check

and my security file:

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:          
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            provider:  fos_userbundle
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        secured_area:
            pattern: ^/

            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

                login_path:             fos_user_security_login 
                check_path:             fos_user_security_check

                # The route name that the login form submits to
                #check_path: security_login
                # The name of the route where the login form lives
                # When the user tries to access a protected page, they are redirected here
                #login_path: security_login
                # Secure the login form against CSRF
                # Reference: http://symfony.com/doc/current/cookbook/security/csrf_in_login_form.html

            logout:
                # The route name the user can go to in order to logout
                path: fos_user_security_logout
                # The name of the route to redirect to after logging out
                target: homepage

            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    
                login_path:        fos_user_security_login
                use_forward:       false
                failure_path:      fos_user_security_login

                oauth_user_provider:
                    service: my.custom.user_provider

    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - { path: '^/(%app_locales%)/login$', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(%app_locales%)/register', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(%app_locales%)/resetting', role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(%app_locales%)/admin/', role: ROLE_ADMIN }
        - { path: '^/(%app_locales%)/user', roles: ROLE_USER }

        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

Can you help me ?
