### ISSUE TITLE
'openssl_pkey_get_private' not found or invalid function name

### ISSUE THREAD

**Issue by domattieu** [lexik/LexikJWTAuthenticationBundle#264]
Hi everybody,

It's my first time using LexikJWTAuthentication and I try to mix it with FosUserBundle. I followed perfectly your documentation but I got an error when I try to POST on /login_check.

Here the error : 
`Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'openssl_pkey_get_private' not found or invalid function name in vendor\lexik\jwt-authentication-bundle\Services\KeyLoader\OpenSSLKeyLoader.php at line 25`

The user is correctly logged by the way : 
`[2016-11-03 15:16:04] security.INFO: User has been authenticated successfully.`

You can find my config below:

config.yml
```
fos_user:
    db_driver: orm
    firewall_name: api
    user_class: ApiBundle\Entity\User

fos_rest:
    routing_loader:
        default_format: json

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    namespace: migrations
    table_name: migration_versions
    name: Application Migrations

lexik_jwt_authentication:
    private_key_path: "%kernel.root_dir%/../var/jwt/private.pem"
    public_key_path:  "%kernel.root_dir%/../var/jwt/public.pem"
    pass_phrase:      ''
    token_ttl:        86400

nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
```

security.yml
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        login:
            pattern:        ^/api/login
            anonymous:      true
            stateless:      true
            form_login:
                check_path:               /api/login_check
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:        ^/api
            anonymous:      false
            stateless:      true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```

routing.yml
```
api:
    prefix:     /api
    resource:   "@ApiBundle/Resources/config/routing.yml"
api_login_check:
    path:       /api/login_check
```

I tried many different configurations and I still got this error... any advices ? 

Thanks !
