### ISSUE TITLE
HWIOAuthBundle + FOSUserBundle

### ISSUE THREAD

**Issue by jokari4242** [lexik/LexikJWTAuthenticationBundle#272]
Hi, 

I'm try to configurate this bundle, but i have this error when i'm running this command: 

curl -X POST http://localhost:8000/api/login_check -d username=user -d password=password 

```
No encoder has been configured for account \"HWI\\Bundle\\OAuthBundle\\Security\\Core\\User\\OAuthUser\
```

Here my configuration
### security.yml
```
security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER, ROLE_MODERATOR, ROLE_API, ROLE_ALLOWED_TO_SWITCH ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]

    providers:
        hwi:
            id: hwi_oauth.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    user:  { password: password, roles: [ 'ROLE_USER' ] }
                    admin: { password: password, roles: [ 'ROLE_ADMIN' ] }
    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

        main:
            pattern: ^/
            oauth:
                resource_owners:
                    facebook:      /login-facebook
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: am_user.oauth_user_provider
                always_use_default_target_path : true
                default_target_path: am_profile_private_get
                use_referer : true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path : true
                default_target_path: am_profile_private_get
                use_referer : true
            logout:
                  path: fos_user_security_logout
                  target: am_app_default_index
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            anonymous:    true
            switch_user: true


    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/my_profile, role: IS_AUTHENTICATED_REMEMBERED }
```

Any idea?

Thanks :-)
