### ISSUE TITLE
FOSUserBunder + LexikJWT token storage return null user

### ISSUE THREAD

**Issue by Yanaro** [lexik/LexikJWTAuthenticationBundle#292]
Hello, after finally making FOS and Lexik to work together. I face another problem in which $this->get('security.token_storage')->getToken()->getUser() returns null.
I use postman chrome extension to send get request with Authorization header - Bearer [token]
getToken returns an object that contains only token, everything else is null.
onJWTAuthenticated event works (probably as expected) as its event contains both token and correct payload. I tried to debug and found out that everything works until 
`$token = new JWTUserToken();
            $token->setRawToken($requestToken);
            $authToken = $this->authenticationManager->authenticate($token);
            $this->tokenStorage->setToken($authToken);`
(code snippet from line 92 in JWTListener in Security firewall) in which the authToken is empty.
My config: 
- Security : 
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        # Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path:               api_login_check
                username_parameter:       _username
                password_parameter:       _password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:      
                    enabled: false
                    name:    bearer
                throw_exceptions:        true
                create_entry_point:      false
                authentication_provider: lexik_jwt_authentication.security.authentication.provider
        main:
            pattern: ^/user
            form_login:
                login_path: /user/login
                check_path: /user/login_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
    access_control:
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user , role: ROLE_USER }
        - { path: ^/api , role: IS_AUTHENTICATED_ANONYMOUSLY }
```
- Config : 
```
lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%
    user_identity_field: username
    token_extractors:
        authorization_header:   
            enabled: true
            prefix:  Bearer
            name:    Authorization
        cookie:        
            enabled: true
            name:    BEARER
        query_parameter:           
            enabled: false
            name:    bearer
    encoder:
        service:            lexik_jwt_authentication.encoder.default
        crypto_engine:  openssl
        signature_algorithm: RS256
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: mhl\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
            from_email:
                address:        webmaster@example.com
                sender_name:    webmaster
            template:   FOSUserBundle:Registration:email.txt.twig
    resetting:
        token_ttl: 86400
        email:
            from_email:
                address:        ...
                sender_name:    ...
            template:   FOSUserBundle:Resetting:email.txt.twig
        form:
            type:               FOS\UserBundle\Form\Type\ResettingFormType
            name:               fos_user_resetting_form
    service:
        mailer:             fos_user.mailer.noop
```

**Comment by chalasr** [comment]
Hi @Yanaro,

You're mixing the old and new way to use this bundle, please consider changing from:

```yaml
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:      
                    enabled: false
                    name:    bearer
                throw_exceptions:        true
                create_entry_point:      false
                authentication_provider: lexik_jwt_authentication.security.authentication.provider
```

to:

```yaml
        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

See the corresponding UPGRADE note: https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/UPGRADE.md#configuration

Let me know if the issue persists after that
