### ISSUE TITLE
Check user token on unprotected route?

### ISSUE THREAD

**Issue by Yanaro** [lexik/LexikJWTAuthenticationBundle#301]
Is there anyway to check for user on unprotected route in case they provide the token? The idea is that I want to get user login status everywhere on the site without getting JWT expired / invalid if the requested route is not protected.

**Comment by chalasr** [comment]
Hello,

There are different ways to achieve this, the simplest being to configure the jwt listener (guard authenticator) on the unprotected firewall, beside the `anonymous` listener, e.g:

```yaml
security:
    # ...
    firewalls:
        secure:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        unsecure:
            pattern: ^/unsecure
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
            # You may have the form login on this one
            #form_login:
            #    check_path: /login
            #    require_previous_session: false
            #    success_handler: lexik_jwt_authentication.handler.authentication_success
            #    failure_handler: lexik_jwt_authentication.handler.authentication_failure

    access_control:
        - { path: ^/unsecure, roles: [IS_AUTHENTICATED_ANONYMOUSLY, IS_AUTHENTICATED_FULLY] }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```

If a valid token is passed, you'll be able to retrieve the user from the controller of your unprotected route  through `$this->getUser()`, if no token was passed, it will be null.
One thing to be aware of: If someone sends an invalid token to your unprotected route, he will get a 401 failure response as for the secured firewall (exceptions are thrown even if you allows anonymous, invalid credentials should never be passed).

Hope this helps you.
