### ISSUE TITLE
Handle empty or null header prefix

### ISSUE THREAD

**Issue by chteuchteu** [lexik/LexikJWTAuthenticationBundle#310]
First, thank you for your great bundle!

`AuthorizationHeaderTokenExtractor->extract` method works well for non-null/empty prefixes (`Bearer` for example), but will return `false` otherwise.

For instance, I'd like to use a `X-Auth-Token: {token}` header. I set this up in my `config.yml`:
```yaml
token_extractors:
    authorization_header:
        prefix: ~
        name: X-Auth-Token
```

In this case, the [explode](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/TokenExtractor/AuthorizationHeaderTokenExtractor.php#L43) function will return an array with a single element (the token): we should check if the `prefix` is either null or empty before blindly assuming it's not, shouldn't we?
