### ISSUE TITLE
less-database non-existent service "security.user.provider.concrete.lexik_jwt". 

### ISSUE THREAD

**Issue by nicraMarcin** [lexik/LexikJWTAuthenticationBundle#338]
Hello

I've tried to run JWTUser but after configuration symfony says:

```
 bin/console cache:clear

                                                                                                                                         
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                             
  The service "security.authentication.manager" has a dependency on a non-existent service "security.user.provider.concrete.lexik_jwt".  
                                                                                                                                         
```
```
 providers:
        sql_db_provider:
            entity:
                class: SharedBundle:User
    
        jwt: 
            lexik_jwt: ~
                

firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
      # Custom authentication firewall for all request thats starts from /api
      api:
          pattern: ^/api/(?!token)
          guard:
              authenticators:
                  - app.jwt_token_authenticator
          stateless: true
          provider: lexik_jwk

      # Here you handle regular form authentication
      main:
          anonymous: ~
````
in debug there is no that service
```
 bin/console debug:container | grep lexik                                                                                                               
  lexik\bundle\jwtauthenticationbundle\encoder\jwtencoderinterface                 alias for "lexik_jwt_authentication.encoder.default"                                                                                             
  lexik\bundle\jwtauthenticationbundle\services\jwsprovider\jwsproviderinterface   Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\DefaultJWSProvider                                                                     
  lexik\bundle\jwtauthenticationbundle\services\jwttokeninterface                  alias for "lexik_jwt_authentication.jwt_manager"                                                                                                 
  lexik\bundle\jwtauthenticationbundle\services\jwttokenmanagerinterface           alias for "lexik_jwt_authentication.jwt_manager"                                                                                                 
  lexik\bundle\jwtauthenticationbundle\tokenextractor\tokenextractorinterface      Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\ChainTokenExtractor                                                                          
  lexik_jwt_authentication.encoder                                                 alias for "lexik_jwt_authentication.encoder.default"                                                                                             
  lexik_jwt_authentication.encoder.default                                         Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder                                                                                      
  lexik_jwt_authentication.encoder.lcobucci                                        Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder                                                                                      
  lexik_jwt_authentication.extractor.authorization_header_extractor                Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\AuthorizationHeaderTokenExtractor                                                            
  lexik_jwt_authentication.extractor.cookie_extractor                              Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\CookieTokenExtractor                                                                         
  lexik_jwt_authentication.extractor.query_parameter_extractor                     Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\QueryParameterTokenExtractor                                                                 
  lexik_jwt_authentication.handler.authentication_failure                          Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationFailureHandler                                                   
  lexik_jwt_authentication.handler.authentication_success                          Lexik\Bundle\JWTAuthenticationBundle\Security\Http\Authentication\AuthenticationSuccessHandler                                                   
  lexik_jwt_authentication.jwt_manager                                             Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager                                                                                         
  lexik_jwt_authentication.jwt_token_authenticator                                 alias for "lexik_jwt_authentication.security.guard.jwt_token_authenticator"                                                                      
  lexik_jwt_authentication.key_loader                                              Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\OpenSSLKeyLoader                                                                         
  lexik_jwt_authentication.security.guard.jwt_token_authenticator                  Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator       
```

**Comment by chalasr** [comment]
I can't reproduce. Which version of this bundle are you using? The provider has been introduced in [2.1](https://github.com/lexik/LexikJWTAuthenticationBundle/tree/v2.1.0).

Also the service is automatically created by the symfony security component and is private, you should find it using `sf debug:container --show-private|grep JWTUserProvider`.

Btw you have a typo in your config: `provider: lexik_jwk` => `provider: lexik_jwt`, but that's probably unrelated.

**Comment by nicraMarcin** [comment]
Hi
I use 2.4 version.

I had error in provider :) I copied and pasted from documentation and there was `lexik_jwt` :)
I've changed to `jwt` and there is no error :)

**Comment by chalasr** [comment]
oh indeed :)

**Comment by nicraMarcin** [comment]
So, if i want get data from payload which interface should I use? Symfony UserInterface get from database
```
    firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
      # Custom authentication firewall for all request thats starts from /api
      api:
          pattern: ^/api/(?!token)
          guard:
              authenticators:
                  - app.jwt_token_authenticator
          stateless: true
          provider: jwt

    providers:
        sql_db_provider:
            entity:
                class: SharedBundle:User
    
        jwt: 
            lexik_jwt: ~
```
