### ISSUE TITLE
Support for Nelmio API Doc

### ISSUE THREAD

**Issue by JuliusKoronci** [lexik/LexikJWTAuthenticationBundle#361]
Since I am using the auth bundle with swagger..wondering if there is an easy way to get the login route into the api doc? Thanks

**Comment by JuliusKoronci** [comment]
I found it in a closed issue..sorry for spamming..

**Comment by kix** [comment]
@JuliusKoronci, I have the same issue, could you share a link to the issue you've found?

**Comment by JuliusKoronci** [comment]
@kix I don't remember but you can check my repo..it should be there https://github.com/JuliusKoronci/Symfony-React-CI/tree/master/symfony-app

**Comment by allartk** [comment]
You can add the route to the paths array under the documentation key:
```
    documentation:
        paths:
            /api/login_check:
                post:
                    summary: get jwt
                    consumes:
                        - application/json
                    parameters:
                        - in: body
                          name: user
                          description: user credentials
                          schema:
                              type: object
                              required:
                                  - userName
                              properties:
                                  username:
                                      type: string
                                  password:
                                      type: string
```
