### ISSUE TITLE
Database user provider can't get user entity

### ISSUE THREAD

**Issue by eskrano** [lexik/LexikJWTAuthenticationBundle#364]
Hi all. i install fresh symfony 3 and install jwt auth bundle.
Make like this project https://github.com/chalasr/lexik-jwt-authentication-sandbox but when i make request to /api with my token i see this http://prntscr.com/ft7nlk . 
P.S. Registration and login_check work's fine, i cant get user .

API security.yml
```yml
api:
                pattern:   ^/api
                stateless: true
                anonymous: false
                provider: entity_provider
                guard:
                    authenticators:
                      - lexik_jwt_authentication.jwt_token_authenticator
                lexik_jwt: ~
```
