### ISSUE TITLE
Anonymous API calls

### ISSUE THREAD

**Issue by RonRademaker** [lexik/LexikJWTAuthenticationBundle#374]
Hi,

Parts of my API must be accessible to anonymous users, so I added `anonymous: true` to the api firewall:

```
api:
  pattern:   ^/api
  stateless: true
  anonymous: true
  guard:
    authenticators:
      - lexik_jwt_authentication.jwt_token_authenticator
```

But when I call without a token, I get `{"code":401,"message":"JWT Token not found"}`. What am I missing here?

**Comment by chalasr** [comment]
Hey, your issue is probably related to access controls which should allow being anonymously authenticated e.g:

```yaml
access_controls:
    - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_ANONYMOUSLY]] }
```

**Comment by RonRademaker** [comment]
Hi, thanks for the quick response. I checked the access_controls, but that's not the issue unfortunately.

**Comment by chalasr** [comment]
I just tried on our sandbox and it works as expected with anonymous listener enabled and proper access_controls. Could you try it and maybe fork it with the changes necessary to reproduce your issue? Usage:

```
git clone https://github.com/chalasr/lexik-jwt-authentication-sandbox/tree/allow-anonymous
cd lexik-jwt-authentication-sandbox
composer install
bin/console doctrine:database:create
bin/console doctrine:schema:update --force
bin/console server:run
curl http://localhost:8000/api

**Comment by RonRademaker** [comment]
I found the problem, but not yet the solution.

I have 

``` yml
   access_decision_manager:
        strategy:             unanimous
        allow_if_all_abstain: true
``` 

in my security settings, and it looks like that doesn't play nicely with the anonymous api access.
