### ISSUE TITLE
Using id field instead of username for finding users in database

### ISSUE THREAD

**Issue by pdoreau** [lexik/LexikJWTAuthenticationBundle#376]
I don't use any username. User login is made by email / password. Email can change so it's not suitable to store it in the JWT token as the identifying field.
User id seems to be the only field I can rely on for both JWT payload identitfying field and for the lookup in database.
How can I configure the bundle to do it ?

**Comment by Luckystrike561** [comment]
Hi any solution for your issue ? I have exactly the same ;)

**Comment by pdoreau** [comment]
@Luckystrike561 It seems ok with : 

 * id as `user_identity_field` (config.yml)
 * a custom JWTTokenAuthenticator using findOneById (userRepository)

Is that a good / recommended way ?

**Comment by chalasr** [comment]
@pdoreau I think it can be simpler:

1) `id` as `user_identity_field`
2) the symfony built-in `entity` provider configured to use `id` as property to load users
    ```yaml
    security:
        providers:
              db_provider:
                  entity:
                      class: AppBundle:User
                      property: id
    ```

Note: 2) can be replaced by a custom user provider, while it is able to load users based on the configured `user_identity_field`.
