### ISSUE TITLE
Configure a different key pair per firewall guard

### ISSUE THREAD

**Issue by jolleychris** [lexik/LexikJWTAuthenticationBundle#378]
Hi 
Thank you for this excellent bundle!
I would like to use a different .pem key pair for each firewall authenticator. It seems that this is not trivial, or at least, I can not see what changes I would need to make to the bundle in order to achieve this. Is there a means to do it, or how could it best be approached?

At a high level, with changes to the extension config and loader I could read an array of key paths
, or multiple key directory params.  But, I'm struggling to see how I could potentially then make use of that, and how I could pass that as a parameter in the firewall config.

Can anybody suggest an approach to this, and where i should be looking?

```
firewalls:        
        api:
            pattern:   ^/api
            stateless: true
            provider: myprovider1
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator        
        other_api:
            pattern:   ^/api2
            stateless: true
            provider: myprovider2
            guard:
                authenticators:
                    #new authenticator supporting other keys?
                    - lexik_jwt_authentication.jwt_token_authenticator2    
```
