### ISSUE TITLE
Question: Database-less user: initial token creation...

### ISSUE THREAD

**Issue by akomm** [lexik/LexikJWTAuthenticationBundle#382]
This documentations explains everything, but as soon as it comes to how you actually initially create a token from a given source, e. G. database, it just makes a cut.

I understand JWT and I wanted to go the db-less way. Your db-less provider part is clear. From my sy security understand I have an idea how I could create the token: Just use an entity provider for the login firewall and the JWT provider for the token (some "cons" coming). 

I also have to use two different "user" types. One as entity for login API and one as JWT db-less user, for the token authenticated API. This is because the username property is part of the JwtUser type and has no mapping information, I would have to override its private property to add mapping and I would carry over API my entity User does not need. Making two unrelated classes on the other hand makes it kind of smell in my opinion.

But because the docs either hide it impossible or it just miss any hints regarding the actual initial token creation, I'm not sure whether the above approach is the intended way to do it or not.

The whole documentation seem to have "holes" whenever it comes to the initial token creation (otherwise its very good!). 
It feels like "1. collection underparts 2. ??? 3. profit". Even the "getting started/usage" gives some configuration and then proposes to check using curl, while the result on given conditions would be always a 401.

*edit* Hm. Going to try implementing JwtUserInterface instead of extending JwtUser, lets see if that works out.

*edit2*

My current solution, with two User types, matching in the UserInterface interface from symfony security component:

```yml
security:
  providers:
    jwt:
      lexik_jwt:
        class: AppBundle\Security\JwtUser
    db:
      entity:
        class: AppBundle\Entity\User
        property: username

  encoders:
    AppBundle\Entity\User: bcrypt

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern:  ^/api/login
      stateless: true
      anonymous: true
      provider: db
      form_login:
        check_path:               /api/login_check
        success_handler:          lexik_jwt_authentication.handler.authentication_success
        failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        require_previous_session: false

    api:
      pattern:   ^/graphql
      stateless: true
      provider:  jwt
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/graphql,   roles: IS_AUTHENTICATED_FULLY }
```

The Entity user is only used on login. Rest works with JwtUser
