### ISSUE TITLE
Firewall with support of JWT and Digest authentication

### ISSUE THREAD

**Issue by raziel057** [lexik/LexikJWTAuthenticationBundle#384]
I would like to be able to configure a Firewall on route ``/api`` which allow authentication by JWT and Digest Authentication (a bit like in that example: https://symfony.com/doc/current/security/multiple_user_providers.html).

When I define the Firewall like this I got an error: Type error: Argument 4 passed to Symfony\Component\Security\Http\Firewall\DigestAuthenticationListener::__construct() must be an instance of Symfony\Component\Security\Http\EntryPoint\DigestAuthenticationEntryPoint, instance of Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator given

```
firewalls:
   api:
            pattern:   ^/api
            stateless: true
            provider: jwt_provider
            http_digest:
                provider: in_memory
                realm:    "Secured Demo API"
                secret:   "SECRET"
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
``` 

Do you know if this use case could be supported?
