### ISSUE TITLE
Using the bundle with token created somewhere else

### ISSUE THREAD

**Issue by greg0ire** [lexik/LexikJWTAuthenticationBundle#409]
My company is intending to use [http://www.keycloak.org/](Keycloak) to generate JWTs for applications that need it.
I'm trying to use this bundle for the guard it provides, which I guess can check the signature against a public key.
I skipped the configuration step where you provide the keys for the moment, and created the following security config:

```
security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY  }
```

The app crashes

> Environment variable not found: "JWT_PRIVATE_KEY_PATH".

This sounds wrong, because I'm not trying to generate a token here, since I didn't provide any credentials.

I can see it trying to load a `JWSProviderInterface` implementation at some point. This interface looks like it should maybe be split into 2 interfaces, so that the private key would no longer be depended on:

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/ddfd184c8dd2f56b0b01bc5731dc84c9c9396701/Services/JWSProvider/JWSProviderInterface.php#L10-L30

It would be great if the JWT generation was optional. Not sure if I'm making sense, these are my first steps with JWT.

What do you think? Does it make sense to use this bundle in my case, or is it not worth the hassle?
