### ISSUE TITLE
Unauthorized when I use entity provider

### ISSUE THREAD

**Issue by ramrami** [lexik/LexikJWTAuthenticationBundle#41]
First of all thank you for this nice bundle :+1: 
Now I'm stack with this problem : when I use the in_memory provider everything is working fine , but when I change the provider to use a Doctrine entity which implements UserInterface , the login_check passes , I get my token but when I try to access to a secured link I get 401 Unauthorized.

![issue](https://cloud.githubusercontent.com/assets/9569590/4917033/d6fc3df6-64df-11e4-96d7-b43d146a3934.png)

Here you can see the token in the request : 
![issue2](https://cloud.githubusercontent.com/assets/9569590/4917051/216f995a-64e0-11e4-8d85-162dbe936e12.png)

My config : 

```
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Acme\DemoBundle\Entity\DemoUser: plaintext
        Acme\DemoBundle\Entity\DemoAdmin: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity: { class: Acme\DemoBundle\Entity\DemoUser, property: email }
        admins:
            entity: { class: Acme\DemoBundle\Entity\DemoAdmin, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_admin:
            pattern:  ^/api/admin/login
            stateless: true
            anonymous: true
            provider: admins
            form_login:
                check_path: /api/admin/login_check
                require_previous_session: false
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure                     
        api_admin:
            pattern:   ^/api/admin
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer  
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: users
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: _username
                password_parameter: _password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure   
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer   
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, roles: [ ROLE_ADMIN ]}
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```
