### ISSUE TITLE
trigger check_path manually from controller

### ISSUE THREAD

**Issue by kanonhian** [lexik/LexikJWTAuthenticationBundle#420]
```
      login:
            pattern: ^/login
            stateless: true
            form_login:
                provider: fos_userbundle
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            anonymous:    true
```

This is my firewall ands work fine. Thing is I have my login decoupled from my controller via REST. What I need is that when accessing to /login the check_path be triggered and therefore, the authentication process. Any idea?
