### ISSUE TITLE
populating the tokenstorage

### ISSUE THREAD

**Issue by kanonhian** [lexik/LexikJWTAuthenticationBundle#438]
I am using a doctrine filter which adds 'deleted=true' to all my queries. Now I want to allow this only for non admin users, so I need to do something like this in order to check the user credentials: $this->get(security.token_storage)->getToken()->getUser(), but the token is empty, even when I am authenticated. Any other way to get the User?

**Comment by kanonhian** [comment]
Well I took a shortcut, I guess. Subscribing to authenticationsuccess event
```
    before_request_listener:
            class: AplicacionBaseBundle\Filters\FilterActivator
            arguments: ["@doctrine.orm.entity_manager","@annotation_reader","@security.token_storage"]
            tags:
                -
                    name: kernel.event_listener
                    event: security.authentication.success
                    method: onSecurityInteractiveLogin
```

Then in my onSecurityInteractiveLogin method 

```
    public function onSecurityInteractiveLogin(AuthenticationEvent $event)
    {
 $token = $event->getAuthenticationToken();
        $user=$token->getUser();
//Check if anonymous user
        if(!$user instanceof UserInterface)
            return;
        if(!$user->hasRole('ROLE_CHUCK_NORRIS')) {
            $filter = $this->em->getFilters()->enable('deletedFilter');
            $filter->setAnnotationReader($this->reader);
            $filter->setParameter('idEnterprise',$user->getEnterprise()->getId());
}
```
I guess it's all. If there I am missing something please tell me.
