### ISSUE TITLE
Unit tests, generating token

### ISSUE THREAD

**Issue by nWidart** [lexik/LexikJWTAuthenticationBundle#445]
Hello,

I've been struggling to unit test generating a token in order to test my api endpoints.

I've followed the docs using:

```php
protected function createAuthenticatedClient($username = 'user', $password = 'password')
{
    $client = static::createClient();
    $client->request(
        'POST',
        '/api/login_check',
        array(
            '_username' => $username,
            '_password' => $password,
        )
    );

    $data = json_decode($client->getResponse()->getContent(), true);

    $client = static::createClient();
    $client->setServerParameter('HTTP_Authorization', sprintf('Bearer %s', $data['token']));

    return $client;
}
```

And in my actual test method:

```php
public function testGetUsers()
{
    $user = new User();
    $user->setEmail('john@doe.com');
    $user->setIsActive(1);
    $user->setUsername('user');
    $user->setPassword('password');
    $em = self::$kernel->getContainer()->get('doctrine')->getManager();
    $em->persist($user);
    $em->flush();

    $client = $this->createAuthenticatedClient();
    $client->request('GET', '/api/users');
    $this->assertEquals(200, $client->getResponse()->getStatusCode());
}
```

Yet, this returns `{"code":401,"message":"Bad credentials"}`.

My `test/security.yaml` has this:

```yaml
security:
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
```
Basically json_login changed to form_login.

I have a password hasher listener to hash the password. I thought it might have come to that, but when I create a user using swagger, and can generate a token for that newly created user (and thus its hashed password).

Did I miss anything to make this work?

Thank you!
