### ISSUE TITLE
401 unauthorized, after login is 200

### ISSUE THREAD

**Issue by tharun148** [lexik/LexikJWTAuthenticationBundle#452]
I have deployed a symfony with LexikJWTAuthenticationBundle bundle in apache2, php7.0 server.
My login api is working fine and when using the token and I have tried any other url it throws 401 error.
I have tried this [link](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#important-note-for-apache-users). But it also throws same error below is my virtual host and htaccess files

```
<VirtualHost *:80>
    ServerName examble.com
    ServerAlias www.examble.com

    DocumentRoot /var/www/html/examble.com/web
    <Directory /var/www/html/examble.com/web>
        AllowOverride None
        Order Allow,Deny
        Allow from All

        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{HTTP:Authorization} ^(.*)
            RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
        </IfModule>
    </Directory>
    # uncomment the following lines if you install assets as symlinks
    # or run into problems when compiling LESS/Sass/CoffeeScript assets
    # <Directory /var/www/project>
    #     Options FollowSymlinks
    # </Directory>

    # optionally disable the RewriteEngine for the asset directories
    # which will allow apache to simply reply with a 404 when files are
    # not found instead of passing the request into the full symfony stack
    <Directory /var/www/html/examble.com/web/bundles>
        <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{HTTP:Authorization} ^(.*)
            RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
        </IfModule>
    </Directory>
    ErrorLog /var/log/apache2/project_error.log
    CustomLog /var/log/apache2/project_access.log combined

    # optionally set the value of the environment variables used in the application
    #SetEnv APP_ENV prod
    #SetEnv APP_SECRET <app-secret-id>
    #SetEnv DATABASE_URL "mysql://db_user:db_pass@host:3306/db_name"
</VirtualHost>
```

htaccess file

```
<IfModule mod_negotiation.c>
    Options -MultiViews
</IfModule>

<IfModule mod_rewrite.c>
    RewriteEngine On

    # Determine the RewriteBase automatically and set it as environment variable.
    # If you are using Apache aliases to do mass virtual hosting or installed the
    # project in a subdirectory, the base path will be prepended to allow proper
    # resolution of the app.php file and to redirect to the correct URI. It will
    # work in environments without path prefix as well, providing a safe, one-size
    # fits all solution. But as you do not need it in this case, you can comment
    # the following 2 lines to eliminate the overhead.
    RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
    RewriteRule ^(.*) - [E=BASE:%1]

    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect to URI without front controller to prevent duplicate content
    # (with and without `/app.php`). Only do this redirect on the initial
    # rewrite by Apache and not on subsequent cycles. Otherwise we would get an
    # endless redirect loop (request -> rewrite to front controller ->
    # redirect -> request -> ...).
    # So in case you get a "too many redirects" error or you always get redirected
    # to the start page because your Apache does not expose the REDIRECT_STATUS
    # environment variable, you have 2 choices:
    # - disable this feature by commenting the following 2 lines or
    # - use Apache >= 2.3.9 and replace all L flags by END flags and remove the
    #   following RewriteCond (best solution)
    RewriteCond %{ENV:REDIRECT_STATUS} ^$
    RewriteRule ^app\.php(?:/(.*)|$) %{ENV:BASE}/$1 [R=301,L]

    # If the requested filename exists, simply serve it.
    # We only want to let Apache serve files and not directories.
    RewriteCond %{REQUEST_FILENAME} -f
    RewriteRule ^ - [L]

    # Rewrite all other queries to the front controller.
    RewriteRule ^ %{ENV:BASE}/app.php [L]
</IfModule>

<IfModule !mod_rewrite.c>
    <IfModule mod_alias.c>
        # When mod_rewrite is not available, we instruct a temporary redirect of
        # the start page to the front controller explicitly so that the website
        # and the generated links can still be used.
        RedirectMatch 302 ^/$ /app.php/
        # RedirectTemp cannot be used instead
    </IfModule>
</IfModule>
```
This is my curl request and output

![screenshot from 2018-02-09 19-50-16](https://user-images.githubusercontent.com/22390881/36032022-a8cc5c8c-0dd2-11e8-9665-01e79f54123b.png)

![screenshot from 2018-02-09 19-52-24](https://user-images.githubusercontent.com/22390881/36032082-d4a33a9c-0dd2-11e8-91da-a9e38ca8e541.png)
![screenshot from 2018-02-09 19-52-41](https://user-images.githubusercontent.com/22390881/36032083-d4cd0d90-0dd2-11e8-98f0-7f8dcc0bdca5.png)

**I have used symfony 3.2**
here is my security.yaml file

```
security:
    role_hierarchy:
        ROLE_SELLER:      ROLE_USER
        ROLE_PARTICIPANT: ROLE_USER
        ROLE_ADMIN:       ROLE_USER
    encoders:
        OpenLoyalty\Bundle\UserBundle\Entity\User: bcrypt

    providers:
        admin_provider:
            id: oloy.user.admin_provider
        customer_provider:
            id: oloy.user.customer_provider
        seller_provider:
            id: oloy.user.seller_provider
    firewalls:
        admin_login:
            pattern:  ^/api/admin/login
            stateless: true
            anonymous: true
            provider: admin_provider
            form_login:
                check_path:               /api/admin/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        customer_login:
            pattern:  ^/api/customer/login
            stateless: true
            anonymous: true
            provider: customer_provider
            form_login:
                check_path:               /api/customer/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        seller_login:
            pattern:  ^/api/seller/login
            stateless: true
            anonymous: true
            provider: seller_provider
            form_login:
                check_path:               /api/seller/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        refresh:
            pattern:  ^/api/token/refresh
            stateless: true
            anonymous: true
        settings_choices:
            pattern:  ^/api/settings/choices
            stateless: true
            anonymous: true
        self_registration:
            pattern:  ^/api/customer/self_register
            stateless: true
            anonymous: true
        activate_account:
            pattern:  ^/api/customer/activate
            stateless: true
            anonymous: true
        password_reset:
            pattern:  ^/api/password/reset
            stateless: true
            anonymous: true
        password_reset_request:
            pattern:  ^/api/merchant/password/reset/request
            stateless: true
            anonymous: true
        password_reset_request_for_customer:
            pattern:  ^/api/customer/password/reset/request
            stateless: true
            anonymous: true
        map_edc_transaction:
            pattern:  ^/api/mapEdcTransaction
            stateless: true
            anonymous: true
        transaction:
            pattern:  ^/api/transaction
            stateless: true
            anonymous: true
            methods: [POST]
        card_activation_for_customer:
            pattern:  ^/api/cardactivation
            stateless: true
            anonymous: true
        banking_sale:
            pattern:  ^/api/banking/edcTransaction
            stateless: true
            anonymous: true
        banking_topup:
            pattern:  ^/api/banking/topupcard
            stateless: true
            anonymous: true
        banking_balance:
            pattern:  ^/api/banking/balance
            stateless: true
            anonymous: true
        banking_card_activation:
            pattern:  ^/api/banking/card/activation
            stateless: true
            anonymous: true
        banking_card_deactivation:
            pattern:  ^/api/banking/card/deactivation
            stateless: true
            anonymous: true
        banking_get_transaction:
            pattern:  ^/api/banking/transaction/data
            stateless: true
            anonymous: true
        banking_void:
            pattern:  ^/api/banking/void
            stateless: true
            anonymous: true
        banking_coupon_redeem:
            pattern:  ^/api/banking/coupon/redeem
            stateless: true
            anonymous: true
        banking_transaction_summary:
            pattern:  ^/api/banking/transaction/summary
            stateless: true
            anonymous: true
        banking_transaction_details:
            pattern:  ^/api/banking/transaction/details
            stateless: true
            anonymous: true
        echo_test:
            pattern:  ^/api/echo/test
            stateless: true
            anonymous: true
        echo_header:
            pattern:  ^/api/echo/header
            stateless: true
            anonymous: true
        card_verification_for_customer:
            pattern:  ^/api/tokenverfication
            stateless: true
            anonymous: true
        campaign_photo:
            pattern:  ^/api/campaign/([a-zA-Z\-0-9]+)/photo
            methods: ["GET"]
            stateless: true
            anonymous: true
        giftcard_photo:
            pattern:  ^/api/merchant/([a-zA-Z\-0-9]+)/giftcardphoto
            methods: ["GET"]
            stateless: true
            anonymous: true
        loyaltycard_photo:
            pattern:  ^/api/merchant/([a-zA-Z\-0-9]+)/loyaltycardphoto
            methods: ["GET"]
            stateless: true
            anonymous: true
        doc:
            pattern:  ^/doc
            stateless: true
            anonymous: true
        translations:
            pattern:  ^/api/translations
            stateless: true
            anonymous: true
        seller_api:
            pattern:   ^/api/seller
            stateless: true
            provider: seller_provider
            lexik_jwt: ~
        customer_api:
            pattern:   ^/api/customer
            stateless: true
            provider: customer_provider
            lexik_jwt: ~
        admin_api:
            pattern:   ^/api
            stateless: true
            provider: admin_provider
            lexik_jwt: ~
            guard:
              authenticators:
                - oloy.user.guard.token
              entry_point: oloy.user.guard.token
        main:
            pattern: ^/
            anonymous: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/self_register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/activate/*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/campaign/([a-zA-Z\-0-9]+)/photo, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/merchant/([a-zA-Z\-0-9]+)/giftcardphoto, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/merchant/([a-zA-Z\-0-9]+)/loyaltycardphoto, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: ["GET"] }
        - { path: ^/api/password/reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/merchant/password/reset/request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/password/reset/request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/mapEdcTransaction, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/transaction, roles: IS_AUTHENTICATED_ANONYMOUSLY, methods: [POST] }
        - { path: ^/api/cardactivation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/edcTransaction, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/topupcard, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/balance, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/card/activation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/card/deactivation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/void, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/transaction/data, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/coupon/redeem, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/transaction/summary, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/banking/transaction/details, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/echo/test, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/echo/header, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/tokenverfication, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/customer/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/seller/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/seller/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/settings/choices, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/translations, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

```

help me to solve this issue
 Thanks
