### ISSUE TITLE
JWTToken change fields for generate

### ISSUE THREAD

**Issue by shubaivan** [lexik/LexikJWTAuthenticationBundle#457]
I use Symfony 3.3.10 with `"lexik/jwt-authentication-bundle": "~2.0",` and for `user_identity_field` I use email

    lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'
    user_identity_field: email

But after my user, call put request with `email`, I mean change email to something another. after have been change, when I call another api, example get user profile, I have error:

    {
      "code": 401,
      "message": "Unable to load an user with property \"email\" = \"q@q.com\". If the user identity has changed, you must renew the token. Otherwise, verify that the \"lexik_jwt_authentication.user_identity_field\" config option is correctly set."
    }

I understood, because I change email, which part for generating token, but I thought token saved in session and don't need regenerate token after change email or password. 

My question how to change generating token fields, example I want use some constant field, example id?

**Comment by FuggyD** [comment]
i have the same issue with one difference:
`user_identity_field: id`

and my id of the user entity is not auto increment:
`/**
     * @ORM\Column(type="guid")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     */
    private $id;`

example: 9186b8bd-170b-11e8-82f8-480fcf324d89

**Comment by Bonfante** [comment]
The user entity method getusername is returning the email?

**Comment by HecFranco** [comment]
How can I change the user_identity_field username (default value) an email? I use symfony 4 and I get this error `"message": "The key \"_username\" must be a string, \"NULL\" given.",`. 
Someone found a solution?

**Comment by chalasr** [comment]
@HecFranco that's for the `form_login` part which is a symfony thing, not related to this bundle.
What you nee is:

```yaml
form_login:
    # ...
    username_parameter: email
```

**Comment by alex74m** [comment]
Well, the error will be

> The key "email" must be a string, "NULL" given.

**Comment by chalasr** [comment]
Then your HTTP request is incorrect, it just does not contain the `email` parameter.

**Comment by chalasr** [comment]
Again, that's a symfony issue, `form_login` is part of symfony. You're looking for https://symfony.com/support

**Comment by RajeshwariN** [comment]
I use Symfony 3.3.11 with "lexik/jwt-authentication-bundle": "2.4.4", and user_identity_field - mobileNo

I get this error on consuming login API

eerror": {
        "code": 400,
        "message": "Bad Request",
        "exception": [
            {
                "message": "The key \"username\" must be provided.",
                 ......
           }
       ]
}

**Comment by EresDev** [comment]
> I use Symfony 3.3.11 with "lexik/jwt-authentication-bundle": "2.4.4", and user_identity_field - mobileNo
> 
> I get this error on consuming login API
> 
> eerror": {
> "code": 400,
> "message": "Bad Request",
> "exception": [
> {
> "message": "The key "username" must be provided.",
> ......
> }
> ]
> }

The answer to your problem is right there. If you are not using the key 'username' for authentication, you must specify it. For example, if you are using 'mobileNo' for authentication, you must specify it in your security.yaml.

```yaml
form_login:
    # ...
    username_parameter: mobileNo
```

**Comment by RajeshwariN** [comment]
@EresDev thanks for help! I updated user_identity_field in config.yml and it worked

**Comment by saifgo** [comment]
login:
            #
            json_login:
                #
                username_path: email

**Comment by HashtagAssist** [comment]
Hello :)) Have I misunderstood something? I want to use the field "email" to get the token at the endpoint "check_login". I have exactly the same problem as @RajeshwariN and have tried the solution of @EresDev. Or the one from saifgo because I use json_login. But it doesn't work. "message": "The key "username" must be provided.".. I have change the following parts in the security.yaml

```
 providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: email

```
```
  firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                username_path: email
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```


and into lexik_jwt_authentication.yaml

```
lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      '' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600
    user_identity_field: email

```

**Comment by RajeshwariN** [comment]
@HashtagAssist Try by adding **provider: entity_provider** under login

**Comment by HashtagAssist** [comment]
Thanks for the quick response! Anyway that dont help :( i still get the the token by this json {"username":"test","password":"test"}.
{"username":"test@test.de","password":"test"} gives Invalid credentials back. And {"email":"test@test.de","password":"test"} result in a 400 (The key "username" must be provided.)

**Comment by gettmure** [comment]
I have the same issue while I try to redirect to login api route, but it gives me `The key "password" must be provided`. My controller returns a redirect response:

```
return $this->redirectToRoute('api_login', [
    'email'    => $user->getEmail(),
    'password' => $user->getPassword(),
], Response::HTTP_TEMPORARY_REDIRECT);
```

My `security.yaml` is configured with the following code:

```
api_login:
    pattern: ^/api/auth/login
    stateless: true
    anonymous: true
    provider: fos_userbundle
    json_login:
        check_path: /api/auth/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

And `lexik_jwt_authentication.yaml`:
```
lexik_jwt_authentication:
    secret_key:          '%env(resolve:JWT_SECRET_KEY)%'
    public_key:          '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase:         '%env(JWT_PASSPHRASE)%'
    token_ttl:           86400
    user_identity_field: id
```

Any suggestions?
