### ISSUE TITLE
CURL works - ReacJs returns me 401 bad credentials

### ISSUE THREAD

**Issue by RecanN** [lexik/LexikJWTAuthenticationBundle#458]
Hi all,
I'm trying to create a jwt authentication with fosuserbundle, after installing lexkJwtAuthenticationVundle my CURL command line works very fine, but when I try to fetch post username and password in ReactJs the server returns me "401" message:"Bad credentials".

my security file : 

```yml
security:
    
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                    Nacer:
                        password: Nacer
                        roles: [ROLE_USER]

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            provider: fos_userbundle
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

My login function in React :

```js
function login(data) {
  let formData  = new FormData();
  formData.append("_username", data.username);
  formData.append("_password", data.password);
  
  const requestOptions = {
    method: 'POST',
    headers: {
      'Accept': 'application/json, application/xml, text/plain, text/html, *.*',
      'Content-Type': 'application/form-data;charset=UTF-8' },
    body: formData,
  };

  return fetch(server+'api/login_check', requestOptions)
  .then(response => {
    if (!response.ok) {
      return Promise.reject(response.statusText);
    }

    return response.json();
  })
  
} 
```

**Comment by chalasr** [comment]
Your configuration contains:

```
username_parameter: username
password_parameter: password
```

But your code uses `_username` and `_password`. Try without underscores?

**Comment by RecanN** [comment]
I updated still have the same error ! :(

**Comment by RecanN** [comment]
I restart a new project and it's works with this security : 

```yml
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

        in_memory:
            memory: ~

    firewalls:
        login:
            pattern:    ^/api/login
            stateless:  true
            anonymous:  true
            provider:   fos_userbundle
            form_login:
                check_path:               /api/login_check
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```
