### ISSUE TITLE
Logging using Doctrine user provider and JWT

### ISSUE THREAD

**Issue by cduran433** [lexik/LexikJWTAuthenticationBundle#476]
Hello,

I am trying to implement the JWT authentication in my project follow the instructions written in the [documentation](https://api-platform.com/docs/core/jwt). I can make it work with if I use the memory provider but when I am trying to do it with the entity provider I always get the response bad credentials. If I change the provider and I use "in_memory" instead of "my_own_provider" it works. I have some fixtures with some users and I check the database and it contains the rows of the users correctly.

This is my security.yml

```yml
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
#    encoders:
#        App\Entity\User: bcrypt


    encoders:
        App\Entity\User: plaintext
        Symfony\Component\Security\Core\User\User: plaintext
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: user-test
                        roles: 'ROLE_USER'
                    admin:
                        password: admin-test
                        roles: 'ROLE_ADMIN'
        my_own_provider:
            entity:
                class: App\Entity\User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: my_own_provider
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api_documentation:
            pattern:   ^/api/documentation
            anonymous: ~
            provider: my_own_provider

        api:
            pattern:   ^/
            stateless: true
            provider: my_own_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator



    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/documentation, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,       roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_API: [ROLE_USER]
```

This is my entity class:

```
<?php

// src/Entity/User.php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Table(name="app_users")
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=254, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    public function __construct()
    {
        $this->isActive = true;
        // may not be needed, see section on salt below
        // $this->salt = md5(uniqid('', true));
    }

    public function getUsername()
    {
        return $this->username;
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function getPassword()
    {
        return $this->password;
    }

    public function getRoles()
    {
        return array('ROLE_USER');
    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId( $id )
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param mixed $email
     */
    public function setEmail( $email )
    {
        $this->email = $email;
    }

    /**
     * @return mixed
     */
    public function getIsActive()
    {
        return $this->isActive;
    }

    /**
     * @param mixed $isActive
     */
    public function setIsActive( $isActive )
    {
        $this->isActive = $isActive;
    }




    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->password,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }
}
```
