### ISSUE TITLE
Issue with security.yml (authentication_provider)

### ISSUE THREAD

**Issue by Kaz-** [lexik/LexikJWTAuthenticationBundle#50]
I'm trying to use this bundle with FOSUser and i'm a bit stuck ..
Authentication works well, i get my token fine.

But I'm having an issue with my security.yml and can't find what..

I used [this example](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md) to protect my authenticated route (/api) and i'm getting this error trying to call `/api/users/me/` :
#### InvalidConfigurationException: Unrecognized option "authentication_provider" under "security.firewalls.api.lexik_jwt"
```yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: myproject_user.user_provider.email
           

    firewalls:
        api_login:
            pattern: ^/api/users/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/users/login
                require_previous_session: false
                username_parameter: email
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure 


        api:
            pattern: ^/api/
            lexik_jwt:
                authorization_header: # check token in Authorization Header
                    enabled: true
                    prefix:  Bearer
                query_parameter:      # check token in query string parameter
                    enabled: true
                    name:    bearer
                throw_exceptions:        false     # When an authentication failure occurs, return a 401 response immediately
                create_entry_point:      true      # When no authentication details are provided, create a default entry point that returns a 401 response
                authentication_provider: lexik_jwt_authentication.security.authentication.provider  
        

    access_control:
        # - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin/, role: ROLE_ADMIN }
```
The "authentication_provider" seems to be the issue, but I don't know why..
