### ISSUE TITLE
login_check returns 404 error on production while works well in development

### ISSUE THREAD

**Issue by Aerendir** [lexik/LexikJWTAuthenticationBundle#501]
As per the title, on local development machine all works as expected while on production I get a 404 error (not found).

I really don't understand why there is this difference in the behaviour as I double checked all what I can.

I'm on Symfony 4.1 and this is my configuration:

```yaml
# config/routes.yaml
login_check:
    path:     /api/login_check
    methods:  [POST]
    defaults:
        _format: json
```

and the firewalls:

```yaml
# config/packages/security
security:
    ...
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern: ^/api/register
            stateless: true
            anonymous: true
        api:
            # Add the trailing slash to enable the Swagger UI (https://stackoverflow.com/a/49967251/1399706)
            pattern: ^/api/
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            pattern: ^/
            anonymous: true
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Add the trailing slash to enable the Swagger UI (https://stackoverflow.com/a/49967251/1399706)
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
```

I have no different `security.yaml` in `dev` environment nor in the `prod` one.

Any idea is welcomed!
