### ISSUE TITLE
[2.5.0] Release - The algorithm \"RS256\" is not supported for OpenSSL

### ISSUE THREAD

**Issue by sorinbb** [lexik/LexikJWTAuthenticationBundle#514]
We use Symfony 4.0 and experienced following error:

The algorithm \"RS256\" is not supported for OpenSSL

Please revise the 2.5.0 branch changes and fix accordingly.
We had to downgrade back to 2.4.4 version for a while.

**Comment by chalasr** [comment]
Can you please share your configuration here? My guess is that you have the following:

```yaml
lexik_jwt_authentication:
    # ...
    encoder: 
        service: 'lexik_jwt_authentication.encoder.default'
```

This in indeed a bug anyways.
