### ISSUE TITLE
Cant override expiration / ttl

### ISSUE THREAD

**Issue by do-web** [lexik/LexikJWTAuthenticationBundle#521]
It is not possible to override the default expiration time to unlimited.

```
$encoder = $this->container->get('lexik_jwt_authentication.encoder');
$token = $encoder->encode(['email' => $data->getEmail()]);
```

With the manager it is also not possible:
```
$jwtManager = $this->container->get('lexik_jwt_authentication.jwt_manager');
$token = $jwtManager->create($newJwtUser);
```

I also tried this to remove expiration for unlimited lifetime:

```
public function onJWTCreated(JWTCreatedEvent $event)
{
    $payload        = $event->getData();
    $payload['exp'] = null;
// unset($payload['exp']); also not working

    $event->setData($payload);
}

**Comment by alexsegura** [comment]
I also want to generate token that never expires. 
The [example](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md#example-override-token-expiration-date-calculation-to-be-more-flexible) in the docs is wrong. 

This is because the `exp` claim is actually added by the `JWSProviderInterface` implementation, whenever there is a `ttl` defined. 

I see no easy way to do this ☹️
The only way I found is by overriding a bunch of services:

```yaml
'lexik_jwt_authentication.jws_provider.not_expiring':
  public: true
  parent: Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\JWSProviderInterface
  arguments:
    index_3: ~

'lexik_jwt_authentication.encoder.not_expiring':
  parent: lexik_jwt_authentication.encoder
  arguments:
    index_0: '@lexik_jwt_authentication.jws_provider.not_expiring'

'lexik_jwt_authentication.jwt_manager.not_expiring':
  parent: lexik_jwt_authentication.jwt_manager
  arguments:
    index_0: '@lexik_jwt_authentication.encoder.not_expiring'
```
