### ISSUE TITLE
Deprecation Notices using PHPUnit

### ISSUE THREAD

**Issue by Faecie** [lexik/LexikJWTAuthenticationBundle#523]
Hey, there! Thank you for the bundle!
I stuck with the problem that unit-tests do not pass due to a deprecation notice
```1x: The "Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\OpenSSLKeyLoader" class is deprecated since version 2.5 and will be removed in 3.0. Use "Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\RawKeyLoader" instead.```

My bundle config is easy as
```
lexik_jwt_authentication:
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
security:
  providers:
    jwt:
      lexik_jwt: ~
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern:   ^/api
      stateless: true
      provider: jwt
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
  access_control:
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```

I xdebugged the problem and found out, that it happens because of in a process of building container Symfony tries to initiate reflection of the class OpenSSLKeyLoader that has error triggering the E_USER_DEPRECATED 
All that we need here is to declare service as deprecated in a container

```
<service id="lexik_jwt_authentication.key_loader.openssl" class="Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\OpenSSLKeyLoader" parent="lexik_jwt_authentication.key_loader.abstract">
            <deprecated>The "%service_id%" service is deprecated since version 2.5 and will be removed in 3.0. Use lexik_jwt_authentication.key_loader.raw instead.</deprecated>
        </service>
```

Then Symfony won't touch this service and we are good to go. Please could you fix it, or I myself could open PR

lexik/jwt-authentication-bundle:2.5.1
