### ISSUE TITLE
Difference between symfony 3.2 and 3.4 ?

### ISSUE THREAD

**Issue by maximebourdel** [lexik/LexikJWTAuthenticationBundle#535]
Hi,

I recently tried upgrade my project but in vain when i try to add my guard with my custom WebserviceUserProvider WebserviceUser and JWTTokenAuthenticator

The problem seems to be located in my createFromPayloads, giving me issues 

before i had this : 
```
    public static function createFromPayload($username, array $payload)
    {
        //Cas ou l'utilisateur se login
        if (isset($payload['roles'])) {
            return new self($username, $payload['roles']);
        //Cas ou l'utilisateur à déjà son token
        } else {
            return new self($username);
        }
    }
```

but  it gives me this error : 
`{"message":"Warning: hash_equals(): Expected known_string to be a string, null given","class":"Symfony\\Component\\Debug\\Exception\\ContextErrorException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Core\/Encoder\/BasePasswordEncoder.php","line":84,"args":[]}
`

i tried  to remove that isset and always add $payload['roles']
so it looks like : 
```
    public static function createFromPayload($username, array $payload)
    {
        return new self($username, $payload['roles']);
    }
```

And now i got this errror : 
```
[2018-07-19 08:49:29] request.INFO: Matched route "login_check". {"route":"login_check","route_parameters":{"_route":"login_check"},"request_uri":"http://127.0.0.1/carPool/api/public/index.php/login_check","method":"POST"} []
[2018-07-19 08:49:29] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"login","authenticators":1} []
[2018-07-19 08:49:29] security.DEBUG: Calling getCredentials() on guard configurator. {"firewall_key":"login","authenticator":"App\\Security\\Guard\\JWTTokenAuthenticator"} []
[2018-07-19 08:49:29] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): Notice: Undefined index: roles at /var/www/html/carPool/api/vendor/symfony/security/Core/Authentication/Provider/DaoAuthenticationProvider.php:92, Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Notice: Undefined index: roles at /var/www/html/carPool/api/src/Security/User/WebserviceUser.php:139)"} []

```

Here is the code i have (i precise everything was working well in my 3.2 version but i don't know how to go forther in debug :s .

```
<?php 

// src/App/Security/User/WebserviceUser.php
namespace App\Security\User;

use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\EquatableInterface;

use Lexik\Bundle\JWTAuthenticationBundle\Security\User\JWTUserInterface;

class WebserviceUser implements EquatableInterface, JWTUserInterface
{
    private $username;
    private $password;
    private $salt;
    private $roles;
    private $nom;
    private $prenom;

    public function __construct($username, array $roles=null )
    {
        $this->username = $username;
        $this->roles = $roles;
    }

    /**
     * Retourne le Role d'un utilisateur
     * @return Array de roles
     */
    public function getRoles()
    {
        return $this->roles;
    }

    /**
     * Définis les roles d'un utilisateur
     * @param Array de roles $roles
     */
    public function setRoles($roles)
    {
        $this->roles = $roles;
    }

    /**
     * Retourne le password d'un utilisateur
     * @return String
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Définit le role d'un utilisateur
     * @param String $password
     */
    public function setPassword($password)
    {
        $this->password = $password;
    }    

    /**
     * Définit le grain de sable du password de l'utilisateur
     * @param String $salt
     * @return String
     */
    public function setSalt($salt)
    {
        return $this->salt = $salt;
    }
    
    /**
     * Définit le grain de sable du password de l'utilisateur
     * @return String
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * Retourne le username (email) de l'utilisateur
     * @return String
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Définit le nom de famille d'un utilisateur
     * @param String $nom
     */
    public function setNom($nom)
    {
        $this->nom = $nom;
    }       
    
    /**
     * Retourne le nom de famille d'un utilisateur
     * @return String
     */
    public function getNom()
    {
        return $this->nom;
    }
    
    /**
     * Définit le prénom d'un utilisateur
     * @param String $prenom
     */
    public function setPrenom($prenom)
    {
        $this->prenom = $prenom;
    }
    
    /**
     * Retourne le prénom d'un utilisateur
     * @return String
     */
    public function getPrenom()
    {
        return $this->prenom;
    }

    /**
     * Fonction non utilisée
     */
    public function eraseCredentials(){}

    /**
     * Va créer l'utilisateur
     * @param String $username email de l'utilisateur
     * @param array $payload (nom et prénom de l'tilisateur)
     * @return \self
     */
    public static function createFromPayload($username, array $payload)
    {
        return new self($username, $payload['roles']);
    }
    

    public function isEqualTo(UserInterface $user)
    {
        if (!$user instanceof WebserviceUser) {
            return false;
        }
        
        if ($this->roles !== $user->getRoles()) {
            return false;
        }
        
        if ($this->username !== $user->getUsername()) {
            return false;
        }
        return true;
    }
}

```

and here is my provider

```
<?php

// src/App/Security/User/WebserviceUserProvider.php
namespace App\Security\User;

use App\Security\User\WebserviceUser;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;


class WebserviceUserProvider implements UserProviderInterface
{ 
    /**
     * Crée un utilisateur avec pour premier attribut son email puis le renvoie
     * @param String $username
     * @return WebserviceUser
     */
    public function loadUserByUsername($username)
    {
        return new WebserviceUser($username);
    }
    
    /**
     * Fonction inconnue
     * @param UserInterface $user
     * @return WebserviceUser
     * @throws UnsupportedUserException
     */
    public function refreshUser(UserInterface $user)
    {
        if (!$user instanceof WebserviceUser) {
            throw new UnsupportedUserException(
                sprintf('Instances of "%s" are not supported.', get_class($user))
            );
        }
        return $this->loadUserByUsername($user->getUsername());
    }
    
    /**
     * Fonction inconnue
     * @param type $class
     * @return type
     */
    public function supportsClass($class)
    {
        return WebserviceUser::class === $class;
    }
}

```

Do you know how can i debug this  i did not had that issue before

**Comment by maximebourdel** [comment]
after looking to the profiler, it looks like it does not detect the services i implemented.
Here is my 

service.yaml
```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    lexik_jwt_authentication.encoder.default:
        class: Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder
        public: true

    #Utilisé pour le GUARD et s'assurer que le token est OK
    app.jwt_token_authenticator:
        class: App\Security\Guard\JWTTokenAuthenticator
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        calls:
            - [setDoctrine, ["@doctrine.orm.entity_manager"]]
        public: true
        autowire: true
        autoconfigure: false

    #Gère le payload (ce qui sera inclu dans le token JWT)
    acme_api.event.jwt_created_listener:
        class: App\EventListener\JWTCreatedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
        public: true
        autowire: true
        autoconfigure: true
```
        

and my security.yaml
```

security:

    #Le provider utilisé est celui de lexik_jwt avec WebserviceUser
    providers:
        jwt:
            lexik_jwt:
                class: App\Security\User\WebserviceUser

    #L'encoder est en plaintext pour Kayoo
    encoders:
        App\Security\User\WebserviceUser: plaintext

    #Définition des roles
    role_hierarchy:
        ROLE_ADMIN:    ROLE_USER

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - app.jwt_token_authenticator
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter: username
                password_parameter: password

        #Pour les users authentifiés
        auth:
            pattern:   ^/auth
            guard:
                authenticators:
                    - lexik_jwt_authentication.security.guard.jwt_token_authenticator
        #Pour les admins 
        admin:
            pattern:   ^/admin
            guard:
                authenticators:
                    - lexik_jwt_authentication.security.guard.jwt_token_authenticator
    
    #Définition des droits pour les url
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth,   roles: ROLE_USER }
        - { path: ^/admin,  roles: ROLE_ADMIN }

```

**Comment by maximebourdel** [comment]
Hi,

Thank you for responding :)

By not detecting I mean when i mean I've put an exception in my getCredentials but it does not trigger 'STOP' anymore whereas in my previous versions it used to trigger 

I precise i am trying to use flex in my 3.4 and i did not have it in my previous.

```
    public function getCredentials(Request $request)
    {
        throw new \InvalidArgumentException('STOP');
        $username = $request->request->get('username');
        $password = $request->request->get('password');

        if ($username == null || $password == null){
            throw new \InvalidArgumentException('Merci de renseigner les paramètres d\'authentification');
        }
        
        return array(
            'username' => $username,
            'password' => $password
        );
    }
```


This is the commant  i am trying
curl -X POST -H "Content-Type: application/json" http://127.0.0.1/carPool/api/public/index.php/login_check -d '{"username":"myuser@user.com","password":"mypassword"}'

is this ok ?

`{"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"Warning: hash_equals(): Expected known_string to be a string, null given","class":"Symfony\\Component\\Debug\\Exception\\ContextErrorException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Core\/Encoder\/BasePasswordEncoder.php","line":84,"args":[]},{"namespace":"Symfony\\Component\\Security\\Core\\Encoder","short_class":"BasePasswordEncoder","class":"Symfony\\Component\\Security\\Core\\Encoder\\BasePasswordEncoder","type":"->","function":"comparePasswords","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Core\/Encoder\/PlaintextPasswordEncoder.php","line":57,"args":[["null",null],["string","mypassword"]]},{"namespace":"Symfony\\Component\\Security\\Core\\Encoder","short_class":"PlaintextPasswordEncoder","class":"Symfony\\Component\\Security\\Core\\Encoder\\PlaintextPasswordEncoder","type":"->","function":"isPasswordValid","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Core\/Authentication\/Provider\/DaoAuthenticationProvider.php","line":64,"args":[["null",null],["string","mypassword"],["null",null]]},{"namespace":"Symfony\\Component\\Security\\Core\\Authentication\\Provider","short_class":"DaoAuthenticationProvider","class":"Symfony\\Component\\Security\\Core\\Authentication\\Provider\\DaoAuthenticationProvider","type":"->","function":"checkAuthentication","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Core\/Authentication\/Provider\/UserAuthenticationProvider.php","line":84,"args":[["object","App\\Security\\User\\WebserviceUser"],["object","Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"]]},{"namespace":"Symfony\\Component\\Security\\Core\\Authentication\\Provider","short_class":"UserAuthenticationProvider","class":"Symfony\\Component\\Security\\Core\\Authentication\\Provider\\UserAuthenticationProvider","type":"->","function":"authenticate","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Core\/Authentication\/AuthenticationProviderManager.php","line":76,"args":[["object","Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"]]},{"namespace":"Symfony\\Component\\Security\\Core\\Authentication","short_class":"AuthenticationProviderManager","class":"Symfony\\Component\\Security\\Core\\Authentication\\AuthenticationProviderManager","type":"->","function":"authenticate","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Http\/Firewall\/UsernamePasswordFormAuthenticationListener.php","line":100,"args":[["object","Symfony\\Component\\Security\\Core\\Authentication\\Token\\UsernamePasswordToken"]]},{"namespace":"Symfony\\Component\\Security\\Http\\Firewall","short_class":"UsernamePasswordFormAuthenticationListener","class":"Symfony\\Component\\Security\\Http\\Firewall\\UsernamePasswordFormAuthenticationListener","type":"->","function":"attemptAuthentication","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Http\/Firewall\/AbstractAuthenticationListener.php","line":140,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]},{"namespace":"Symfony\\Component\\Security\\Http\\Firewall","short_class":"AbstractAuthenticationListener","class":"Symfony\\Component\\Security\\Http\\Firewall\\AbstractAuthenticationListener","type":"->","function":"handle","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security-bundle\/Debug\/WrappedListener.php","line":46,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Bundle\\SecurityBundle\\Debug","short_class":"WrappedListener","class":"Symfony\\Bundle\\SecurityBundle\\Debug\\WrappedListener","type":"->","function":"handle","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security-bundle\/Debug\/TraceableFirewallListener.php","line":35,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Bundle\\SecurityBundle\\Debug","short_class":"TraceableFirewallListener","class":"Symfony\\Bundle\\SecurityBundle\\Debug\\TraceableFirewallListener","type":"->","function":"handleRequest","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security\/Http\/Firewall.php","line":61,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"],["object","Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator"]]},{"namespace":"Symfony\\Component\\Security\\Http","short_class":"Firewall","class":"Symfony\\Component\\Security\\Http\\Firewall","type":"->","function":"onKernelRequest","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/security-bundle\/EventListener\/FirewallListener.php","line":48,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Bundle\\SecurityBundle\\EventListener","short_class":"FirewallListener","class":"Symfony\\Bundle\\SecurityBundle\\EventListener\\FirewallListener","type":"->","function":"onKernelRequest","file":null,"line":null,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"],["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"","short_class":"","class":"","type":"","function":"call_user_func","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/event-dispatcher\/Debug\/WrappedListener.php","line":104,"args":[["array",[["object","Symfony\\Bundle\\SecurityBundle\\Debug\\TraceableFirewallListener"],["string","onKernelRequest"]]],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"],["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"WrappedListener","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"->","function":"__invoke","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":212,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"],["string","kernel.request"],["object","Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"doDispatch","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":44,"args":[["array",[["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"]]],["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","function":"dispatch","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/event-dispatcher\/Debug\/TraceableEventDispatcher.php","line":139,"args":[["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"->","function":"dispatch","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":127,"args":[["string","kernel.request"],["object","Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handleRaw","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":68,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"->","function":"handle","file":"\/var\/www\/html\/carPool\/api\/vendor\/symfony\/http-kernel\/Kernel.php","line":202,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"->","function":"handle","file":"\/var\/www\/html\/carPool\/api\/public\/index.php","line":37,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]}]}}`

Maybe i am doing wrong in my security ?

```
security:

    #Le provider utilisé est celui de lexik_jwt avec WebserviceUser
    providers:
        jwt:
            lexik_jwt:
                class: App\Security\User\WebserviceUser

    #L'encoder est en plaintext pour Kayoo
    encoders:
        App\Security\User\WebserviceUser: plaintext

    #Définition des roles
    role_hierarchy:
        ROLE_ADMIN:    ROLE_USER

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            guard:
                authenticators:
                    - app.jwt_token_authenticator
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter: username
                password_parameter: password
```

**Comment by chalasr** [comment]
The content type of your request is json, while your authenticator seems to expect form data, try changing your curl command to: `curl -X POST -H http://127.0.0.1/carPool/api/public/index.php/login_check -d username=myuser@user.com -d password=mypassword`.

Also you have both `form_login` and `app.jwt_token_authenticator` set on the same firewall, both looking for a `username` and `password` parameters, that looks weird to me, I'm note sur to understand the logic. What does your `app.jwt_token_authenticator` do? Does it deliver tokens from `username+password` couples? Because it's exactly what the `form_login` in place should do (should one be removed?).

**Comment by maximebourdel** [comment]
Got 
```
curl -X POST -H http://127.0.0.1/carPool/api/public/index.php/login_check -d username=myuser@user.com -d password=mypassword
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

I tried removing  -H and i have the same outpout than before : 
`Warning: hash_equals(): Expected known_string to be a string, null given","class":"Symfony\\Component\\Debug\\Exception\\ContextErrorException`


The reason why I implemented the app.jwt_token_authenticator was to call an API checking for return code in a  checkCredentials function so i can validate the password if the code return = 0

What i do not undertand is that it was working in my previous version.

```

    #Utilisé pour le GUARD et s'assurer que le token est OK
    app.jwt_token_authenticator:
        class: App\Security\Guard\JWTTokenAuthenticator
        parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
        calls:
            - [setDoctrine, ["@doctrine.orm.entity_manager"]]
        public: true
        autowire: true
        autoconfigure: false
```
(I let the ` throw new \InvalidArgumentException('STOP');`
just for the exemple)

```

<?php

namespace App\Security\Guard;

use Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator as BaseAuthenticator;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\HttpFoundation\Request;
use Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;

/**
 * Représente tous les appels concernant l'identification d'un utilisateur (login)
 * @package App\Security\Guard
 * @author Maxime Bourdel
 */
class JWTTokenAuthenticator extends BaseAuthenticator
{
    private $doctrines;
    
    /**
     * Injecte doctrine via les services
     * @param type $doctrine
     */
    public function setDoctrine($doctrine){
        $this->doctrines = $doctrine;
    }
    
    /**
     * Etape 1 
     * Récupère ce que rentre l'utilisateur et le retourne sous forme de tableau
     * @param Request $request
     * @throws \InvalidArgumentException
     * @return Array
     * {@inheritdoc}
     */
    public function getCredentials(Request $request)
    {
        //throw new \InvalidArgumentException('STOP');
        $username = $request->request->get('username');
        $password = $request->request->get('password');

        if ($username == null || $password == null){
            throw new \InvalidArgumentException('Merci de renseigner les paramètres d\'authentification');
        }
        
        return array(
            'username' => $username,
            'password' => $password
        );
    }

    /**
     * Etape 2
     * Récupère l'utilisateur
     * @param type $credentials
     * @param UserProviderInterface $userProvider
     * @return type
     * {@inheritdoc}
     */
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $username = $credentials['username'];
        return $userProvider->loadUserByUsername($username);
    }

    /**
     * Etape 3
     * Vérifie le mot de passe (password) de l'utilisateur est correct via l'API Kayoo
     * @param type $credentials
     * @param UserInterface $user
     * @return boolean return true si mdp ok
     * @throws BadCredentialsException
     * {@inheritdoc}
     */
    public function checkCredentials($credentials, UserInterface $user)
    {
        // Paramètres POST pour Kayoo
        $values= 'user='.$user->getUserName();
        $values.= '&password='.$credentials['password'];
        $values.= '&rememberMe=true';
        $values.= '&json=true';
        
        $json_response = $this->callKayooAPI($values);

        if( $json_response['error'] == '0'){
            $user->setPassword($credentials['password']);
            $user->setNom($json_response['usr_info']['last_name']);
            $user->setPrenom($json_response['usr_info']['first_name']);            
            $user->setRoles(['ROLE_USER']);
            //Arrivé ici = mdp ok donc on valide cette étape
            return true;
        }
        
        //Mauvaises authentification (email ou mdp)
        throw new BadCredentialsException();
    }
    
    /**
     * Etape 4
     * L'utilisateur est OK, on crée son token
     * @param UserInterface $user
     * @param type $providerKey
     * @return JWTUserToken
     * {@inheritdoc}
     */
    public function createAuthenticatedToken(UserInterface $user, $providerKey)
    {
        return new JWTUserToken(['ROLE_USER'], $user);
    }
    
    /**
     * Appel à l'API Kayoo
     * @param type $values valeurs en GET (ex : https://www.kayoo.com/_/Layout_Common_Login/login2?user=maxime.bourdel@businessdecision.com&password=toto&rememberMe=true&json=true)
     * @return type json exemple en cas d'erreur {"error":800,"message":"Identifiant ou mot de passe incorrect","app_info":{"v":{"web_app":"1.7.20160307","mobile_app":"3.0"}}}
     */
    private function callKayooAPI($values){
        
        $url='https://www.kayoo.com/_/Layout_Common_Login/login2';
        
        //Appel à l'API Kayoo
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/x-www-form-urlencoded'));
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $values);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        $response  = curl_exec($ch);
        curl_close ($ch);
        
        return json_decode($response, true);
    }
}

```
