### ISSUE TITLE
After upgrade to 2.5.4 this message appear

### ISSUE THREAD

**Issue by suiXz** [lexik/LexikJWTAuthenticationBundle#563]
The "Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\DefaultJWSProvider" class is deprecated since version 2.5 and will be removed in 3.0. Use "Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\LcobucciJWSProvider" or create your own "Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\JWSProviderInterface" implementation instead.

How can we fix that ?

At the moment we rollback to 2.5.3

**Comment by chalasr** [comment]
It seems you are using the deprecated DefaultEncoder somehow. Can you show your config? Do you have something like:
```yaml
lexik_jwt_authentication:
    encoder:
        service: lexik_jwt_authentication.encoder.default
```
? 
Or are you using the encoder service into your code?
