### ISSUE TITLE
Unable to load an user with property ....

### ISSUE THREAD

**Issue by yooouuri** [lexik/LexikJWTAuthenticationBundle#580]
lexik_jwt_authentication.yaml
```yaml
lexik_jwt_authentication:
    user_identity_field: mijn_pidz_id
```

security.yaml
```yaml
security:
    firewalls:
    # ...

    api:
        pattern: ^/api
        stateless: true
        anonymous: false
        guard:
            authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator
```

I create my token programmatically

```php
$user = $userRepository->findOneByMijnPidzId($mijnPidzId);

if (null === $user) {
    $user = new User($mijnPidzId, ['ROLE_USER']);

    $userRepository->save($user);
}

$token = $JWTManager->create($user);
```

My database contains a user with `mijn_pidz_id`

<img width="154" alt="image" src="https://user-images.githubusercontent.com/12934957/48132364-9143a700-e293-11e8-9dc5-b99ec698467b.png">

The payload contains a `mijn_pidz_id`

<img width="276" alt="image" src="https://user-images.githubusercontent.com/12934957/48132431-cb14ad80-e293-11e8-9340-22320c12171f.png">

When I try to access a protected url (like /api/blabla), I get the following error

```
{
    "code": 401,
    "message": "Unable to load an user with property \"mijn_pidz_id\" = \"5353\". If the user identity has changed, you must renew the token. Otherwise, verify that the \"lexik_jwt_authentication.user_identity_field\" config option is correctly set."
}
```
