### ISSUE TITLE
How make regular auth and lexikJwt auth side-by-side?

### ISSUE THREAD

**Issue by silasrm** [lexik/LexikJWTAuthenticationBundle#59]
Hi,

My app is using a regular authentication (with FOSUserBundle), and I desire add support to auth on my API with LexikJWT, for authentication of users using others apps connected to my app.

How I make this?

Thk's.

**Comment by slashfan** [comment]
Hi,

Can you describe more precisely the workflow you want to make ? Do you simply want to add the JWT authentication to the regular authentication ? If so there shouldn't be a problem, you can mix it with FOSUserBundle by using the same provider. Or do you want your regular authenticated app users to be automatically authenticated on the API as well ?

Regards.

**Comment by silasrm** [comment]
Hi,

My app is using FOSUserBundle to regular authentication. This is ok. But, I'll add an API and my users will make login in my external app (mobile, for example) using the same user and password.

Then the regular authentication, with FOSUserBundle, exists and LexikJWT authentication also exists, but only in API.

Thk's

**Comment by slashfan** [comment]
Hi,

Look at [the configuration section of the documentation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#configuration) or [the security configuration of the sandbox](https://github.com/slashfan/LexikJWTAuthenticationBundleSandbox/blob/master/app/config/security.yml). Add the flollowing lines to your security.yml (of course rename the firewalls if there is a conflict with your current configuration).

```yml

firewalls:
    # your current configuration for fosuserbundle
    # ... 
    api_login:
        pattern:  ^/api/login
        stateless: true
        anonymous: true
        form_login:
            check_path: /api/login_check
            require_previous_session: false
            username_parameter: username
            password_parameter: password
            success_handler: lexik_jwt_authentication.handler.authentication_success
            failure_handler: lexik_jwt_authentication.handler.authentication_failure
    api:
        pattern:   ^/api
        stateless: true
        lexik_jwt: ~

access_control:
    # ...
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

```

You might have to configure the user provider, and if you use another fields than `username` to identify your users you can customize it under the `user_identity_field` property of [the bundle configuration](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md).

Hope it helps.
