### ISSUE TITLE
Authenticated anonymously not work

### ISSUE THREAD

**Issue by JellyBellyDev** [lexik/LexikJWTAuthenticationBundle#60]
Hi man,
good work with this bundle. I cloned and try the sandbox: https://github.com/slashfan/LexikJWTAuthenticationBundleSandbox
but i don't understand why if i change access control setting:

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/pages, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

and i go to http://localhost:8000/angular-demo/index.html 
I continue to see the authentication request.

P.S. in PageController.php (getPagesAction function) i comment these lines:

    if (!$this->get('security.context')->isGranted('ROLE_USER')) {
        throw new AccessDeniedException();
    }

Thanks

**Comment by slashfan** [comment]
Hi,

Have you tried adding `anonymous: true` to the `api` firewall configuration ? Like this : 

```yml
api:
    pattern:   ^/api
    stateless: true
    anonymous: true
    lexik_jwt: 
        # ... rest of your config
```

It worked for me in the sandbox.
