### ISSUE TITLE
Unable to find _controller when accessing /login_check

### ISSUE THREAD

**Issue by adrienlefebvre92** [lexik/LexikJWTAuthenticationBundle#603]
Hello,

I followed the Sf4 sandbox to install JWT Auth, but still I have this response :

> 2019-01-03T18:39:27+01:00 [info] Matched route "login_check".
2019-01-03T18:39:27+01:00 [info] Populated the TokenStorage with an anonymous Token.
2019-01-03T18:39:27+01:00 [warning] Unable to look for the controller as the "_controller" parameter is missing.
2019-01-03T18:39:27+01:00 [critical] Uncaught Exception: Unable to find the controller for path "/login_check". The route is wrongly configured.
[Thu Jan  3 18:39:27 2019] 127.0.0.1:48564 [404]: /login_check

When I try this command : 

> curl -X POST -H "Content-Type: application/json" http://localhost:8000/login_check -d '{"email":"johndoe@test.fr","password":"test"}'

Here is my routes.yaml : 

```
index:
    path: /
    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\DefaultController::register
    methods: POST

api:
    path: /api
    controller: App\Controller\DefaultController::api

login_check:
    path:     /login_check
    methods:  [POST]

```

And here is my security.yaml : 
```

security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true

        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                username_path: email
                password_path: password
        api:
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```

I am using PHP7.2 and Symfony 4.2.
Does someone know how to correct this error ?

Thanks,

Adrien

**Comment by Wulfu** [comment]
I can confirm same issue on php 7.2 symfony 4.2.
Still trying to figure this out.
My config:
```
security:
    encoders:
        App\Entity\User: bcrypt
    providers:
        database:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

```

**Comment by Wulfu** [comment]
@adrienlefebvre92 try removing section:
```
main:
            anonymous: true
```
this was the problem in my case

**Comment by kemicofa** [comment]
While I'm not getting the error via the curl request, I am getting a similar error when running tests as mentioned in #610 

Here is my test.log

```bash
[2019-01-29 21:30:24] request.INFO: Matched route "api_admin_login". {"route":"api_admin_login","route_parameters":{"_route":"api_admin_login"},"request_uri":"http://localhost/api/admin/login_check","method":"POST"} []
[2019-01-29 21:30:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-01-29 21:30:24] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
```

Though when it matches the route, `"request_uri":"http://localhost/api/admin/login_check"` looks fishy.

**Comment by sigriffiths** [comment]
The following works for me in tests using WebTestCase.

```php
    /**
     * Generate an authenticated client with a correct bearer token
     *
     * @param string $username
     * @param string $password
     * @return \Symfony\Bundle\FrameworkBundle\Client
     */
    protected function createAuthenticatedClient($username = '', $password = '')
    {
        $client = static::createClient();
        $client->request(
            'POST',
            '/api/login_check',
            [],
            [],
            ['CONTENT_TYPE' => 'application/json'],
            json_encode([
                'username' => $username,
                'password' => $password,
            ])
        );

        $data = json_decode($client->getResponse()->getContent(), true);

        $client = static::createClient();
        $client->setServerParameter('HTTP_Authorization', sprintf('Bearer %s', $data['token']));

        return $client;
    }
```

**Comment by shreelathags** [comment]
Got around it by moving the 'main' block after all other firewalls.
main:
            anonymous: true

**Comment by PaulCombal** [comment]
I had the same issue at some point but remember fixing it. I simply forgot the HTTP header `content-type: application/json` in the request headers.

**Comment by eissasoubhi** [comment]
You need to make sure that you are sending a **POST** request with **HEADER** `'content-type': 'application/json'` and the data must be in **JSON**

**Comment by chalasr** [comment]
Closing as explained. Please open a PR if you think you can improve the documentation.

**Comment by antond1990** [comment]
I have the same issue and if I remove the part `anonymous: true` I get an 502 Bad Gateway error.

**Comment by EvKoh** [comment]
Try to change order of your firewalls, example :
1 - dev
2 - login
3 - api
4 - main

**Comment by mghabdo** [comment]
i'm geting the same error
i tried all solutions

if i add  
`main
anonymous: true` i got this : 

**The authenticator manager no longer has "anonymous" security. Please remove this option under the "main" firewall.**

and when comment it :

**Unable to find the controller for path "/api/login_check". The route is wrongly configured.**

**Comment by Pixman** [comment]
Hello @mghabdo, anonymous was removed, you can read this in the doc.
https://symfony.com/doc/current/security/authenticator_manager.html#authenticators-removed-anonymous

**Comment by Eric-ciccotti** [comment]
I faced to the same issue,
The solution in my case was to read the Symfony documentation provided by @Pixman (link just above)

> The new system is backwards compatible with the current authentication system, with some exceptions that will be explained in this article:
> 
> Anonymous users no longer exist
> Configuring the authentication entry point is required when more than one authenticator is used
> The authentication providers are refactored into Authenticators
> 

Here my files :

Security.yaml
```
security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                      
    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

```
routes.yaml
```
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check
  methods:  [POST]
```

i just removed the provider, In my case User is an entity so its not mendoraty according to symfony documentation, don't know why but that the reason of the "Unable to find _controller when accessing /login_check" for me.

```
main:
            lazy: true
            provider: app_user_provider
```
remove  : **provider: app_user_provider**
> If your User class is an entity, you don’t need to do anything else. But if your class is not an entity, then make:user will also have generated a UserProvider class that you need to finish. Learn more about user providers here: User Providers.

I'm a newbie in PHP, I hope it could help someone.
