### ISSUE TITLE
Error: Unable to find the controller for path "/api/admin/login_check" during functional tests but works with cURL

### ISSUE THREAD

**Issue by kemicofa** [lexik/LexikJWTAuthenticationBundle#610]
### Description

When I'm doing the request to my symfony server running on `http://localhost:8000/api/admin/login_check` it returns the desired token.

However, when I do it with the functional tests I get the following error:

> Error: Unable to find the controller for path \"\/api\/admin\/login_check\". The route is wrongly configured. 

I also went through the [functional test docs](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/3-functional-testing.md).

### Test method:

```php
    public function testLogin(){

        $client = static::createClient();
        $client->request('POST', '/api/admin/login_check', [], [],
            [
                'Content-Type' => 'application/json',
                'Accept' => 'application/json'
            ],
            json_encode([
                'email' => 'email@test.com',
                'password' => 'qwerty123'
            ])
        );

        $this->assertEquals(200, $client->getResponse()->getStatusCode());

    }
```

### Routes:

```yaml
# Admin Routes
api_admin_login_check:
    path: /api/admin/login_check
    methods:  [POST]
```

### security:

```yaml
security:

# more configs here

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_admin:
            pattern: ^/api/admin/login
            stateless: true
            anonymous: true
            json_login:
                username_path: email
                provider: app_admin_provider
                check_path: /api/admin/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        admin_api:
            pattern: ^/api/admin
            stateless: true
            provider: app_admin_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/admin/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

What am I doing wrong?

Also any pointers as to why I'm getting a `401 JWT Token not found` for my `/api/admin/register` even if I've put it in my access_control, would be nice.

[SO Question](https://stackoverflow.com/questions/54407480/error-unable-to-find-the-controller-for-path-login-check-the-route-is-wrong)

**Comment by kemicofa** [comment]
Went through my logs and something fishy is effectively happening. When I do a postman request everything works well. Here is the logs for the request:

```bash
[2019-01-29 21:36:19] request.INFO: Matched route "api_admin_login". {"route":"api_admin_login","route_parameters":{"_route":"api_admin_login"},"request_uri":"https://localhost:8000/api/admin/login_check","method":"POST"} []
[2019-01-29 21:36:19] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.password AS password_3 FROM admin t0 WHERE t0.email = ? LIMIT 1 ["email@test.com"] []
[2019-01-29 21:36:19] security.INFO: User has been authenticated successfully. {"username":null} []
```

However, during my test here are the logs:

```bash
[2019-01-29 21:30:24] request.INFO: Matched route "api_admin_login". {"route":"api_admin_login","route_parameters":{"_route":"api_admin_login"},"request_uri":"http://localhost/api/admin/login_check","method":"POST"} []
[2019-01-29 21:30:24] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2019-01-29 21:30:24] request.WARNING: Unable to look for the controller as the "_controller" parameter is missing. [] []
```

As can be noticed that the request_uri in both requests don't match. In fact, the second one doesn't make any sense as it is bound to fail:

`"request_uri":"http://localhost/api/admin/login_check"
`

Any ideas as why the request_uri looks like that? Is it possible there is a configuration issue with my tests?

**Comment by kemicofa** [comment]
For the 401 error (on `/api/register`) I just simply needed to add this above my `login_admin:` 
```yaml
        register_admin:
            pattern: ^/api/admin/register
            anonymous: true
            stateless: true
```

Which is weird since I've already specified it in my Access Control.

I'm still getting the 404 not found error when accessing login_check. I've been able to get a couple of facts straight for the `test env`:

@chalasr I've cloned your project and was able to reproduce the issue.
https://github.com/kemicofa/lexik-jwt-authentication-sandbox

When the project is installed and run, there is a 404 error when running test. However, retrieving the token via curl works perfectly fine.
