### ISSUE TITLE
Another Unable to find the controller for path "/login_check". The route is wrongly configured

### ISSUE THREAD

**Issue by michaelrachlitz** [lexik/LexikJWTAuthenticationBundle#613]
So obviously, there is a lot of issues already with this error message. Only a few has been addressed.

I feel I have been through all the issues now, and I have attempted many different configurations to see if I could get a working result, with no luck.

Error message
```
Unable to find the controller for path "/login_check". The route is wrongly configured
```

```
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER
    providers:
        entity_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        # Removed main entirely as suggested in a different issue, with no luck. Also attempted to move dev
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login_check
                # Attempted with specific username_path and password_path config as well as without
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern:  ^/register
            stateless: true
            anonymous: true
        api:
            pattern:   ^/v1
            stateless: true
            anonymous: true
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/v1, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }

```

Creating users with /register works fine. However, all users created through register returns the error message regarding a missing controller. However, that only occures if the username/password credentials is correct, if I type in a wrong password, it returns bad credentials as expected.

**Comment by kemicofa** [comment]
Could you provide your routes.yaml ? Also what version of symfony are you using? Do you have a github project that reproduces this problem? Is this during the dev environment?

**Comment by michaelrachlitz** [comment]
@kemicofa 

```
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api:
  path: /v1
  controller: App\Controller\AuthController::api

login:
  path: /login
  controller: App\Controller\AuthController::login
```

Done several new attempts though. At this moment, I am manually validating logins and I removed the /login_check. Manually creating tokens also.

Using Symfony 4.
Environment: Dev as well as prod.
