### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by Xeyos88** [lexik/LexikJWTAuthenticationBundle#630]
Hi guys,
i have a problem with the configuration, because at each api called lexik run ever the start() function of guard.

The login works fine, lexik return the token and the client generates the nex request in the correct way (in the header i have **Authorization**: bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSU...)
But the response is ever erro auth required.

This is my configuration:
JwtTokenAuthenticator.php
```php
<?php

namespace App\Security;


use App\Entity\UserOperator;
use Doctrine\ORM\EntityManagerInterface;
use Lexik\Bundle\JWTAuthenticationBundle\Encoder\JWTEncoderInterface;
use Lexik\Bundle\JWTAuthenticationBundle\TokenExtractor\AuthorizationHeaderTokenExtractor;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Core\Exception\CustomUserMessageAuthenticationException;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;
use Symfony\Component\Security\Guard\AbstractGuardAuthenticator;

class JwtTokenAuthenticator extends AbstractGuardAuthenticator
{

    private $jwtEncoder;
    private $em;
    private $credential;
    public function __construct(JWTEncoderInterface $jwtEncoder, EntityManagerInterface $em)
    {
        $this->jwtEncoder = $jwtEncoder;
        $this->em = $em;
    }

    public function supports(Request $request)
    {
        // TODO: Implement supports() method.
    }

  
    public function getCredentials(Request $request)
    {
        $extractor = new AuthorizationHeaderTokenExtractor(
            'Bearer',
            'Authorization'
        );
        $token = $extractor->extract($request);
        if (!$token) {
            return;
        }
        return $token;
    }

   
    public function getUser($credentials, UserProviderInterface $userProvider)
    {
        $data = $this->jwtEncoder->decode($credentials);
        $this->credential = $data['username'];

        if ($data === false) {
            throw new CustomUserMessageAuthenticationException('Invalid Token');
        }
        $username = $data['username'];

        return $this->em
            ->getRepository(UserOperator::class)
            ->findOneBy(['name' => $username]);
    }


    public function checkCredentials($credentials, UserInterface $user)
    {
        return true;
    }

    
    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        // TODO: Implement onAuthenticationFailure() method.
    }

    
    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        // TODO: Implement onAuthenticationSuccess() method.
    }

   
    public function supportsRememberMe()
    {
        return false;
    }

    public function start(Request $request, AuthenticationException $authException = null)
    {
        return new JsonResponse([
            'error' => 'auth required'
        ], 401);
    }

}
```
services.yaml
```yaml
services:
    lexik_jwt_authentication:
          class: App\Security\JwtTokenAuthenticator
          autowire: true
```
security.yaml
```yaml 
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        entity_provider:
            entity:
                class: App\Entity\OperatorUser
                property: username

    encoders:
        App\Entity\OperatorUser:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern:   ^/
            anonymous: true
            stateless: true
            provider: entity_provider
            guard:
                authenticators:
                - 'lexik_jwt_authentication'
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

```
lexit_jwt_authentication.yaml
```yaml
lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '******'
    token_ttl: 86400
    user_identity_field: username

    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
```
Route called:
```php
/**
     * @Route("/operatorDashboard", name="operator_dashboard", methods={"POST", "GET"})
     * @Security("is_granted('role_admin')")
     * @param Request $request Params with dashboard information
     * @return JsonResponse the information required
     */
```
Why is ever called a start function?
