### ISSUE TITLE
Ignoring token in header for public routes

### ISSUE THREAD

**Issue by napravicukod** [lexik/LexikJWTAuthenticationBundle#640]
Public routes are managed through `access_control` within security.yaml config.
Still, when requesting a public route with a token in header, token is being validated.
It seems that token should be ignored.

What would be the best way to accomplish this?

I did it by creating a `firewall` entry like this:
```
api_public_get:
    pattern: ^/api/(categories|offers|images)
    methods: [GET]
    security: false
```
But this seems unmanageable when dealing with many routes.
Is there a more elegant way to tackle this?
