### ISSUE TITLE
FOSUser + LexikJWT still returning 401 "Bad Credentials"

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [lexik/LexikJWTAuthenticationBundle#66]
Hello,
After reading and trying all fixes found in here trying to get LexikJWT and FOSUser working together, I finally create my own new issue because I could really not find a way, it's still returning 401 "Bad Credentials"...

I need a "backend admin" login (which is working)  independent from my API login which will be used in an hybrid app.

Here is my security.yml :
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            pattern: ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:        /admin/logout
                target:      /admin
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path:     /api/login_check
                username_parameter: username
                password_parameter: password
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            provider: fos_userbundle
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                throw_exceptions:        false
                create_entry_point:      true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY, ROLE_API, ROLE_ADMIN] }
```
If someone has any idea why I cannot manage to get this working, I thank you in advance.

I'm trying using Sandbox's AngularJS implementation and Curl CLI, they both return 401 Bad Credentials..

**Comment by slashfan** [comment]
Hi,

I see you are using the `fos_user.user_provider.username_email` user provider. Are the `email` and `username` values equal in your user entities ? If they are different, check the [configuration reference](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#configuration-reference-1) and try to change the `user_identity_field` to `email` in the bundle configuration.

Let me know if it helps.

**Comment by Yonn-Trimoreau** [comment]
Thank you for answering me so quickly.
I've overriden the FOSUser's setEmail function in my entity class to make them the same. As described [here](http://openclassrooms.com/forum/sujet/symfony-supprimer-username-fosuserbundle#message-85362128) : 
```
public function setEmail($email){
    parent::setEmail($email);
    $this->setUsername($email);
}
```
I checked in database, they are the same. And I tried both `email` and `username` in `user_identity_field` parameter

**Comment by vialcollet** [comment]
Hi !  I am having the exact same issue.
I am also using FOSUserBundle.
After getting the token, any call to the api returns a 401 Bad Credentials. 

I am using an Angular App and I have the exact same code as in the [Sandbox Bundle](https://github.com/slashfan/LexikJWTAuthenticationBundleSandbox).

Here is the debug from Symfony : 

```
security.INFO: Authentication exception occurred; redirecting to authentication entry point (A Token was not found in the SecurityContext.) 
security.DEBUG: Calling Authentication entry point
```

Here is my security.yml:

```
# app/config/security.yml
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email


    firewalls:
        dev:
            pattern: ^/{_{profiler|wdt}}/
            security: false
            switch_user: true
        api_login:
            pattern:    ^/api/login
            stateless:  true
            anonymous:  true
            logout:     false
            provider:   fos_userbundle
            form_login:
                check_path:               api_login_check
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:    ^/api
            stateless:  true
            provider:   fos_userbundle
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer
        main:
            pattern: .*
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            switch_user:  true

    role_hierarchy:
        ROLE_DELEGATION:        [ROLE_USER]
        ROLE_EXPORT:            [ROLE_USER]
        ROLE_USER_ADMIN:        [ROLE_USER]
        ROLE_LIST_ADMIN:        [ROLE_USER]
        ROLE_IMPORT:            [ROLE_USER]
        ROLE_MOBILE:            [ROLE_USER]
        ROLE_ADMIN:             [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/$, role: ROLE_USER}
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/contacts, role: ROLE_USER }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/entites, role: ROLE_USER }
        - { path: ^/export, role: ROLE_EXPORT }
        - { path: ^/titres, roles: ROLE_ADMIN }
        - { path: ^/categories, roles: ROLE_ADMIN }
        - { path: ^/services, roles: ROLE_ADMIN }
        - { path: ^/groupes, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/imports, roles: ROLE_IMPORT }
        - { path: ^/utilisateurs, roles: ROLE_USER_ADMIN }
        - { path: ^/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/group, roles: ROLE_USER_ADMIN }
#        JWT SETUP
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: ROLE_MOBILE }
```

**Comment by vialcollet** [comment]
@Yonn-Trimoreau have you been able to solve the issue on your side?
No progress on mine... :(

**Comment by carlcraig** [comment]
not sure if this will make a difference, but worth a try:

```yaml
        api:
            pattern:    ^/api/.* # instead of ^/api
```

**Comment by Yonn-Trimoreau** [comment]
No progress on mine neither, I've disabled it since someone helps finding an answer.. I tried debugging but with no success.
@carlcraig Sadly, your solution is not working, but thanks for trying ;)

**Comment by slashfan** [comment]
Hi @Yonn-Trimoreau @vialcollet 

I just pushed a new branch on the sandbox repository showing how to make a basic integration of the bundle with fosuserbundle. You can find [it here](
https://github.com/slashfan/LexikJWTAuthenticationBundleSandbox/tree/fosuser-integration). Use the `make install` or `make test` command to test it (you'll need a database).

Based on this simple tests it works fine, so I don't really know how to help without having more info about your code.

By the way, could you show your FOSUserBundle configuration ?

**Comment by vialcollet** [comment]
Hi @Yonn-Trimoreau .
That's great news to see that you have spent some of your time configuring this bundle. I am sure I'll be able to understand what's wrong from there.

One thing to mention is that I have two firewalls. One for the standard Symfony web access and another one for the mobile API using AngularJS (Ionic framework).
In the fos_user fonciguration, I specify `firewall_name: main` only. Maybe that's the reason...

Here is my FOSUserBundle here:
```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Curuba\contactsBundle\Entity\users
    group:
        group_class: Curuba\contactsBundle\Entity\Group
    from_email:
            address:        bastien.vial-collet@curuba.fr
            sender_name:    Bastien Vial-Collet
```

I'll keep you posted.

**Comment by vialcollet** [comment]
Hmm. No success so far. Your Sandbox is obviously working perfectly on my Windows PC.
I see five differences between your sandbox and my app.

+ I am running my Symfony app from wamp
+ Because of the above and because Angular App is served from a node server I am using CORS.
+ I don't have any specific listeners related to your bundle. 
+ I have two logins: one traditional form provided by FOS for Web access and a stateless one used by the application.
+ I have to firewalls : one for the api: `api` and one for the web access: `main`

Excepts from the above, configuration and security have the exact same code.

I can confirm that the header of the GET request includes the token (BEARER + token).

What do you suggests as the next step to understand where it is failing. How can I go beyond the exception `You are not authenticated, A Token was not found in the SecurityContext.)?

**Comment by carlcraig** [comment]
Have you looked at:
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#important-note-for-apache-users 
Might be this issue that is preventing token from being there for firewall to authenticate.

**Comment by vialcollet** [comment]
Hi @carlcraig . Thanks for your help.

I just tried to run the server using app.console server:run and now it works!!
So it confirms that the issue is coming from the apache configuration.

As indicated in my first post, I had activated vhosts in wamp and added the RewriteEngine instructions. But this was not helping.

For information here is what I have:

```
#httpd.conf
# Virtual hosts
Include conf/extra/httpd-vhosts.conf
```

And : 
```
#httpd-vhosts.conf
<VirtualHost *:8080>

    DocumentRoot "c:/wamp/www"
    ServerName localhost
    RewriteEngine On
    RewriteCond %{HTTP:Authorization} ^(.)
    RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

</VirtualHost>
```

No idea why this is not working!

My next step will be to deploy on a test server to check everything is fine.

Thank you all for your help and if you have any clue why the above wamp config doesn't work let me know!

**Comment by slashfan** [comment]
@Yonn-Trimoreau Have you made any progress ? Can we close the issue ?

**Comment by Yonn-Trimoreau** [comment]
Sorry about the week without answers from me, I was in vacation.
In fact, @vialcollet only invited himself in my issue. Our issues are totally different.
I'm not getting the token at all, while he is.
So, my issue is exacty at the same point as @vialcollet stopped it. When I send my credentials to `/api/login_check`, it responds 401 Bad Credentials..

**Comment by slashfan** [comment]
I really cannot help you without seeing the code. Have you looked at the fosuser branch of the sandbox ?

**Comment by Yonn-Trimoreau** [comment]
Yes, I looked at it and tried your way, still no way of making it work.. Here is my code : 

`config.yml` :
```
fos_user:
    db_driver: orm
    firewall_name: admin
    user_class: Ork\VtcBundle\Entity\User

lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    pass_phrase:      'test'                                 # ssh key pass phrase
    token_ttl:        86400
    encoder_service:     lexik_jwt_authentication.jwt_encoder
```

`security.yml`
```
    firewalls:
        dev:
            pattern:  ^/{_{profiler|wdt}}/
            security: false
            switch_user: true

        api_login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path:     api_login_check
                username_parameter: username
                password_parameter: password
                require_previous_session: false
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    prefix: Bearer
                throw_exceptions:        true

        admin:
            pattern: ^/admin
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:
                path:        /admin/logout
                target:      /admin
            anonymous:    true
```

`routing.yml`
```
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /admin

api_login_check:
    path: /api/login_check
```

`parameters.yml`
```
    jwt_private_key_path: %kernel.root_dir%/var/jwt/private.pem   # ssh private key path
    jwt_public_key_path:  %kernel.root_dir%/var/jwt/public.pem    # ssh public key path
    jwt_key_pass_phrase:  'test'                                      # ssh key pass phrase
    jwt_token_ttl:        86400
```

I'm sure it's a little thing, thank you for helping me and sorry for bothering you about my issue

**Comment by Yonn-Trimoreau** [comment]
No idea ? :(

**Comment by slashfan** [comment]
Sorry no. Have you tried debugging step by step ? Is the success_handler or the failure handler of your form_login even called ?

**Comment by Yonn-Trimoreau** [comment]
I don't have any handler set, how do I do this ?

**Comment by slashfan** [comment]
They are present in your `security.yml`

```yaml
api_login:
    pattern:  ^/api/login
    stateless: true
    anonymous: true
    provider: fos_userbundle
    form_login:
        check_path:     api_login_check
        username_parameter: username
        password_parameter: password
        require_previous_session: false
        success_handler: lexik_jwt_authentication.handler.authentication_success # here
        failure_handler: lexik_jwt_authentication.handler.authentication_failure # here
```

**Comment by Yonn-Trimoreau** [comment]
But what are they associated to and how do I use it ?

**Comment by vialcollet** [comment]
One question @Yonn-Trimoreau, what is your environment?

**Comment by Yonn-Trimoreau** [comment]
Linux Mint / Apache 2.4.7 / PHP 5.5.9 / PostgreSQL 9.3.6

**Comment by skrajewski** [comment]
Hello all,

I had a similar problem with this bundle and FOSUserBundle. I have two providers in my *security.yml* in this order

- in_memory
- fos_userbundle

My primary provider is *fos_userbundle*, so I added key `provider: fos_userbundle` to my firewall section but the server return 401 response with empty body instead of 200 or "Bad Credentials" information. I changed providers order (fos_userbundle first) and everything works correctly. It seems  `provider` option does not work and firewall will use first registered provider.

**Comment by trousers** [comment]
I found the problem by debugging the exception returned in the construct

Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationFailureEvent

In my case the exception was coming from FOSuserbundle and telling me no username!

**Comment by 3KyNoX** [comment]
and @trousers did you corrected this pointed problem ?

Facing no username given too in dev.log when using 

> curl -X POST -d '{"username": "johndoe", "password": "test"}' -H "Content-Type:application/json" http://courtier-web-api-platform/app_dev.php/login_check

Works when using 

> curl -X POST -d  username="johndoe" -d password="test" http://courtier-web-api-platform/app_dev.php/login_check

But I need to post my request in json.

**Comment by kent99** [comment]
Hello,
Any updates for this issue? I use JWTAuthenticationBundle with FOSUser and it is impossible for me to authenticate an user with username/email, this is either username or email.

**Comment by chalasr** [comment]
@kent99 Are you able to achieve this with FOSUser only (without this bundle)? 
Otherwise, your issue come from FOSUser; or worst, Symfony.

It's not common to have two "username" combined for an authentication. Maybe you should look for only one (either username or email)?

**Comment by skrajewski** [comment]
@kent99,

Could you show your `security.yml` file?

**Comment by kent99** [comment]
@chalasr yes it worked with FOSUser Bundle [Logging by Username or Email](http://symfony.com/doc/current/bundles/FOSUserBundle/logging_by_username_or_email.html)

JWTAuthenticationBundle provides only one authentification field?

Maybe I have to open an issue for this but this issue is related to my problem, I allow the user to change his email but as the email does not change in the token payload I have a 401 Bad credentials when the user does another request after that user updated his email.

@skrajewski yes please find my security.yml below

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: ...
        Symfony\Component\Security\Core\User\User:
            algorithm: ...
            cost: ...

...

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory:
                users:
                   ...

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern: ^/api/doc
            provider: ...
            anonymous: ~
            ...

        authenticate:
            pattern:  ^/v1/authenticate
            stateless: true
            anonymous: true
            form_login:
                check_path:               /v1/authenticate
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        refresh:
            pattern:  ^/v1/token/refresh
            stateless: true
            anonymous: true
            provider: fos_userbundle

        api:
            pattern:   ^/v1
            provider: fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

    access_control:
        ...
```
