### ISSUE TITLE
Can't authenticate, "Bad credentials" on Symfony 4/MongoDB

### ISSUE THREAD

**Issue by Cypaubr** [lexik/LexikJWTAuthenticationBundle#691]
Hi, I am trying to make my API secured with JWT token. I followed the installation process but I can not authenticate using a stored user I always get this result:
```json
{
    "code": 401,
    "message": "Bad credentials."
}
```

Here is my lexik_jwt_authentication.yaml:
```yaml
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(resolve:JWT_PASSPHRASE)%'
    token_ttl: '%env(resolve:JWT_TOKEN_TTL)%'
```

Here is my security.yaml:
```yaml
security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Document\User:
            algorithm: bcrypt
    providers:
        user_mongo:
            mongodb:
                class: App\Document\User
                property: username
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            provider: user_mongo
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            anonymous: ~
            pattern: ^/

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYLOUSLY }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_ADMIN }
```

My User.php:
```php
<?php


namespace App\Document;

use Carbon\Carbon;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;

/**
 * Class User
 * @package App\Document
 * @MongoDB\Document
 */
class User implements AdvancedUserInterface
{

    /**
     * @var string
     * @MongoDB\Id
     */
    protected $id;

    /**
     * @var string
     * @MongoDB\Field(type="string")
     */
    protected $email;

    /**
     * @var array
     * @MongoDB\Field(type="collection")
     */
    protected $roles = ['ROLE_USER'];

    /**
     * @var string
     * @MongoDB\Field(type="string")
     */
    protected $password;

    /**
     * @var bool
     * @MongoDB\Field(type="bool")
     */
    protected $accountNonExpired = true;

    /**
     * @var bool
     * @MongoDB\Field(type="bool")
     */
    protected $accountNonLocked = true;

    /**
     * @var bool
     * @MongoDB\Field(type="bool")
     */
    protected $credentialsNonExpired = true;

    /**
     * @var bool
     * @MongoDB\Field(type="bool")
     */
    protected $enabled = true;

    /**
     * @var \DateTimeImmutable
     * @MongoDB\Field(type="date")
     */
    protected $createdAt;

    /**
     * @var \DateTimeImmutable
     * @MongoDB\Field(type="date")
     */
    protected $updatedAt;

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        return $this -> roles;
    }

    /**
     * Returns the password used to authenticate the user.
     *
     * This should be the encoded password. On authentication, a plain-text
     * password will be salted, encoded, and then compared to this value.
     *
     * @return string|null The encoded password if any
     */
    public function getPassword()
    {
        return $this -> password;
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this -> email;
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    /**
     * @return string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param string $id
     * @return User
     */
    public function setId(string $id): User
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     * @return User
     */
    public function setEmail(string $email): User
    {
        $this->email = $email;
        return $this;
    }

    /**
     * @param array $roles
     * @return User
     */
    public function setRoles(array $roles): User
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @param string $password
     * @return User
     */
    public function setPassword(string $password): User
    {
        $this->password = $password;
        return $this;
    }

    /**
     * @return \DateTimeImmutable
     */
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeImmutable $createdAt
     * @return User
     */
    public function setCreatedAt(\DateTimeImmutable $createdAt): User
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    /**
     * @return \DateTimeImmutable
     */
    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTimeImmutable $updatedAt
     * @return User
     */
    public function setUpdatedAt(\DateTimeImmutable $updatedAt): User
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * @MongoDB\PrePersist()
     * @MongoDB\PreUpdate()
     */
    public function updateTimestamps()
    {
        $this -> updatedAt = Carbon::now() -> toDateTimeImmutable();
        if ($this -> createdAt == null) {
            $this -> createdAt = Carbon::now() -> toDateTimeImmutable();
        }
    }

    /**
     * Checks whether the user's account has expired.
     *
     * Internally, if this method returns false, the authentication system
     * will throw an AccountExpiredException and prevent login.
     *
     * @return bool true if the user's account is non expired, false otherwise
     *
     * @see AccountExpiredException
     */
    public function isAccountNonExpired()
    {
        return $this -> accountNonExpired;
    }

    /**
     * Checks whether the user is locked.
     *
     * Internally, if this method returns false, the authentication system
     * will throw a LockedException and prevent login.
     *
     * @return bool true if the user is not locked, false otherwise
     *
     * @see LockedException
     */
    public function isAccountNonLocked()
    {
        return $this -> accountNonLocked;
    }

    /**
     * Checks whether the user's credentials (password) has expired.
     *
     * Internally, if this method returns false, the authentication system
     * will throw a CredentialsExpiredException and prevent login.
     *
     * @return bool true if the user's credentials are non expired, false otherwise
     *
     * @see CredentialsExpiredException
     */
    public function isCredentialsNonExpired()
    {
        return $this -> credentialsNonExpired;
    }

    /**
     * Checks whether the user is enabled.
     *
     * Internally, if this method returns false, the authentication system
     * will throw a DisabledException and prevent login.
     *
     * @return bool true if the user is enabled, false otherwise
     *
     * @see DisabledException
     */
    public function isEnabled()
    {
        return $this -> enabled;
    }
}
```

I have only one route for the moment in my routes.yaml:
```yaml
api_login_check:
  path: /api/login_check
  defaults: { _controller: App\Controller\SecurityController::apiLogin }
  methods: ['POST']
```

Anf of course the controller:
```php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;

class SecurityController extends AbstractController
{
    public function apiLogin(): JsonResponse
    {
        $user = $this -> getUser();

        return new Response([
            'email' => $user -> getEmail(),
            'roles' => $user -> getRoles()
        ]);
    }
}
```

I really don't know what to do, I am stuck for a day now...
