### ISSUE TITLE
HMAC support documentation

### ISSUE THREAD

**Issue by MLDMoritz** [lexik/LexikJWTAuthenticationBundle#692]
Hey,

HMAC support seems to be not working out of the box, like its suggested.

If there is no private key, encoder signature_algorithm should default to a working version like `HS256`.

This is not documented, by the way.

Minimal configuration for using HMAC would be something like this:

```
lexik_jwt_authentication:
    secret_key: '%env(JWT_SECRET_KEY)%'
    encoder:
        signature_algorithm: HS256
```
