### ISSUE TITLE
How to authenticate in multi-tenant systems?

### ISSUE THREAD

**Issue by fma-technologies** [lexik/LexikJWTAuthenticationBundle#698]
Hello,

It looks like the default implementation relies on the username being a unique field. In my case, I can have multiple users with the same username (but the client / username combination will be unique).

    {"username":"myuseraccount","password":"mysecretpassword","client":"1500"}

What would I need to change so that I can add another parameter, like above, when making the initial authentication request?

**Comment by lolmx** [comment]
I managed it writing a custom UserProvider, made it implements `Lexik\Bundle\JWTAuthenticationBundle\Security\User\PayloadAwareUserProviderInterface`.

In the new `loadUserByUsernameAndPayload` method you'll be given the username along the payload, there it is you can store arbitrary data inside it, like your client id.
Then you just have to find your user with username/clientId pair.

Add a listener to add client id on newly created jwt and you're good.
(listener  for event `lexik_jwt_authentication.on_jwt_created`)

Quite full example below:
```php
namespace AppBundle;

use AppBundle\Entity\User;
use AppBundle\Repository\UserRepository;
use Lexik\Bundle\JWTAuthenticationBundle\Security\User\PayloadAwareUserProviderInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface;

class MyCustomProvider implements PayloadAwareUserProviderInterface
{
    /**
     * @var UserRepository
     */
    private $userRepository;

    /**
     * @var array
     */
    private $cache = [];

    /**
     * @var RequestStack
     */
    private $requestStack;

    public function __construct(UserRepository $userRepository, RequestStack $requestStack)
    {
        $this->userRepository = $userRepository;
        $this->requestStack = $requestStack;
    }

    public function loadUserByUsernameAndPayload($username, array $payload)
    {
        if (isset($this->cache[$username])) {
            return $this->cache[$username];
        }

        if (!isset($payload['clientId'])) {
            // Fetch from where ever you want, for example through the requestStack
            $payload['clientId'] = $this->requestStack->getCurrentRequest()->attributes->get('clientId');
        }

        $user = $this->userRepository->findOneBy([
            'username' => $username,
            'client' => $payload['clientId'],
        ]);

        if (null === $user) {
            throw new UsernameNotFoundException();
        }

        return $this->cache[$username] = $user;
    }

    public function loadUserByUsername($username)
    {
        return $this->loadUserByUsernameAndPayload($username, []);
    }

    public function refreshUser(UserInterface $user)
    {
        return $user;
    }

    public function supportsClass($class)
    {
        return User::class === $class;
    }
}
```

```yml
# security.yml

security:
    providers:
        custom_provider:
            id: AppBundle\MyCustomProvider # <- your class' service id, here i'm using autowiring
    firewalls:
        login:
            anonymous: true
            stateless: true
            provider: custom_provider
            json_login:
                check_path: my_route
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

```php
namespace AppBundle;

use Lexik\Bundle\JWTAuthenticationBundle\Event\JWTCreatedEvent;
use Symfony\Component\HttpFoundation\RequestStack;

class AddClientPayloadListener
{
    /**
     * @var RequestStack
     */
    private $requestStack;

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function addClientToPayload(JWTCreatedEvent $event): void
    {
        $request = $this->requestStack->getCurrentRequest();

        if (null === $request) {
            return;
        }

        // Because in most case you'll only create tokens upon login or when refreshing token, only check for those routes
        $route = $request->attributes->get('_route');
        if ('client_login' !== $route && 'token_refresh' !== $route) {
            return;
        }

        $payload = $event->getData();
        // And again get your client id from where ever you want, for the example through the requestStack
        $payload['clientId'] = $request->attributes->get('clientId');

        $event->setData($payload);
    }
}
```

```yml
# services.yml

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # ...

    AppBundle\AddClientPayloadListener:
        tags:
            -
                name: kernel.event_listener
                event: lexik_jwt_authentication.on_jwt_created
                method: addClientToPayload
```
