### ISSUE TITLE
How to add extra data to the existing login_check route

### ISSUE THREAD

**Issue by xvilo** [lexik/LexikJWTAuthenticationBundle#711]
I have the `api_login_check` route configured and it does work with my authenticator, however, the current response is `{"token": "some-jwt"}`, I would like to add extra/additional data to that array. 

I tried creating an event listener on `lexik_jwt_authentication.on_authentication_success`. So I have added the following to my `services.yml`:

```yaml
    app.event.jwt_authenticated_listener:
        class: App\EventListener\JWTAuthenticatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }
```

The listener class looks as follow:

```php
<?php
declare(strict_types=1);

namespace App\EventListener;

use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationSuccessEvent;

class JWTAuthenticatedListener
{
    /**
     * @param AuthenticationSuccessEvent $event
     */
    public function onAuthenticationSuccess(AuthenticationSuccessEvent $event): void
    {
        $event->setData(array_merge(
            $event->getData() ?? [],
            ['token' => 'foobar']
        ));
    }
}
```

However this does not yield extra data to be added to the JSON Response. What am I missing?
