### ISSUE TITLE
Misleading error messages when providers are incorrectly configured

### ISSUE THREAD

**Issue by rapliandras** [lexik/LexikJWTAuthenticationBundle#715]
Having the following configuration
```
        publicapp_user_provider:
            entity:
                class: App\Entity\PortalUser
                property: emailAddress
```

I receive

```
{
    "code": 401,
    "message": "Invalid credentials."
}
```

When I disable the Accept and Content-Type headers, I get

```
Unable to find the controller for path \"/publicapi/login\". The route is wrongly configured.
```

Which is thrown by the symfony kernel, thus making it impossible to debug.

The problem above was that the user provider's `emailAddress` property should've been `email`, as it had been changed previously. The configuration was fixed and the login was working so far.

Now, I  face a different misconfiguration, yet the same message. And it gives me zero aid where to start. (Afaik everything is according to the config docs)

**Comment by abelardolg** [comment]
This error is showed me but I don't know why.

I correctly provide the username and the password but it doesn't work.

**Comment by fd6130** [comment]
> This error is showed me but I don't know why.
> 
> I correctly provide the username and the password but it doesn't work.

Do you mean this error message?

```json
{
    "code": 401,
    "message": "Authentication request could not be processed due to a system problem."
}
```

OR If it is just a simple `Bad Credential` or `Invalid Credential` error message, maybe you forgot to configure the `user_identity_field`:

```yaml
lexik_jwt_authentication:
    # ...
    user_identity_field: username
```
