### ISSUE TITLE
Invalid JWT Token

### ISSUE THREAD

**Issue by leo91000** [lexik/LexikJWTAuthenticationBundle#720]
Hi, 

I am having a problem with your bundle.
I have one endpoint to get a bearer token (POST /authentication_token).

However when I use my token to acces some protected routes, I get the following response :
```json
{
    "code": 401,
    "message": "Invalid JWT Token"
}
```

I know there are other related issues, but I couldn't find any solution in any of these : #221 #199 #354 #705

Here is my security.yaml :
```yml
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /authentication_token
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

```

I am using API platform, here is how I protect my route :
```php
/**
 * @ApiResource(
 *      output=Output::class,
 *      input=Input::class,
 *      collectionOperations={
 *          "get",
 *          "post"={"security"="is_granted('ROLE_ADMIN')"}
 *      },
 *      itemOperations={
 *          "get",
 *          "put"={"security"="is_granted('ROLE_ADMIN')"},
 *          "patch"={"security"="is_granted('ROLE_ADMIN')"},
 *          "delete"={"security"="is_granted('ROLE_ADMIN')"}
 *      },
 *      normalizationContext={"groups"={"MEDIA_OBJECT_READ"}},
 *      denormalizationContext={"groups"={"MEDIA_OBJECT_WRITE"}}
 * )
 * @ORM\Entity(repositoryClass="App\Repository\MediaObjectRepository")
 */
class MediaObject
{
    ...
}
```
What did I do wrong ?

EDIT :

After some digging, I found that the error was thrown by LlcobucciJWTEncoder  :
```
It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line
```
Do you have any idea why ?

My env variables are like this :

```env
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
```

And my keys are generated by php :
```php
        $rsa = new RSA();
        $rsa->setPublicKeyFormat(RSA::PUBLIC_FORMAT_PKCS1);
        $rsa->setComment("api-jwt-key");
        $keyPair = $rsa->createKey(4096);
        $privateKey = $keyPair['privatekey'];
        $publicKey = $keyPair['publickey'];

        $jwtPath = $this->fileService->joinPaths($this->fileService->getRootDir(), 'config', 'jwt');

        file_put_contents($this->fileService->joinPaths($jwtPath, 'private.pem'), $privateKey);
        file_put_contents($this->fileService->joinPaths($jwtPath, 'public.pem'), $publicKey);
```
The generated keys are stored in project/config/jwt/[private|public].pem
