### ISSUE TITLE
[question] load user with username when logging in with email

### ISSUE THREAD

**Issue by waspinator** [lexik/LexikJWTAuthenticationBundle#721]
I'm trying to configure JWTs to work with [API-Platform](https://api-platform.com/docs/core/jwt/#configuring-the-symfony-securitybundle). I can get a token by `post`ing my email and password to `/authentication_token`, but when I try to use it as a Bearer token I get the following error:

```
{
    "code": 401,
    "message": "Unable to load an user with property \"username\" = \"admin\". If the user identity has changed, you must renew the token. Otherwise, verify that the \"lexik_jwt_authentication.user_identity_field\" config option is correctly set."
}
```
If I change the entity property in the `app_user_provider` after logging in to `username` then the token works. 

How would I load a user using the username property? Or have set lexik_jwt_authentication.user_identity_field to use email? Or better yet use either username or password?

If I add `user_identity_field: email` to `lexik_jwt_authentication.yaml` the error changes to 

```
{
    "code": 401,
    "message": "Unable to find key \"email\" in the token payload."
}
```

`routes.yaml`
```
authentication_token:
    path: /authentication_token
    methods: ['POST']
```

`lexik_jwt_authentication.yaml`
```
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
```

`security.yaml`
```
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            anonymous: lazy
            provider: app_user_provider
            json_login:
                check_path: /authentication_token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```
