### ISSUE TITLE
Authentication firewalls aren't respecting the access_control rules

### ISSUE THREAD

**Issue by EmilCataranciuc** [lexik/LexikJWTAuthenticationBundle#724]
For the following firewall:
```
    api:
      pattern:   ^/api
      stateless: true
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
```

This has no effect (still asks for authentication):
```
  access_control:
    - { path: '^/api/invoice/download/',        roles: IS_AUTHENTICATED_ANONYMOUSLY }
```
