### ISSUE TITLE
using test key

### ISSUE THREAD

**Issue by dev-yann** [lexik/LexikJWTAuthenticationBundle#726]
I would like to use two pair, prod and test
My config/jwt contain: 

- private.pem
- public.pem
- private-test.pem
- public-test.pem

This is my config/packages/lexik_jwt_authentication.yaml:
```
lexik_jwt_authentication:
 
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'

    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'

    pass_phrase: '%env(JWT_PASSPHRASE)%'

    token_ttl: 10800 # 3h in seconds

    token_extractors:

        cookie: # using cookie jwt

            enabled: true

            name: '%env(TOKEN_COOKIE_NAME)%'

```

and my config/test/lexik_jwt_authentication.yaml:
```
lexik_jwt_authentication:
secret_key: '%kernel.project_dir%/config/jwt/private-test.pem'
public_key: '%kernel.project_dir%/config/jwt/public-test.pem'
pass_phrase: '%env(JWT_PASSPHRASE)%'
```

it appear that when I run my test with `php bin/phpunit` my  config/test/lexik_jwt_authentication.yaml is never call. unit test use my config/packages/lexik_jwt_authentication.yaml. It is a phpunit configuration problem or is there another solution ? 
thanks for your time ❤️
