### ISSUE TITLE
I receive token, but not authorized when trying to use it.

### ISSUE THREAD

**Issue by plamenh** [lexik/LexikJWTAuthenticationBundle#734]
Config:

```
main:
    ...

    json_login:
        check_path: /authentication_token
        username_path: username
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

jwt_test:
            pattern:    ^/jwt-test
            stateless:  true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

access_control:
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/jwt-test, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

As stated in the title, I get the token, but then can't use it to get to any content:

```
/**
     * @Rest\Get("/jwt-test")
     *
     * @return View
     */
    public function jwtTestAction()
    {
        $user = $this->getUser();

        return new View($user, Response::HTTP_OK);
    }
```

I get an empty response instead of user. If I check with `$this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');`, I get redirected to login page. The funny thing is that when I use Postman to get the token and then make another request, even without Bearer token, I get the data just fine. Not sure, if this is postman session or anything (even using different tabs).
