### ISSUE TITLE
LexikJWTAuthenticationBundle err "code": 401,     "message": "Invalid credentials." 

### ISSUE THREAD

**Issue by HB-booba** [lexik/LexikJWTAuthenticationBundle#736]
hello guys,

first of all thank you for this bundle,
i have an issue every time i send authentication request, even if the other requests works very well,

![image](https://user-images.githubusercontent.com/35043477/78550013-3ea94a00-77fb-11ea-988a-b312c21bed83.png)

![image](https://user-images.githubusercontent.com/35043477/78549987-351fe200-77fb-11ea-986f-c9af2a74ca08.png)
  
![image](https://user-images.githubusercontent.com/35043477/78550048-508aed00-77fb-11ea-9602-64fac674c246.png)

**Comment by sanchobouillant** [comment]
Hi, 

I have exactly the same issue. Maybe an issue with the password encoder set to auto?

**Comment by HB-booba** [comment]
> Hi,
> 
> I have exactly the same issue. Maybe an issue with the password encoder set to auto?
> 
> Edit: I solved my problem. My user entity had not a valid getPassword().

thanks for your answer but its not the case, i checked the user and nothing looks bad..!

**Comment by drychlik76** [comment]
Im having the exact same issue but with Symfony 4.  Ive spent 2 days trying to resolve this.  I am using a Macbook for local development.

**Comment by pam81** [comment]
Same issue on my side! Symfony 4.3 and lexik/jwt-authentication-bundle 2.6 
I'm always getting 401 Invalid Credentials. I did a basic configuration like in the doc

**Comment by playerro** [comment]
Works nice, but not with custom errors instead of 401. My issue:
#739

**Comment by ivleneb** [comment]
Same problem, some one resolved?

**Comment by ivleneb** [comment]
I'm resolve in this way: add a 'username_path' and 'password_phone'
##
    firewalls:
      #added from here
        login:
            pattern:  ^/api/login_check
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                username_path: phone
                password_path: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
##

I've previously made a "JSON Authentication Endpoint" according to this https://symfony.com/doc/4.4/security/json_login_setup.html. According to that you must enter a 'route' to find the credentials in the json structure.... So, in the end was a symfony thing.

**Comment by DevManen** [comment]
I had a similar problem. 

I edited the security's configuration in every possible way, I overided the _JsonLoginFactory_ and the _DaoAuthenticationProvider_.
Then, after 2 hours of stupidity, I realize that the **_password_ column in my _User_ entity was truncated to 50 characters**...

For the great majority of encoders (including _bcrypt_ and _argon2i_), 50 characters is not enough at all.
The encoded password will be truncated and the method _PasswordEncoderInterface::isPasswordValid()_ called in _UserAuthenticationProvider::checkAuthentication()_ will never return _TRUE_.

So, if it can help someone, with an encoded password stored in a database : don't forget to **check the column's definition of your _User_ entity** !

**Comment by fd6130** [comment]
If you serve your project using symfony-cli i think you can read the debug error message in your terminal. Or go to profiler to have a look and test the sql query?

**Comment by fd6130** [comment]
> hello guys,
> 
> first of all thank you for this bundle,
> i have an issue every time i send authentication request, even if the other requests works very well,
> 
> ![image](https://user-images.githubusercontent.com/35043477/78550013-3ea94a00-77fb-11ea-988a-b312c21bed83.png)
> 
> ![image](https://user-images.githubusercontent.com/35043477/78549987-351fe200-77fb-11ea-986f-c9af2a74ca08.png)
> 
> ![image](https://user-images.githubusercontent.com/35043477/78550048-508aed00-77fb-11ea-9602-64fac674c246.png)

I see you forgot to add `property` in your provider config...so my guess is it doesn't know which property you want to treat as "username"..

You may refer to the docs: https://symfony.com/doc/current/security.html#b-the-user-provider

**Comment by fd6130** [comment]
So what is your `App\Entity\User` looks like?

**Comment by BrandonBx** [comment]
Hello take care because for me (I use symfony 5.3), I changed the entity user->getUsername. Take care to get the right username_path

**Comment by Systemcheck** [comment]
The solution which did the job for me is:

User Entity:

Method getUsername() returns .. of course $this->username
The username wasnt used to authenticate, thatswhy i changed the return to $this->email

**Comment by ismaellastlevel** [comment]
I had a similar problem and I figured out it this way: I was using the email fiel instead of the username for authentication , so:
- in security.yaml i set the **username_path** to email:
 ```
firewalls:
    #...
    login:
        pattern: ^/api/login
        stateless: true
        json_login:
            check_path: /api/login
            username_path: email
            password_path: password
            success_handler: lexik_jwt_authentication.handler.authentication_success
            failure_handler: lexik_jwt_authentication.handler.authentication_failure
    
    api:
        pattern: ^/api
        stateless: true
        jwt: ~
            
```

- and in the lexik_jwt_authentication.yaml file I added **user_identity_field**: email:
```
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # in seconds, default is 3600
    user_identity_field: email  # key under which the user identity will be stored in the token payload
```
