### ISSUE TITLE
Invalid credentials instead of 422 or 404 errors

### ISSUE THREAD

**Issue by playerro** [lexik/LexikJWTAuthenticationBundle#739]
Hello! I'm using JWT Bundle with SF4+apache+PGSQL. I have api and login check. Trying to send POST request with correct credentials gives me 200 OK. Trying to send POST request with bad credentials gives me ALWAYS 401 Invalid credentials and never go in my code which should response 422 in this case. 

Here is code:
```
/**
     * @Route("/api/login_check")
     * @param Request $request
     * @param JWTTokenManagerInterface $JWTManager
     * @param UserPasswordEncoderInterface $encoder
     * @return JsonResponse
     */
    public function getTokenUser(Request $request, JWTTokenManagerInterface $JWTManager, UserPasswordEncoderInterface $encoder) {
        $request = $this->transformJsonBody($request);
        $username = $request->get('username');
        $password = $request->get('password');
        if (empty($username) || empty($password)) {
            return $this->respondValidationError("Invalid username or password");
        }
        $em = $this->getDoctrine()->getManager();
        /* @var $user User */
        $user = $em->getRepository(User::class)->findOneBy([
            'username' =>$username,
        ]);
        if (!$user) {
            //returns 422
            return $this->respondValidationError("User with these credentials not found");
        }
        if ($user->getPassword() !== $encoder->encodePassword($user, $password)) {
           //returns 422
         return $this->respondValidationError("User with these credentials not found");
        }
        return new JsonResponse(['test' => $JWTManager->create($user)]);
    }
```
If credentials is not correct I never get into this function, why?

Here is security:

```
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: app_user_provider
    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login_check, roles:  IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

```

I tried to change apache config, security.yml firewall config, nothing worked. Please help
