### ISSUE TITLE
TokenStorage not populated when creating token programmatically

### ISSUE THREAD

**Issue by fhuszti** [lexik/LexikJWTAuthenticationBundle#748]
I've got two kind of users I need to log in, the local ones who use a simple authentication system (they send username/password to the API, LexikJWT finds them in the db and authenticates them, then returns a token), and the other ones who have a `password === null` in the db and should be authenticated using a LDAP connection to a remote server.
What I did was let everyone send their credentials to the same login endpoint, so LexikJWT dispatches an `AuthenticationFailureEvent `for the LDAP users. In an `AuthenticationFailureListener`, I then test the credentials against the LDAP server. My plan is that if this fails, I let the API throw an `InvalidCredentialsException`, but if LDAP says OK, I programatically authenticate the user using `$authenticationSuccessHandler->handleAuthenticationSuccess($user)` as [per the doc](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/7-manual-token-creation.md).

Which brings me to my issue: when authenticating manually my user like this, the TokenStorage is not populated, whereas it is when authenticating the classic way. Moreover, and maybe this is linked, but when authenticating manually, the process actually goes all the way through my `AuthenticationSuccessListener` but it still ends up returning an `InvalidCredentialsException`.

Here is my `security.yaml`:
```
...
 providers:
        app_user_provider:
            entity:
                class: App\Entity\API\User
                property: login
        jwt:
            lexik_jwt: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        anon:
            pattern: ^/anon/
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /anon/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/
            stateless: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/anon/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,      roles: IS_AUTHENTICATED_FULLY }
```

And my `AuthenticationFailureListener`:
```
public function onAuthenticationFailureResponse(AuthenticationFailureEvent $event)
    {
        try {
            $login = $event->getException()->getToken()->getUser();
            $password = $event->getException()->getToken()->getCredentials();
            //if JWT authentication didn't work, we try LDAP
            $dn = $BASE_DN.$login;
            $this->ldap->bind($dn, $password);
            //if we're still here, then LDAP is OK, so we fetch the user
            $user = $this->em->getRepository(User::class)->findOneBy(['login' => $login]);
            if (!$user)
                throw new InvalidCredentialsException();
            return $this->authenticationSuccessHandler->handleAuthenticationSuccess($user);
        } catch (\Exception $e) {
            throw new HttpException(401, "Invalid credentials");
        }
    }
```

Am I doing something wrong? Shouldn't manual token creation populate the TokenStorage anyway?

EDIT: the problem was my `$user` I gave to `$this->authenticationSuccessHandler->handleAuthenticationSuccess($user)` had his password field to null, which the authentication system didn't like. So I added the encoded password to the `$user` before passing it on.
I also moved my whole LDAP logic to a subscriber listening to `kernel.request`, as it is way cleaner than waiting for JWT to throw an `Exception` before working it.
