### ISSUE TITLE
on multiple Doctrine ORM code":401,"message":"Authentication request could not be processed due to a system problem

### ISSUE THREAD

**Issue by starcodeconqueror** [lexik/LexikJWTAuthenticationBundle#757]
{
    "code": 401,
    "message": "Authentication request could not be processed due to a system problem."
}

my security.yaml
```yaml
security:
    encoders:
        App\Entity\Customer\Users:
            algorithm: argon2i

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Customer\Users
                property: email
```
in UsersRepository
```php
public function upgradePassword(UserInterface $user, string $newEncodedPassword): void
    {
        if (!$user instanceof Users) {
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', \get_class($user)));
        }

        $user->setPassword($newEncodedPassword);
        $this->_em->persist($user);
        $this->_em->flush();
    }
```

is this error raise because i have multiple em ?
```yaml
doctrine:
    dbal:
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        default_connection: main
        connections:
            main:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_MAIN)%'
                charset: utf8mb4
            customer:
                # configure these for your database server
                url: '%env(resolve:DATABASE_URL_CUSTOMER)%'
                charset: utf8mb4
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: main
        entity_managers:
            main:
                connection: main
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity\Main'
                        alias: Main
            customer:
                connection: customer
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Customer'
                        prefix: 'App\Entity\Customer'
                        alias: Customer

```

**Comment by akira28** [comment]
I'm getting the same issue, and I also have multiple doctrine orm. Did you ever found a workaround?

**Comment by ewertoncode** [comment]
Same problem too

**Comment by vatoer** [comment]
you should define manager_define in your security.yml

```
manager_name: 'your-user-authentication-entity-manager-name'
```

```yaml
providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Customer\Users
                property: email
                # optional: if you're using multiple Doctrine entity
                # managers, this option defines which one to use
                manager_name: 'customer'
```
