### ISSUE TITLE
Get a 401 when trying to get url

### ISSUE THREAD

**Issue by hotgeart** [lexik/LexikJWTAuthenticationBundle#77]
Hi (me again :unamused: ), 

I'm having an issue. I get a 401 error when I'm trying to get someting with my angular (iconic) app. 

Here is the header :
```console
GET /api/newsfeed HTTP/1.1
Host: acme.local
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: http://localhost
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE0Mzc1NjY3OTMsInVzZXJuYW1lIjoiYW5nZWxhQG1haWwuY29tIiwiaWF0IjoiMTQzNzQ4MDM5MyJ9.zQ-HVmtCboibXVMIVBWP9t5oUf2zr_XU2VCIeEJohTZ3MfE2ZciAJv1tS-mjQ3J50SGAVFOMROsF58E5rX7FPJdjtRUU7fEOEWL0qSzlXwnSIsXenX-_Sd2MLxo4_C8rq_4HnQtRLE7sZpZ6oubVr4DoKVkWFm116fUzQL4QP84qdJApIbNXMeWpBbZtBBRqFT9y67dBf7mF_Ml_4EMMEKRU_kuParMOPp3cPuKeU8OWMg5TFj5lq5UweelShkHQskdEPkdlsjDPy5WuLfLjJVJjv-2nMBGOMUpZJ91tfg2FnTOLEUQUmSaPaJ1GxVh3HNjjr2VcPqTyx-dkXQ7WF0V_jSkIyoyOfjfk04FqNx47lsDyyaIxr_hs5CHvblmCt2ObTic-O_k8d9FBuVRJFVjTfrHUvB4NBvv7kwvICg57PbcQaHhFhoWfB7JScpD43cw7GaL4PsDLvcSEdz1Hoajvd6u6AowvtNanjDckVdC1egYWvm0tPgFtmfvqvKOGlV8_mFumRbXaxc-CK1Me5ZbcLsIZw25-z2VZqfekVbHNQqC54fwRBu2kX247Hsjgv0KPOGGmJ4AfLhttv6v4skiDZfhWg_AhvREQcgwkAChcOPUC-bniZmyHzCxofBcRALoMnixIDICRK-bdeD4h4ea5f87E2Xm3gvgLY-OX7V4
Referer: http://localhost/acmeApp/www/login.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
```

And the response:
```console
HTTP/1.1 401 Unauthorized
Date: Tue, 21 Jul 2015 12:06:34 GMT
Server: Apache/2.4.4 (Win32) PHP/5.4.16
Vary: Authorization
X-Powered-By: PHP/5.4.16
Set-Cookie: PHPSESSID=5232dq7k06ibkh7gejapc7clc6; path=/
Cache-Control: no-cache
Access-Control-Allow-Origin: http://localhost
Content-Length: 44
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
Content-Type: application/json
```

At the start I thought it was a problem with the login, but the header show the authorization token is present. So I've no more idea where to look.

My controller : 
```php
<?php

namespace Acme\NewsfeedBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use FOS\RestBundle\Controller\Annotations as FOSRest;
use Acme\NewsfeedBundle\Entity\Newsfeed;

/**
 * ApiController
 *
 * @FOSRest\NamePrefix("api_")
 */
class ApiController extends Controller
{
    /**
     * @throws AccessDeniedException
     * @return array
     */
    public function apiGetNewsfeedAction()
    {
        if (!$this->get('security.context')->isGranted('ROLE_USER')) {
            throw new AccessDeniedException();
        }

        $news = $this->getDoctrine()
                        ->getManager()
                        ->getRepository('AcmeNewsfeedBundle:Newsfeed')
                        ->getNewsfeed($count);

        return $news;
    }
}
```

security.yml
```yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MODO:        ROLE_USER
        ROLE_ADMIN:       ROLE_MODO
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODO, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            switch_user:  true
            remember_me:
                key:      "%secret%"
                lifetime: 31536000
                path:     /
                domain:   ~


    always_authenticate_before_granting: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

config.yml
```yml
# JWT AUTH (API)
lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%


fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener: true
    #disable_csrf_role: ROLE_USER
    body_converter:
        enabled: true
    view:
        view_response_listener: force

nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: false }
    router:  { annotations: true }
```
I've no idea what give you more (code). So let me know.

The eventlistener in the sandbox are optional, no ? Be cause I don"t have them in my project.

Thx

**Comment by Irvyne** [comment]
Same error with config :
```yml
security:
    firewalls:
        ...
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer
``` 
Only query_parameter works, authorization_header always return 401.
