### ISSUE TITLE
Events are not dispatched

### ISSUE THREAD

**Issue by BenjiBoy13** [lexik/LexikJWTAuthenticationBundle#770]
Hi, I'm trying to make use of the JWT events such as (onAuthenticationSuccess, onAuthenticationFailure, etc ), my goal is to register the JWT token in a *Set-Cookie* HTTP header and auto refresh the user token when the expiration date is near, I found this tutorial on the internet ( https://rojas.io/how-to-store-a-jwt-in-a-cookie-and-auto-refresh-the-token-using-lexikjwtauthenticationbundle/ ) but it looks like the events are **not** getting called no matter what aproach I take, I have tried via *event listeners* and *event subscribers*, none of them seems to be working, as it right now I have the following configuration.

security.yaml
```yml
# ...
main:
        anonymous: false
        stateless: true
        provider: orm_users
        guard:
            authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator
# ...
```

lexik_jwt_authentication.yaml
```yml
# ...
token_extractors:
        cookie:
            enabled: true
            name: BEARER
# ...
```
services.yml
```yml
app.jwt_event_subscriber:
        class: App\Subscriber\JwtSubscriber
        tags:
            - { name: kernel.event_subscriber }
```

App\Subscriber\JwtSubscriber.php
```php
use App\Services\JSONResponseService;
use Lexik\Bundle\JWTAuthenticationBundle\Events;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class JwtSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return array(
            Events::AUTHENTICATION_SUCCESS => 'onAuthenticationSuccess',
            Events::AUTHENTICATION_FAILURE => 'onAuthenticationFailure'
        );
    }

    public function onAuthenticationSuccess()
    {
        dump("Okay");
        die();
    }

    // ...
}
```

The JWT bundle works just fine really, but, my events are getting completly ignored by the bundle.
Am I missing something?

Thanks in advance.
