### ISSUE TITLE
User password empty after persisting a (new) entity

### ISSUE THREAD

**Issue by antond1990** [lexik/LexikJWTAuthenticationBundle#781]
When saving a new entity, Doctrine sets the password to an empty string. However, the user object is not passed to the entity manager.

My code to persist the new entity:

```
    $object = new Entity1();

    $object
        ->setKeywords($postData['keywords'] ?? null)
        ->setEntityRelation($entity2)
        ->setCreatedAt(new \DateTime())
        ->setCreatedBy($this->getUser());

    $this->entityManager->persist($object);
    $this->entityManager->flush();
```

When I run `dump($this->getUser())`, the password in the User entity is `""`.

My security.yml file:

security: encoders: App\Entity\User: algorithm: bcrypt

```
providers:
  users:
    entity:
      class: 'App\Entity\User'
      property: 'email'

firewalls:
  login_v1:
    pattern: ^/
    stateless: true
    anonymous: true
    json_login:
      provider: users
      check_path: /v1/login
      success_handler: lexik_jwt_authentication.handler.authentication_success
      failure_handler: lexik_jwt_authentication.handler.authentication_failure
    guard:
      authenticators:
        - lexik_jwt_authentication.jwt_token_authenticator

access_control:
  - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
  - { path: ^/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/v1/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
  - { path: ^/v1/apply,       roles: IS_AUTHENTICATED_FULLY }
  - { path: ^/v1/user/get, roles: IS_AUTHENTICATED_FULLY }
```
