### ISSUE TITLE
Should I version my keys ?

### ISSUE THREAD

**Issue by PauchardThomas** [lexik/LexikJWTAuthenticationBundle#794]
Hello,

As I seen in the doc : 

``` yaml
lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
    pass_phrase:      'your_secret_passphrase' # required for token creation, usage of an environment variable is recommended
    token_ttl:        3600
```

Keys location are located in `%kernel.project_dir%/config/jwt` folder. 

Is it safe to version my keys to my repo (github) or should I put my keys outside of my source code, in a secure directory (eg ~/.ssh) and add the path to a .env file ?

Thanks.
