### ISSUE TITLE
LexikJWTAuthenticationBundle is conflicting with the NelmioCorsBundle

### ISSUE THREAD

**Issue by SmirnovW** [lexik/LexikJWTAuthenticationBundle#811]
Hello, first of all, thank you for the great bundle!

I use the NelmioCorsBundle to manage CORS. Everything works fine except the "login" endpoint. 
The "login" doesn't contain the CORS headers.

this is my configuration:

```yaml
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/v1/account/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/v1/account/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

```

```yaml
nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Authorization']
        max_age: 3600
        allow_credentials: true
        expose_headers: [ '*' ]
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['OPTIONS', 'POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['Authorization']
            max_age: 3600

```

The response of the /api/v1/account/login

<img width="597" alt="Screenshot 2020-12-12 at 22 21 26" src="https://user-images.githubusercontent.com/12068000/101991802-780a5180-3cc8-11eb-8ce3-6655332accad.png">

Is there something wrong with my configs?
