### ISSUE TITLE
Unable to create a signed JWT from the given configuration. (500 Internal Server Error)

### ISSUE THREAD

**Issue by FlorianMrn** [lexik/LexikJWTAuthenticationBundle#822]
Hello everybody !

For two days, I have been trying to resolve the bug named in the title.

The problem appeared when I copied the original repository from github.

I tried :

- Regeneration of the two pem keys
- Update the package (currently 2.1 and Symfony 5.X)
- Hardwrite the passphrase in lexik_jwt_authentication.yaml

lexik_jwt_authentication.yaml : 

```
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
```

security.yaml:

```
         login:
            pattern:  ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

routes.yaml:

```
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
    path: /api/login_check
```

Any advices ?

Thansk by advance :-)
