### ISSUE TITLE
bug: upgrading to 2.11.0 breaks DefaultJWSProvider (namshi/jose package missing)

### ISSUE THREAD

**Issue by filisko** [lexik/LexikJWTAuthenticationBundle#834]
Hi,

Just experienced an issue with the library.

My **lexik_jwt_authentication.yaml** looks like this:
```yaml
lexik_jwt_authentication:
   # other stuff here ...
    encoder:
        service: lexik_jwt_authentication.encoder.default
        signature_algorithm: RS256
```
As you can see it depends on **DefaultJWSProvider** and the **RS256** signature algorithm.

When upgrading to **2.11.0**, composer removes `namshi/jose` package:
```
Package operations: 0 installs, 1 update, 1 removal
  - Removing namshi/jose (7.2.3)
  - Updating lexik/jwt-authentication-bundle (v2.10.6 => v2.11.0)
```

But **DefaultJWSProvider** actually uses it (e.g., **isAlgorithmSupportedForEngine()**), so the first thing anyone will realise is an exception:
```
InvalidArgumentException: The algorithm "RS256" is not supported for OpenSSL
```

Installing the package again fixes the issue.

The thing is, DefaultJWSProvider has the `@deprecated` tag, but it says it will be supported until version 3.0, so I guess it makes sense to keep the `namshi/jose` package and deprecate both in 3.0?
```
@deprecated since version 2.5, to be removed in 3.0
```

It seems the dependency was moved to `require-dev` in #816, so It doesn't seem to have been done in purpose? Also to note, the unit tests are passing of course because at the time of running them the dependency is included (dev).

![image](https://user-images.githubusercontent.com/8798694/107505968-b4a9da80-6b9d-11eb-8d7f-88847bd62519.png)

Thanks!
