### ISSUE TITLE
Question: Why does the bundle needs two firewalls?

### ISSUE THREAD

**Issue by naitsirch** [lexik/LexikJWTAuthenticationBundle#836]
I am planning to integrate the bundle into a Symfony application.

In the documentation the following example configuration for `config/packages/security.yaml` is given:

```yaml
security:
    # ...
    
    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

Why are two firewalls required for this to work? A usual form login does only need one firewall.

**Comment by db306** [comment]
The login checks whether the password and username is valid, whereas the second checks the validity of the access token

**Comment by naitsirch** [comment]
Thanks. I have assumed something like that. I have played arround with the cofings a bit and found out, that it is simply possible to reduce them to **one** firewall:

```yaml
security:
    firewalls:
        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            json_login:
                check_path: api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```

This works perfectly :-)

Does it make sense to update the docs? I think the current state makes it unnecessary complex.
