### ISSUE TITLE
Unrecognized option "acme_api.event.authentication_failure_listener" under "security".

### ISSUE THREAD

**Issue by UneMinute** [lexik/LexikJWTAuthenticationBundle#851]
Hi,
First, thank you A LOT to the whole team for your hard work!

I'm trying to customize the "authentication failure" response body, following your recommendations. 
But I keep getting the error: "Unrecognized option "acme_api.event.authentication_failure_listener" under "security"."
I feel like I might have forgotten something but can't figure out what.. 

Thank you in advance for your answer.

config/services.yaml
```
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider

            json_login:
                check_path: app_login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: app_logout
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```

src/EventListener/AuthenticationFailureListener.php
```
namespace App\EventListener;

use Lexik\Bundle\JWTAuthenticationBundle\Event\AuthenticationFailureEvent;
use Lexik\Bundle\JWTAuthenticationBundle\Response\JWTAuthenticationFailureResponse;

class AuthenticationFailureListener
{
    /**
     * @param AuthenticationFailureEvent $event
     */
    public function onAuthenticationFailureResponse(AuthenticationFailureEvent $event)
    {
        $data = [
            'status'  => '401 Unauthorized',
            'message' => 'Bad credentials, please verify that your username/password are correctly set',
        ];

        $response = new JWTAuthenticationFailureResponse('Bad credentials, please verify that your username/password are correctly set', '401 Unauthorized');

        $event->setResponse($response);
    }
}
```
