### ISSUE TITLE
Translate failure messages with _locale

### ISSUE THREAD

**Issue by barbhackk** [lexik/LexikJWTAuthenticationBundle#857]
Hi,

I want to translate the message using _locale with symfony.
Here is the configuration for login_check:
```
/**
     * @Route(
     *     "/{_locale}/api/login_check",
     *     name="api_login",
     *     requirements={
     *         "_locale": "en|fr",
     *     }
     * )
     * @return JsonResponse
     */
    public function api_login(): JsonResponse
    {
        $user = $this->getUser();

        return new Response([
            'email' => $user->getEmail(),
            'roles' => $user->getRoles(),
        ]);
    }

```

When I try to call the url '/fr/api/login_check' I have an error: Call to a member function getEmail() on null.

**I think I am not using the translation as it should. I want to be able to translate according to a locale passed as a parameter in the URL**

security.yaml :
```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

Thanks for your help,

Seb
