### ISSUE TITLE
401 JWT Token not found

### ISSUE THREAD

**Issue by krajcikondra** [lexik/LexikJWTAuthenticationBundle#875]
Hi,

I use Symfony 5 and I am solving following problem.

Send POST request to **api/login_check** wtih json
`{username: 'test', password: 'test'}`

Response is ok:

`{token: 'some_token'}`

Problem occurs in next request: When I send request GET **/user/get-current** with header 
`{ Authorization: 'Bearer some_token'}`

I get error **401 JWT Token not found**

In terminal output is nothing interesting, maybe only:

```
[PHP        ] Jun 14 09:57:07 |DEBUG  | SECURI Guard authenticator does not support the request. 
[PHP        ] Jun 14 09:57:07 |INFO   | PHP    User Deprecated: Since gos/web-socket-bundle 3.1: The "gos_web_socket.data_collector.websocket" service is deprecated and will be removed in GosWebSocketBundle 4.0. 

```

Do you know what can be problem?

My config:

services.yaml
```
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    sendgrid_api_key: PleaseEnterSendGridApiKey

expert_coder_swiftmailer_send_grid:
    api_key: mujApiKlic
    categories: [my_category] # optional, will be added to all mails sent (can be seen on sendgrid dashboard)

gos_web_socket:
    server:
        port: 8888        # The port the socket server will listen on
        host: 127.0.0.1   # The host ip to bind to
        router:
            resources:
                - '%kernel.project_dir%/config/pubsub/routing.yaml'
    client:
        firewall: [api, login, dev, main] # Can be an array of firewalls
        session_handler: 'session.handler.pdo'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    app.websocket.topic.acme:
        class: App\Websocket\Topic\AcmeTopic
        tags:
            - { name: gos_web_socket.topic }

    swiftmailer.mailer.transport.expertcoder_swift_mailer.send_grid.transport:
        alias: expertcoder_swift_mailer.send_grid.transport

    SKAgarwal\GoogleApi\PlacesApi:
        arguments:
            $key: 'my_api_key'

    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - !service { class: PDO, factory: ['@database_connection', 'getWrappedConnection'] }
            - { lock_mode: 0 }

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\Admin\:
        resource: '../src/Controller/Admin'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     db
        port:     5432
        dbname:   testApp
        user:     root
        password: root
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                pow: Oro\ORM\Query\AST\Functions\Numeric\Pow
```

security.yaml

```
security:
    encoders:
        App\Entity\User: bcrypt


    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: nickname
    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern:   ^/api
            stateless: true
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication
            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/auth/sign-up, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/sign-in, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/login-check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/validate-sign-up, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/phone-verify, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/restore-forgotten-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/set-new-password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/verify-token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```
