### ISSUE TITLE
Remove guard related service definitions when authenticator manager is enabled.

### ISSUE THREAD

**Issue by chalasr** [lexik/LexikJWTAuthenticationBundle#879]

**Comment by jzecca** [comment]
I get this deprecation notice after migrating to the new authentication system:

```
1x: The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator"
    class implements "Symfony\Component\Security\Guard\AuthenticatorInterface"
    that is deprecated since Symfony 5.3, use the new authenticator system instead.
```

The deprecation only shows the first time I run my tests (or after running `bin/console cache:clear -e test`).

Could it be related to this issue?

**Comment by chalasr** [comment]
@jzecca I think so, yes. I'm looking at it.

**Comment by asumkin** [comment]
I still get deprecation message after composer upgrade

Remaining indirect deprecation notices (1)

  1x: The "Lexik\Bundle\JWTAuthenticationBundle\Security\Guard\JWTTokenAuthenticator" class implements "Symfony\Component\Security\Guard\AuthenticatorInterface" that is deprecated since Symfony 5.3, use the new authenticator system instead.

**Comment by chalasr** [comment]
Did you also upgrade your security config to use the new authenticator instead of Guard?

**Comment by asumkin** [comment]
You meant this 

```
api:
            pattern:   ^/api
            stateless: true
            custom_authenticators:
                - lexik_jwt_authentication.jwt_token_authenticator

```
?

**Comment by chalasr** [comment]
Nope, I mean: 

```
api:
            pattern:   ^/api
            stateless: true
            jwt: ~
```

As documented and mentioned in https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/UPGRADE-2.12.md.
