### ISSUE TITLE
Why is the token not validated if it is empty? 

### ISSUE THREAD

**Issue by a2550559** [lexik/LexikJWTAuthenticationBundle#902]
Hello! Help me pls.

If I pass a token in the request, then it is checked and if the token is not correct, then I get an error.

If the token is not passed in the request, then it is not checked. 

How to show an error if the token is empty ?

**Security.yaml**
```
 firewalls:
        api:
            pattern: ^/rest/
            methods: [GET, POST, PUT, PATCH, OPTIONS]
            provider: app_user_provider
            stateless: ~
            anonymous: false
            entry_point: App\Security\MyCustomAuthenticator
            jwt: ~
            custom_authenticators:
                - App\Security\MyCustomAuthenticator
        api_auth:
            pattern: /auth
            provider: app_user_provider
            stateless: true
            custom_authenticators:
                - App\Security\MyCustomAuthenticator
```

**lexik_jwt_authentication.yaml**
```
lexik_jwt_authentication:
    secret_key: '---'
    public_key: '---'
    pass_phrase: '---'
    token_ttl: 3600
    user_identity_field: login
    encoder:
        service: lexik_jwt_authentication.encoder.lcobucci
        signature_algorithm: RS256
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
```
