### ISSUE TITLE
Extending JWTTokenAuthenticator in symfony 5.3

### ISSUE THREAD

**Issue by john-dufrene-dev** [lexik/LexikJWTAuthenticationBundle#915]
I need to extend Authenticator related to  [https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md](url)

When I extend, I have this depreciation, anyone now I can extend with the new symfony system ?

Thank's in advance.

**Comment by fd6130** [comment]
Hmmm seems like you need to write your own authenticator? I think the current jwt authenticator is this one:

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Security/Authenticator/JWTAuthenticator.php

@chalasr Any idea about extending the authenticator in new authenticator system? This bundle latest docs still using the guard authenticator example.

**Comment by chalasr** [comment]
Indeed, this part of the docs needs an update. The diff should be quite small since the new authenticator provides the same extension points.

**Comment by fd6130** [comment]
I think we can just extend the authenticator from this bundle like this:

```php
namespace App\Security\Authenticator;

use Lexik\Bundle\JWTAuthenticationBundle\Security\Authenticator\JwtAuthenticator;

class CustomAuthenticator extends JWTAuthenticator
{

}
```

But not sure how should we put that in `security.yaml`:

```yaml
api:
    pattern:   ^/api
    stateless: true
    jwt:
       - App\Security\Authenticator\CustomAuthenticator

```

I wonder is it correct way to config custom authenticator in this bundle?

**Comment by chalasr** [comment]
It should be more like this:

```yaml
api:
    pattern:   ^/api
    stateless: true
    custom_authenticators:
        - App\Security\Authenticator\CustomAuthenticator
```
