### ISSUE TITLE
Question - how to skip route/url from validation?

### ISSUE THREAD

**Issue by Volmarg** [lexik/LexikJWTAuthenticationBundle#917]
Hello,

Is there some simple way to skip the route from validation.

- **Core**: Symfony 5.x
- **File**: security.yaml

```yaml
    firewalls:
        login:
            provider: app_user_provider
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            stateless: true
            jwt: ~
```

It's about the `main` firewall. I would like to put a routes which should be skipped from validation. Any idea how to handle it?

Anything like:

```yaml
        main:
            stateless: true
            jwt: ~
         exclude: ['url1', 'url2']
```

?
