### ISSUE TITLE
[Symfony 5.3.X] Unable to find the controller for path \"/api/login_check\". The route is wrongly configured.

### ISSUE THREAD

**Issue by Neutron-Pro** [lexik/LexikJWTAuthenticationBundle#926]
Hi,

I encountered a problem while installing your **LexikJWTAuthenticationBundle**.

Recently, I upgraded to the new version of **Symfony** and they changed a lot of things about authentication. So I wanted to build an API using your **JWT** bundle.

Following your documentation (and of course taking the **Symfony 5.3.X** documentation), I encountered this error when going to the `POST /api/login_check` route.

```json
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "status": 404,
  "detail": "Unable to find the controller for path \"/api/login_check\". The route is wrongly configured.",
  "class": "Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException",
  "trace": [
    ...
  ]
}
```

I show you my configuration for the **LexikJWTAuthenticationBundle**:

`security.yaml`
```yml
security:
    enable_authenticator_manager: true
    
    password_hashers:
        App\Entity\User: 'auto'
        
    providers:
        app_user:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user
            jwt: ~

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

`routes.yaml`
```yml
api_login_check:
    path: /api/login_check
```

`lexik_jwt_authentication.yaml`
```yml
lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 300
```

`bundle.php`
```php
return [
  ...,
  Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true]
]
```

You have all my configuration, the problem would probably come from `route.yaml` as it requires a `controller` however, the authentication controller is already done in your bundle.

Thanks for all !

**Comment by fd6130** [comment]
Make sure your login POST request have header `Content-Type: application/json`. If you use normal POST request and not json POST request it will error.

**Comment by Neutron-Pro** [comment]
I'm in **POST**, my body is a **JSON** and the **Content-Type** is **application/json**.

```sh
curl --location --request POST 'http://localhost:8080/api/login_check' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "admin@demo.com",
    "password": "123456789"
}'
```

**Comment by fd6130** [comment]
I think it is because the firewall ordering issue. Try move your `login` before `api` in firewall.

```
firewalls:
        # ...

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
       
        api:
            pattern: ^/api
            stateless: true
            provider: app_user
            jwt: ~

```
