### ISSUE TITLE
Unable to find the controller for path "/api/login_check". The route is wrongly configured.

### ISSUE THREAD

**Issue by thomasFoglia** [lexik/LexikJWTAuthenticationBundle#939]
Hello,

I have this error message when I call /login_check (404 error) :
> Unable to find the controller for path "/api/login_check". The route is wrongly configured.

here are my firewalls  : The order is OK ("main" is well after login)
```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login_check
            stateless: true
            provider: provider_auth_email_or_username
            json_login:
                check_path: api_login_check # or api_login_check as defined in config/routes.yaml
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        registration:
            pattern: ^/api/users
            stateless: true
            methods: [POST]

        api:
            pattern: ^/api
            provider: provider_auth_email_or_username
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            lazy: true
```

Routes.yml :
```
api_login_check:
    path: /api/login_check
```

With postman, No error ! 200 and /login_check return the token.

But, on my frontend, I got the 404 error.
here is my code :
```
var data_login = {
    "email": value_email,
    "password": value_password
};

$.ajax({
    url: API_BASE + "/login_check",
    type: "POST",
    data: JSON.stringify(data_login),
    async: false,
    contentType: "application/json",
    complete: function (xhr, textStatus) {
        var status = xhr.status;
        if (status === 200) {
            var token = JSON.parse(xhr.responseText)['token'];
            //
        } else if (status === 401) {
             //
        }
    },
    error: function (xhr, status, error) {
        //
    }
});
```

Why does this work on Postman but not on the frontend with jquery? I have however the Content-Type at "application / json" in the ajax call.

thank you !!
