### ISSUE TITLE
Extending JWTAuthenticator - How can I add services to my extension?

### ISSUE THREAD

**Issue by TristanPouliquen** [lexik/LexikJWTAuthenticationBundle#945]
Hello,

I'm trying to extend the new JWTAuthenticator (https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md), and I need to inject in my extension the reference to a custom repository, eg:
```php
class CustomJWTAuthenticator extends JWTAuthenticator
{
    private CustomRepository $repository;

    public function __construct(
        JWTTokenManagerInterface $jwtManager,
        EventDispatcherInterface $dispatcher,
        TokenExtractorInterface $tokenExtractor,
        UserProviderInterface $userProvider,
        CustomRepository $repository
    ) {
        $this->repository = $repository;
        parent::__construct($jwtManager, $dispatcher, $tokenExtractor, $userProvider);
    }
    // ...
}
```

My config is:
```yaml
# services_yaml
// ...
app.custom_jwt_authenticator:
    class: App\Security\Authenticator\JwtTokenAuthenticator
    parent: lexik_jwt_authentication.security.jwt_authenticator

# security.yaml
// ...
        api:
            pattern: ^/graphql|^/api/v1/(?!tokens)
            stateless: true
            provider: 'users'
            jwt:
                authenticator: app.custom_jwt_authenticator
            custom_authenticators:
                     - App\Security\Authenticator\LegacyJwtTokenAuthenticator
                     - App\Security\Authenticator\OAuthAuthenticator
```

I've followed the steps in the documentation,  `cache:clear` works correctly but when I try to interact with my firewalls, I get this error:
`Too few arguments to function App\Security\Authenticator\JwtTokenAuthenticator::__construct(), 4 passed in /home/assoconnect/backend/var/cache/dev/ContainerOdA0ED5/getSecurity_Authenticator_Jwt_ApiService.php on line 26 and exactly 5 expected`

And seeing the stack trace, it looks like Symfony tries to instantiate my service with only  the 4 arguments from the LexikJWT bundle. 

What am I missing? 

Thanks in advance :-)

**Comment by fd6130** [comment]
I'm not really sure about this. But i do have a workaround for this case (by manually wiring arguments) :

```yaml
app.custom_jwt_authenticator:
    class: App\Security\Authenticator\JwtTokenAuthenticator
    parent: lexik_jwt_authentication.security.jwt_authenticator
    arguments:
         $repository: '@App\Repository\CustomRepository'
```

Hope that help!
