### ISSUE TITLE
Cannot extend JWTAuthenticator (symfony 5.3)

### ISSUE THREAD

**Issue by geoffroyp** [lexik/LexikJWTAuthenticationBundle#946]
Hi guys,

As mentionned in the "support" part of the readme file from this repository, I have posted a message on stackoverflow with  lexikjwtauthbundle tag, but didn't received much replies. On top of this, it might actually be a bug so I thought it might be a good idea to post it here as well.

You can find my original post here: https://stackoverflow.com/questions/69823739/constructor-error-when-trying-to-extend-lexikjwtauthbundle-jwtauthenticator

Long story short: when I try to extend JWTAuthenticator, I get and error message telling me the 4th argument ($userProvider) is supposed to be of type UserProviderInterface, but it got an empty string instead. And indeed, it the call stack, I can see that there is a piece of code in the cache (probably the service container) that calls the constructor of my custom authenticator with an empty string in stead of the 4th argument. Thus, autowiring cannot work since it gets "overwritten".

here's the criminal:

in in /var/www/api/api/var/cache/dev/ContainerU4stufr/getApp_KsAuthenticatorService.php -> __construct (line 27)

`include_once \dirname(__DIR__, 4).'/vendor/symfony/security-http/EntryPoint/AuthenticationEntryPointInterface.php';        include_once \dirname(__DIR__, 4).'/vendor/lexik/jwt-authentication-bundle/Security/Authenticator/ForwardCompatAuthenticatorTrait.php';        include_once \dirname(__DIR__, 4).'/vendor/lexik/jwt-authentication-bundle/Security/Authenticator/JWTAuthenticator.php';        include_once \dirname(__DIR__, 4).'/src/Security/KsAuthenticator.php';        return $container->privates['app.ks_authenticator'] = new \App\Security\KsAuthenticator(($container->services['lexik_jwt_authentication.jwt_manager'] ?? $container->load('getLexikJwtAuthentication_JwtManagerService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->privates['lexik_jwt_authentication.extractor.chain_extractor'] ?? $container->load('getLexikJwtAuthentication_Extractor_ChainExtractorService')), '');    }`

So...is it me who's doing womething wrong, or is there a bug somewhere in the lib?

**Comment by fd6130** [comment]
I think it is because misconfiguration of your `security.yaml`.  Just put the custom authenticator id in main firewall `jwt` key.

https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/6-extending-jwt-authenticator.md

Try with this config instead:
```yaml
security:
    ...
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            provider: app_user_provider
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        main:
            pattern: ^/api
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt:
                 authenticator: app.ks_authenticator
```

**Comment by geoffroyp** [comment]
Well thanks a lot, it indeed did the trick!

However, the extension still does not work. All I did in my own authenticator is copy/paste all methods (except getters) from JWTAuthenticator, then replace the logic by `dd('custom authenticator)`, but all I get when I call /api/login_check is "Unable to create a signed JWT from the given configuration.", from vendor/lexik/jwt-authentication-bundle/Encoder/LcobucciJWTEncoder.php (line 38)

So since I don't get any dd() frist, I believe it means that my authenticator is not called. Am I wrong? (I don't see in in the callstack either)

edit: well, if I call something else than /api/login-check it does indeed call my custom authenticator. So the error might be not linked to this. I'll continue investigating

**Comment by fd6130** [comment]
> but all I get when I call /api/login_check is "Unable to create a signed JWT from the given configuration.", from vendor/lexik/jwt-authentication-bundle/Encoder/LcobucciJWTEncoder.php (line 38)

Can you post your lexik configuration yaml here from `config/packages` ? Seems like something wrong with your JWT passphrase or something.

And, how about try this config?

```yaml
# security.yaml
        api:
            pattern: ^/api
            provider: app_user_provider
            stateless: true
            jwt:
                 authenticator: app.ks_authenticator

        main:
            lazy: true
```

My guessing is that the main firewall is the culprit here.
