### ISSUE TITLE
Database-less user provider with a non-default username

### ISSUE THREAD

**Issue by geoffroyp** [lexik/LexikJWTAuthenticationBundle#953]
Greetings,

I would like to create a database-less user provider as explained on this documentation page:
https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/8-jwt-user-provider.md

Problem: when I do this, I cannot generate token anymore because of "invalid credential". Since my "username" field is called "login" in my user entity, I believe that was the problem, and searched for a way to pass this information to the user provider.
But since I foudn no option in your documentation to do so, I tried to rename "login" into "username", and change the getters accordingly. But to my surprise, it did not change anything. I still get "invalid credentials"

For reference, here's (part of) my security.yaml that works:

```
security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        ks_hasher:
            id: 'App\Security\Hasher\KsPasswordHasher'
            algorithm: 'md5'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\Kscommon\User
                property: login
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            provider: app_user_provider
            user_checker: App\Security\KsChecker
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            lazy: true
            provider: app_user_provider
            stateless: true
            jwt:
                authenticator: app.ks_authenticator
```

And here's the one that fail authentication:
```
security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        ks_hasher:
            id: 'App\Security\Hasher\KsPasswordHasher'
            algorithm: 'md5'

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        jwt:
            lexik_jwt: ~
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            provider: jwt
            user_checker: App\Security\KsChecker
            pattern: ^/api/login_check
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            lazy: true
            stateless: true
            jwt:
                provider: jwt
                authenticator: app.ks_authenticator
```

Did I miss something?
Also, is there a way to use a different field than "username" for JWT user provider?

Cheers,
