### ISSUE TITLE
UserBadge does not send payload to security user

### ISSUE THREAD

**Issue by mbraeuner** [lexik/LexikJWTAuthenticationBundle#955]
Hi,

I can not figuring out what I'm doing wrong If I setup a [database-less user provider](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/8-jwt-user-provider.md) with symfony 5.3 like descibed .

With custom user class "App\Security\User"

When I send my users data to the login_check the paylod is empty, since the UserBadge provides only one parameter
[$this->user = ($this->userLoader)($this->userIdentifier);](https://github.com/symfony/symfony/blob/bde6c0987bbafdf4060f17d57f680ffae86e0b59/src/Symfony/Component/Security/Http/Authenticator/Passport/Badge/UserBadge.php#L67)
Therefore the payload recived by createFromPayload is empty and the user creation will fail, because we have to few arguments to construct the user

```yaml
security:
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true
    providers:
        jwt:
            lexik_jwt:
                class: App\Security\User

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            jwt: ~
            # provider: jwt
            json_login:
                check_path: login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
```

This is the trace
![image](https://user-images.githubusercontent.com/29225156/142720831-ebaa01ec-66a0-4171-b79c-36c8a73f5b8b.png)

If I cut down the constructor to only username the CheckCredentialsListener.php checks the password, which is not present in users data and failes. It seems that I missed something in the configuration of the authentification.
I tried to extend the payload. The [events](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/2.x/Resources/doc/2-data-customization.md) are not fired right now,
