### ISSUE TITLE
cannot fetch currently logged in user on /login page

### ISSUE THREAD

**Issue by desmax** [lexik/LexikJWTAuthenticationBundle#964]
On login page I want to do a redirect in case User is logged in, my configuration follows closely what is written in documentation, but on log in  page I can't fetch current user. 

```        
       login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern:   ^/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

....

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
```
