### ISSUE TITLE
Still got JWT Token Not Found Error with Symfony 5.4

### ISSUE THREAD

**Issue by Aaarrrgggh** [lexik/LexikJWTAuthenticationBundle#970]
Hi,

I downloaded the bundle and tried it with Symfony 5.4. I have the famous error "JWT Token Not Found". 
For testing, I did the same request with brut JS, PHP and Authentication Bearer is well sent and founded by PHP with getAllHeaders(); method.
I tried to do the same process with Symfony and Authentication Bearer is not present in the Symfony Headers.

Apache configuration is Okay with 

```
RewriteCond %{HTTP:Authorization} .
RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```

My code (security.yml) : 

```
 login:
            pattern: ^/api/auth/login
            stateless: true
            provider: user
            json_login:
                check_path: api_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~
```

```
    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix:  Bearer 
            name:    Authorization
```

Is something missing?

Thanks
