### ISSUE TITLE
1.1.0 -> 1.2.0 upgrade

### ISSUE THREAD

**Issue by marrek13** [lexik/LexikJWTAuthenticationBundle#98]
Hi,
I am writing a project using your bundle. I made and update today, but after it everything stopped working. There is no error from server, no information in logs(both of symfony and apache), just empty 500 error after the "OPTIONS" request. Is there something that I should change in the configuration after that update?

My security.yml:
```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:             ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        gettoken:
            pattern:  ^/api/users/logins$
            stateless: true
            provider: fos_userbundle
            gfreeau_get_jwt:
                username_parameter: username
                password_parameter: password
                post_only: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            provider: fos_userbundle
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
            anonymous: true

    access_control:
        - { path: ^/api/users/logins$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY]}
```
