### ISSUE TITLE
No route found for "POST https://localhost:8000/api/login"

### ISSUE THREAD

**Issue by oragion62** [lexik/LexikJWTAuthenticationBundle#981]
Hi,

I use your JWT bundle for 4 months approximately and I really appreciate to work with.

I took a previous project I've made with your bundle and symfony. I tried to reinstall it locally.

I've made a `composer install --ignore-platform-reqs` because it's said there is a problem to install laminas/laminas-code and friendofphp/proxy-manager-lts because they use php 7.4 and I have a PHP 8.1.1.

Once I had my vendor folder created, I've made all configurations but I always have this error message : No route found for "POST https://localhost:8000/api/login"

You can find all my configuration here

composer.json
```json
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.0.0",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "doctrine/annotations": "^1.13",
        "lexik/jwt-authentication-bundle": "^2.12",
        "nelmio/cors-bundle": "^2.1",
        "symfony/console": "5.3.*",
        "symfony/dotenv": "5.3.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.3.*",
        "symfony/orm-pack": "^2.1",
        "symfony/runtime": "5.3.*",
        "symfony/security-bundle": "5.3.*",
        "symfony/serializer": "5.3.*",
        "symfony/validator": "5.3.*",
        "symfony/yaml": "5.3.*"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "5.3.*"
        }
    },
    "require-dev": {
        "symfony/maker-bundle": "^1.33"
    }
}
```

security.yaml
```yaml
security:
    # https://symfony.com/doc/current/security/experimental_authenticators.html
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/
            stateless: true
            jwt: ~
        #dev:
            #pattern: ^/(_(profiler|wdt)|css|images|js)/
            #security: false
        #main:
            #lazy: true
            #provider: app_user_provider

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/,      roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```

routes.yaml
```yaml
api_login_check:
  path: /api/login_check
```

.env
```
###> lexik/jwt-authentication-bundle ###
JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
JWT_PASSPHRASE=my-passphrase
###< lexik/jwt-authentication-bundle ###
```

Of course, I have a folder : config/jwt with my certificates

Don't hesitate if you want more informations

Thank you for your help !! :)

Guillaume R.

**Comment by sensorario** [comment]
Sorry, .. but I see just

 - /login
 - /api/login_check
 
 So, .. I think `/api/login` should not exists.

**Comment by oragion62** [comment]
Hi, 

Thank you for your response.

Sorry, I've made some changes to try to correct the problem before my previous message, I didn't correct.

But now, I have in my security.yaml

```yaml
firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: api_login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
```

```yaml
access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,      roles: IS_AUTHENTICATED_FULLY }
```

I always have my route not found (POST https://127.0.0.1:8000/api/login) :/

Thanks

**Comment by fd6130** [comment]
Is your request header contain content-type:application/json when you call the api?

**Comment by oragion62** [comment]
yes @fd6130 as you can see on the screenshoot

![image](https://user-images.githubusercontent.com/98232463/150675071-b675dc31-6ec1-4ad0-96d0-b80a94c73c47.png)

**Comment by fd6130** [comment]
> yes @fd6130 as you can see on the screenshoot
> 
> ![image](https://user-images.githubusercontent.com/98232463/150675071-b675dc31-6ec1-4ad0-96d0-b80a94c73c47.png)
> 

How about use api/login_check  instead?

**Comment by oragion62** [comment]
It works with /api/login_check, really strange ...

**Comment by chalasr** [comment]
Doesn’t `/api/login_check` correspond to the route used as `check_path`? Changing the path on this route’s definition should work.

**Comment by oragion62** [comment]
yes, it is @chalasr but it's really strange because /api/login should works in the version installed on my web server it works, so I don't understand why I have this error.

So I'll change `check_path` :)

Thanks all for your messages :)

**Comment by chalasr** [comment]
You're welcome.

**Comment by FournyP** [comment]
Hi, I have the same problem here

PHP version: 8.1.2
Symfony version: 6.0

Here my following config file:
```yaml
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\ServiceUser:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\ServiceUser
                property: uuid
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: api_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
```

I have follow @oragion62 instructions to fix the issue but it doesn't work

I have created a SecurityController:
```php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SecurityController extends AbstractController
{
    #[Route('/api/login', name: 'api_login', methods: ['POST'])]
    public function index(): Response
    {
        $user = $this->getUser();
        return $this->json([
            'roles' => $user->getRoles(),
        ]);
    }
}
```

And I got the following error
No route found for "POST http://127.0.0.1:8000/api/login"

Do you have any idea where it could come from ?

Have a good day
