### ISSUE TITLE
Authentication listener

### ISSUE THREAD

**Issue by yelmontaser** [lexik/LexikJWTAuthenticationBundle#99]
Hi,
Is there a way to use another Firewall Listener that base as the provider?

eg:
```yml
lexik_jwt:
    authentication_provider: jwt.security.authentication.provider
    authentication_listener: jwt.security.authentication.listener
```

Thanks.
