### ISSUE TITLE
Each request returns a 401

### ISSUE THREAD

**Issue by martinkobelka** [lexik/LexikJWTAuthenticationBundle#992]
Good day. I'm trying to run jwt on my symfony project.

Login works for me. When I send a request to /api/login_check, I can see my token in response.

The problem is, I can't authorize myself. When I send response with header: 
`Authorization: Bearer --token--` 

I always get the answer "401 unauthorized".  Where can be problém? I tried it many times. I created ten new projects and followed by several different tutorials. I always got the same result.  When I delete a token, I get a message that the token is not found. So symfony sees my token. But he doesn't authorize me. Here are my source codes.

There is my repository [https://github.com/martinkobelka/bad_symfony](https://github.com/martinkobelka/bad_symfony)

This curl request returns me token
`curl -X POST -H "Content-Type: application/json" http://localhost:8000/api/login_check -d '{"username":"test@test.com","password":"test"}' `

But this requestst returns me 401 not authorized
`curl --location --request GET 'http://localhost:8000/api'
--header 'Authorization: Bearer --token--'`

It it bug, or I'm doing something wrong

**Comment by fd6130** [comment]
How about this? Place the `provider` option in your `api` key.

```yaml
security:
         # ...
         api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
```
