### ISSUE TITLE
Configure JWT audience claim

### ISSUE THREAD

**Issue by lobodol** [lexik/LexikJWTAuthenticationBundle#993]
Hello there,

I'm using this bundle in a Symfony app, in a microservice architecture.

I'd like each service to check audience claim in order to reject JWT if not listed in it.

Furthermore, I could not find a way to configure it somewhere.  
I imagine something like this:

```yaml
# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
  audience:
    - service1
    - service2
```

Is there a way to configure audience claim of generated JWT?

Regards,
